// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Entities;


namespace FarVision.Mes
{
    public partial class Accn : Entity<int>
   {
        public string AccNo { get; set; }
        public string Name { get; set; }
        public string AccNoUp { get; set; }
        public string Dc { get; set; }
        public string Cls { get; set; }
        public string AccNoB { get; set; }
        public string AccNoE { get; set; }
        public string SwObj { get; set; }
        public string SwArp { get; set; }
        public string SwInv { get; set; }
        public string SwTax { get; set; }
        public string SwCas { get; set; }
        public string KnCst { get; set; }
        public string CshFr { get; set; }
        public string OthSw1 { get; set; }
        public string OthSw2 { get; set; }
        public string Curid { get; set; }
        public string EngName { get; set; }
        public string RelCls { get; set; }
        public string Rem { get; set; }
        public DateTime? StopDd { get; set; }
        public string ClsId1 { get; set; }
        public string ClsId2 { get; set; }
        public string ClsId3 { get; set; }
        public string ClsId4 { get; set; }
        public string ChkCashFlow { get; set; }
        public string ChkCsh { get; set; }
        public string KmType { get; set; }
        public string KmId { get; set; }
        public string AccNoStd { get; set; }
        public byte[] UpDd { get; set; }
        public string WordNo1 { get; set; }
        public string WordNo2 { get; set; }
        public string WordNo3 { get; set; }
        public string WordNo4 { get; set; }
        public string WordNo5 { get; set; }
        public string Kind { get; set; }
        public string Accno2 { get; set; }
        public string CurType { get; set; }
        public string AccNoIfrs { get; set; }
        public string OffsetId { get; set; }
        public string ExcId { get; set; }
        public string AccNoGstd { get; set; }
        public string AccNoQyjz { get; set; }
    }
}