// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Bacomp
 : Entity<int>    {
        
        public string No { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public DateTime OpenDate { get; set; }
        public string ComName { get; set; }
        public string CurNo { get; set; }
        public string CurName { get; set; }
        public string CurSymbol { get; set; }
        public string Orgcode { get; set; }
        public string NameS { get; set; }
        public string Domain { get; set; }
        public string Addr { get; set; }
        public string Lp { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string Zap { get; set; }
        public string Email { get; set; }
        public string TaxNo { get; set; }
        public Guid? Picture { get; set; }
        public string NameEn { get; set; }
        public string AddrEn { get; set; }
        public string CustomCode { get; set; }
        public string Memo { get; set; }
        public int UserId { get; set; }
        public DateTime InputDate { get; set; }
        public int Flag { get; set; }
    }
}