// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BarcodeProductMap
 : Entity<int>    {
        
        public string Barcode { get; set; }
        public string PrdNo { get; set; }
        public string PrdSnm { get; set; }
        public string ModNo { get; set; }
        public string IdNo { get; set; }
    }
}