// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BatchgRec
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string PrdNo { get; set; }
        public string BatNo { get; set; }
        public DateTime Sysdate { get; set; }
        public string SalNo { get; set; }
    }
}