// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BatRec1
 : Entity<int>    {
        public string BatNo { get; set; }
        public string PrdNo { get; set; }
        public string Wh { get; set; }
        public string PrdMark { get; set; }
        public decimal? QtyIn { get; set; }
        public decimal? QtyOut { get; set; }
        public decimal? Cst { get; set; }
        public decimal? QtyLrn { get; set; }
        public decimal? QtyBrw { get; set; }
        public decimal? QtyOnWay { get; set; }
        public decimal? QtyOnPrc { get; set; }
        public decimal? QtyOnRsv { get; set; }
        public decimal? QtyOnOdr { get; set; }
        public string ClsId { get; set; }
        public decimal? Qty1In { get; set; }
        public decimal? Qty1Out { get; set; }
        public decimal? Qty1Lrn { get; set; }
        public decimal? Qty1Brw { get; set; }
        public string Pass { get; set; }
        public string Usr { get; set; }
        public DateTime? ValidDd { get; set; }
        public decimal? QtyMax { get; set; }
        public decimal? QtyMin { get; set; }
        public DateTime? LstOtd { get; set; }
        public DateTime? LstInd { get; set; }
        public decimal? QtySa { get; set; }
        public decimal? QtyRk { get; set; }
        public decimal? QtyZg { get; set; }
        public decimal? QtyCk { get; set; }
        public decimal? QtySq { get; set; }
        public string Rem { get; set; }
        public DateTime? ChqcDd { get; set; }
        public decimal? QtySw { get; set; }
        public decimal? QtyWx { get; set; }
        public decimal? QtyWs { get; set; }
        public decimal? QtyWsKc { get; set; }
        public decimal? QtyQl { get; set; }
        public decimal? QtyQ2 { get; set; }
        public decimal? QtyQ2Yl { get; set; }
        public decimal? QtyQ3 { get; set; }
        public decimal? CstBx { get; set; }
        public decimal? QtySqr { get; set; }
        public decimal? QtySqc { get; set; }
        public decimal? QtyLock { get; set; }
        public DateTime? ScDd { get; set; }
        public decimal? QtyJh { get; set; }
        public DateTime? LstOtdQc { get; set; }
        public DateTime? LstIndQc { get; set; }
        public byte[] UpDd { get; set; }
        public decimal? Qty1Lock { get; set; }
        public decimal? CstIfrs { get; set; }
    }
}