// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BfFilter
 : Entity<int>    {
        
        public string No { get; set; }
        public int Type { get; set; }
        public string Category { get; set; }
        public bool Isdefault { get; set; }
        public int Iuserid { get; set; }
        public byte[] Viewdata { get; set; }
    }
}