// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BfRptTemplets1
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string Parentbusino { get; set; }
        public string Childbusino { get; set; }
        public string Parentkeyname { get; set; }
        public string Childfkeyname { get; set; }

        public virtual BfRptTempletC MidNavigation { get; set; }
    }
}