// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BfRptTempletS
 : Entity<int>    {
        
        public string Busino { get; set; }
        public string Busikind { get; set; }
        public string Name { get; set; }
        public int Isdefault { get; set; }
        public string Memo { get; set; }
        public string Userno { get; set; }
        public DateTime Inputdate { get; set; }
        public int Flag { get; set; }
        public byte[] Viewdata { get; set; }
    }
}