// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class BilSpc
 : Entity<int>    {
        
        public string BilId { get; set; }
        public string SpcId { get; set; }
        public string SpcNo { get; set; }
        public string Name { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
    }
}