// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CallInfo
 : Entity<int>    {
        
        public string CallTypeNo { get; set; }
        public string RsNo { get; set; }
        public string RsDesp { get; set; }
        public string CallDep { get; set; }
        public string CallSalNo { get; set; }
        public DateTime? CallDate { get; set; }
        public string SebNo { get; set; }
        public string CallPad { get; set; }
        public string CallPadIp { get; set; }
        public DateTime SysDate { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string BusiNo { get; set; }
        public string CallSta { get; set; }
        public string SourceNo { get; set; }
        public string ToBillNo { get; set; }
        public string AlmsgNo { get; set; }
        public string ResetUsr { get; set; }
    }
}