// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Casn
 : Entity<int>    {
        
        public string CasNo { get; set; }
        public string RefNo { get; set; }
        public string Cus { get; set; }
        public string CusNo { get; set; }
        public DateTime? OpnDat { get; set; }
        public DateTime? EndDat { get; set; }
        public string Name { get; set; }
        public decimal? Amtn { get; set; }
        public decimal? AmtnAdd { get; set; }
        public decimal? AmtnSub { get; set; }
        public DateTime? ClsDat { get; set; }
        public decimal? EndRto { get; set; }
        public string ClsMth { get; set; }
        public decimal? Cst1 { get; set; }
        public decimal? Cst2 { get; set; }
        public decimal? Cst3 { get; set; }
        public decimal? Cst4 { get; set; }
        public string Dep { get; set; }
        public string CasOk { get; set; }
        public string Rem { get; set; }
        public string Adr1 { get; set; }
        public string AgNo { get; set; }
        public string AgName { get; set; }
        public string CasVer { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsId { get; set; }
        public string Usr { get; set; }
        public short? DayHh { get; set; }
        public short? WeekHh { get; set; }
        public short? MonthDd { get; set; }
        public string BanNo { get; set; }
        public string FileId { get; set; }
        public string Type { get; set; }
        public string Up { get; set; }
        public string Snm { get; set; }
        public byte[] UpDd { get; set; }
        public string SalNo { get; set; }
        public string DfUsr { get; set; }
        public string DfTel { get; set; }
        public decimal? Qty1Rcv { get; set; }
        public decimal? Qty1Fined { get; set; }
        public string RemRcv { get; set; }
        public string MobId { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public string Ut1 { get; set; }
        public decimal? AmtnZb { get; set; }
        public DateTime? ClsDdZb { get; set; }
        public string ClsIdZb { get; set; }
        public string TempId { get; set; }
        public int? PerZb { get; set; }
        public decimal? LossRate1 { get; set; }
        public decimal? LossRate2 { get; set; }
        public decimal? AmtnJs { get; set; }
        public string SupCode { get; set; }
        public string TaxpayerCode { get; set; }
        public string BnkName { get; set; }
        public string IdCode { get; set; }
        public Guid? CtFile { get; set; }
        public string CtFileName { get; set; }
        public DateTime? SignDd { get; set; }
        public decimal? CtRtnRto { get; set; }
        public decimal? AmtnTarget { get; set; }
        public string AccDays { get; set; }
        public string RcvType { get; set; }
        public decimal? Pay1Amtn { get; set; }
        public decimal? Pay2Amtn { get; set; }
        public decimal? Pay2Days { get; set; }
        public string IdxNo { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string BilType { get; set; }
        public string DataSrc { get; set; }
        public string AutoBil { get; set; }
        public decimal? RtoHb { get; set; }
        public decimal? RtoXk { get; set; }
        public string ReturnId { get; set; }
        public decimal? AmtnJh { get; set; }
        public string FxNo { get; set; }
        public decimal? RtoZk { get; set; }
        public string Cellphone { get; set; }
        public decimal? AmtnSp1 { get; set; }
        public decimal? AmtnSp2 { get; set; }
        public decimal? AmtnSp3 { get; set; }
        public decimal? AmtnSp4 { get; set; }
        public decimal? AmtnSp5 { get; set; }
        public decimal? AmtnBz { get; set; }
        public decimal? AmtnDj { get; set; }
    }
}