// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Ceshi
 : Entity<int>    {
        public string SebNo { get; set; }
        public string Name { get; set; }
        public string CallSta1 { get; set; }
        public DateTime? Dt { get; set; }
        public string RsDesp { get; set; }
    }
}