// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CmmMeasureRec
 : Entity<int>    {
        public CmmMeasureRec()
        {
            CmmMeasureRecItem = new HashSet<CmmMeasureRecItem>();
        }

        
        public string PartName { get; set; }
        public string Revisionnumber { get; set; }
        public string Serialnumber { get; set; }
        public DateTime? Ddate { get; set; }
        public string Dtime { get; set; }
        public string PrdNo { get; set; }
        public string ZcNo { get; set; }
        public string SebNo { get; set; }
        public string BanNo { get; set; }
        public DateTime? RecDd { get; set; }
        public string TzNo { get; set; }
        public DateTime? Sysdate { get; set; }
        public string ChkType { get; set; }

        public virtual ICollection<CmmMeasureRecItem> CmmMeasureRecItem { get; set; }
    }
}