// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CnttSgt
 : Entity<int>    {
        
        public string CtNo { get; set; }
        public DateTime? CtDd { get; set; }
        public string State { get; set; }
        public string IpCnttNo { get; set; }
        public string OpCnttNo { get; set; }
        public string PreManualNo { get; set; }
        public string ManualNo { get; set; }
        public string CusNoTrade { get; set; }
        public string CusNoWork { get; set; }
        public string TradeType { get; set; }
        public string PrjNo { get; set; }
        public string CusNoFrgn { get; set; }
        public string SuppmtrCnttNo { get; set; }
        public decimal? CstWork { get; set; }
        public string IpMprdNo { get; set; }
        public string OpMprdNo { get; set; }
        public decimal? AmtIpMtr { get; set; }
        public decimal? AmtOpPrd { get; set; }
        public string CustId1 { get; set; }
        public string CustId2 { get; set; }
        public string CustId3 { get; set; }
        public string CustId4 { get; set; }
        public DateTime? AppDd { get; set; }
        public string AccareaId { get; set; }
        public string SalNo { get; set; }
        public string TradeId { get; set; }
        public string TaxId { get; set; }
        public string CutNo { get; set; }
        public string TransId { get; set; }
        public decimal? RtoTax { get; set; }
        public string FeSc { get; set; }
        public string VstType { get; set; }
        public string InvType { get; set; }
        public decimal? RtoIsal { get; set; }
        public string TaxType { get; set; }
        public string Offer { get; set; }
        public string AgreeNo { get; set; }
        public string PassNo { get; set; }
        public int? CnttQty { get; set; }
        public string CurIdIp { get; set; }
        public string CurIdOp { get; set; }
        public decimal? AmtMng { get; set; }
        public decimal? RtoMng { get; set; }
        public string WorkType { get; set; }
        public DateTime? IpDd { get; set; }
        public DateTime? OpDd { get; set; }
        public string StrArea { get; set; }
        public string ImFlg { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ChkDd { get; set; }
        public string ChgFlag { get; set; }
        public string Memo { get; set; }
    }
}