// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Combitable
 : Entity<int>    {
        public string Combitype { get; set; }
        public string Itemtype { get; set; }
        public string Fixchar { get; set; }
        public int? Itemlen { get; set; }
        public string Format { get; set; }
        public string Align { get; set; }
        public string Covercar { get; set; }
        public int? Rowindex { get; set; }
    }
}