// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CurId
 : Entity<int>    {
        
        public string CurId1 { get; set; }
        public DateTime IjDd { get; set; }
        public string CurName { get; set; }
        public decimal? ExcRto { get; set; }
        public string AccNoIr { get; set; }
        public string AccNoIp { get; set; }
        public string AccNoChk { get; set; }
        public decimal? ExcRtoE { get; set; }
        public decimal? ExcRtoI { get; set; }
        public decimal? ExcRtoO { get; set; }
        public string IdSgt { get; set; }
        public byte[] UpDd { get; set; }
        public string Dep { get; set; }
        public string DeproNo { get; set; }
    }
}