// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CusBox
 : Entity<int>    {
        
        public string Boxcode { get; set; }
        public string Productcode { get; set; }
        public string Number { get; set; }
        public DateTime? ProTime { get; set; }
        public string Tablename { get; set; }
    }
}