// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Cust
 : Entity<int>    {
        
        public string CusNo { get; set; }
        public string CusAre { get; set; }
        public string MasCus { get; set; }
        public string ObjId { get; set; }
        public string Name { get; set; }
        public string Snm { get; set; }
        public string ClsMth { get; set; }
        public short? ClsDd { get; set; }
        public short? MmEnd { get; set; }
        public short? ChkDd { get; set; }
        public string UniNo { get; set; }
        public string BosNm { get; set; }
        public string CntMan1 { get; set; }
        public string CntMan2 { get; set; }
        public string AccMan { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string Zip { get; set; }
        public string InvId { get; set; }
        public string Id1Tax { get; set; }
        public string Cls1 { get; set; }
        public DateTime? StrDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string Cur { get; set; }
        public string CrdNrNc { get; set; }
        public string EMail { get; set; }
        public string SendMth { get; set; }
        public string SendWh { get; set; }
        public string IdCode { get; set; }
        public string Compnet { get; set; }
        public DateTime? CompDd { get; set; }
        public decimal? Capsum { get; set; }
        public decimal? Busisum { get; set; }
        public int? Salms { get; set; }
        public string Businote { get; set; }
        public string Notify { get; set; }
        public string Broker { get; set; }
        public string LoadingPort { get; set; }
        public string DisPort { get; set; }
        public string ManuPlace { get; set; }
        public string BizDsc { get; set; }
        public string Country { get; set; }
        public string FpName { get; set; }
        public bool? ChkFax { get; set; }
        public decimal? RtoTax { get; set; }
        public string ChkCusIdx { get; set; }
        public bool? CyId { get; set; }
        public string RegistCode { get; set; }
        public string CorpId { get; set; }
        public string MCust { get; set; }
        public string SalNo { get; set; }
        public string ChkDep { get; set; }
        public decimal? RtoKk { get; set; }
        public string Dep { get; set; }
        public decimal? RtoFl { get; set; }
        public decimal? RtoYl { get; set; }
        public string Dep1 { get; set; }
        public short? PayDays { get; set; }
        public string PayFlag { get; set; }
        public decimal? AmtnMaxPay { get; set; }
        public string ChkQk { get; set; }
        public decimal? AmtnQk { get; set; }
        public decimal? RtoDiscnt { get; set; }
        public bool? ChkIrp2 { get; set; }
        public string Logon { get; set; }
        public string WhNo { get; set; }
        public string StopOrder { get; set; }
        public string RtnCtrl { get; set; }
        public string DrpId { get; set; }
        public string YhWh1 { get; set; }
        public string YhWh2 { get; set; }
        public string AccNoIr { get; set; }
        public string AccNoIp { get; set; }
        public short? PrtweeksPo { get; set; }
        public short? SoweeksPo { get; set; }
        public string ChkDrp1 { get; set; }
        public string ChkDrp2 { get; set; }
        public string ChkDrp3 { get; set; }
        public string XnNo { get; set; }
        public string ChkBarcode { get; set; }
        public string AccNoZp { get; set; }
        public string HmId { get; set; }
        public decimal? AmtnFl { get; set; }
        public decimal? AmtnFled { get; set; }
        public string ChkSbrto { get; set; }
        public decimal? RtoFqsk { get; set; }
        public string DateflagFqsk { get; set; }
        public DateTime? DateFqsk { get; set; }
        public int? QsFqsk { get; set; }
        public string CodeName { get; set; }
        public string NsrCode { get; set; }
        public string NamePy { get; set; }
        public string BizDsc1 { get; set; }
        public string ExTrdId { get; set; }
        public string ImTrdId { get; set; }
        public string FpType { get; set; }
        public string ChkMinXf { get; set; }
        public string BilMinXf { get; set; }
        public decimal? AmtnMinXf { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public string Usr { get; set; }
        public string Adr1 { get; set; }
        public string Adr2 { get; set; }
        public string Rem { get; set; }
        public string NmEng { get; set; }
        public string MainPrd { get; set; }
        public string AdrEng { get; set; }
        public bool? IsEffective { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public bool? Isdelete { get; set; }
        public bool? IsCustomerDeposit { get; set; }
        public decimal? SmallPackageQty { get; set; }
        public string SaleType { get; set; }
    }
}