// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class CusWh
 : Entity<int>    {
        
        public string CusNo { get; set; }
        public string Wh { get; set; }
        public string Name { get; set; }
        public string CntMan { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string Adr { get; set; }
        public string SendcusName { get; set; }
        public string ConMan { get; set; }
        public string CellNo { get; set; }
        public string Zip { get; set; }
        public byte[] UpDd { get; set; }
        public int? CounId { get; set; }
        public string EMail { get; set; }
        public string Rem { get; set; }
        public string ChkDft { get; set; }
    }
}