// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Database
 : Entity<int>    {
        
        public string Name { get; set; }
        public string Usr { get; set; }
        public string PoolName { get; set; }
        public int? RegionNum { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string GsmPassword { get; set; }
        public string ConnectString { get; set; }
        public DateTime UpdDate { get; set; }
        public int DatabaseNum { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Status { get; set; }
        public string ScanAddress { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public int? OnsPort { get; set; }
        public DateTime ChkDate { get; set; }
        public int NumAssignedInstances { get; set; }
        public int? SrlatThresh { get; set; }
        public string ChkMob { get; set; }
        public int? CpuThresh { get; set; }
        public bool IsPrint { get; set; }
        public string Version { get; set; }
        public string DbType { get; set; }
        public byte[] EncryptedGsmPassword { get; set; }
    }
}