// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Dcrresult
 : Entity<int>    {
        public string SebNo { get; set; }
        public string ParaNo { get; set; }
        public byte? Type { get; set; }
        public string Maxvalue { get; set; }
        public string Minvalue { get; set; }
    }
}