// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Dept
 : Entity<int>    {
        
        public string Dname { get; set; }
        public int? Pid { get; set; }
        public string Loc { get; set; }
        public string Dep { get; set; }
        public string Name { get; set; }
        public string EngName { get; set; }
        public string Up { get; set; }
        public DateTime? StopDd { get; set; }
        public decimal? Daytime { get; set; }
        public string MakeId { get; set; }
        public bool? GroupId { get; set; }
        public string Usr { get; set; }
        public string NamePy { get; set; }
        public string DepGstd { get; set; }
        public string CusNos { get; set; }
        public string CusNo { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public string MaterialWarehouse { get; set; }
        public string TargetWarehouse { get; set; }
    }
}