// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class EqpMaintainPlan
 : Entity<int>    {
        public decimal? ActQtyCycle { get; set; }
        public DateTime BillDate { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string BusiNo { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public string ChkMob { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public byte[] CycelInfo { get; set; }
        public string Dep { get; set; }
        
        public bool? IsAllRelease { get; set; }
        public bool? IsClose { get; set; }
        public bool? IsPrint { get; set; }
        public string JhSpec { get; set; }
        public string JhStatus { get; set; }
        public DateTime? LastReleaseTime { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public int? QtyCycle { get; set; }
        public string Rem { get; set; }
        public string SalNo { get; set; }
        public string SebCycleUnit { get; set; }
        public string SebNo { get; set; }
        public decimal? Standard { get; set; }
        public string StationNo { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
    }
}