// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class EqpMaintainSpec
 : Entity<int>    {
        public EqpMaintainSpec()
        {
            EqpMtspecInfo = new HashSet<EqpMtspecInfo>();
            EqpSparePart = new HashSet<EqpSparePart>();
        }

        public DateTime BillDate { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string BusiNo { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public string ChkMob { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string Dep { get; set; }
        public bool Enabled { get; set; }
        public string Guide { get; set; }
        
        public bool? IsClose { get; set; }
        public bool? IsPrint { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string PostNo { get; set; }
        public int? QtyCycle { get; set; }
        public string Rem { get; set; }
        public string SebCycleUnit { get; set; }
        public string SebName { get; set; }
        public string SebNo { get; set; }
        public decimal? Standard { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string Version { get; set; }

        public virtual ICollection<EqpMtspecInfo> EqpMtspecInfo { get; set; }
        public virtual ICollection<EqpSparePart> EqpSparePart { get; set; }
    }
}