// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class EqpPartChangeRecord
 : Entity<int>    {
        
        public int? Itm { get; set; }
        public int Mid { get; set; }
        public string PartName { get; set; }
        public string PartNo { get; set; }
        public decimal Qty { get; set; }
        public string Rem { get; set; }
        public string SalNo { get; set; }
        public DateTime? Sysdate { get; set; }
    }
}