// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class EqpRunStatus
 : Entity<int>    {
        public EqpRunStatus()
        {
            EqpRunRecord = new HashSet<EqpRunRecord>();
        }

        public string DevNo { get; set; }
        
        public DateTime StartTime { get; set; }
        public string StatusNo { get; set; }
        public string StatusProp { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }

        public virtual ICollection<EqpRunRecord> EqpRunRecord { get; set; }
    }
}