// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class ExImpTemp
 : Entity<int>    {
        
        public string TpType { get; set; }
        public string TpName { get; set; }
        public string BusiNo { get; set; }
        public string SheetName { get; set; }
        public int? SheetIndex { get; set; }
        public int StartRow { get; set; }
        public int? RowsCount { get; set; }
        public string TableName { get; set; }
        public Guid ColMap { get; set; }
        public Guid MapData { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime? UpdDate { get; set; }
    }
}