// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Fieldstable
 : Entity<int>    {
        public string Name { get; set; }
        public int? Rown { get; set; }
        public string Datatype { get; set; }
        public string Vvalue { get; set; }
    }
}