// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class HfplRecs
 : Entity<int>    {
        
        public int Mid { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string BatNo { get; set; }
        public decimal Qty { get; set; }
    }
}