// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Indx
 : Entity<int>    {
        
        public string IdxNo { get; set; }
        public string Name { get; set; }
        public string IdxUp { get; set; }
        public DateTime? StopDd { get; set; }
        public string Rem { get; set; }
        public decimal? UpStd { get; set; }
        public byte[] UpDd { get; set; }
        public string WebTitle { get; set; }
        public string WebDescription { get; set; }
        public string WebKeywords { get; set; }
        public string DaySupply { get; set; }
        public string ChkYh { get; set; }
        public decimal? LosRto { get; set; }
        public string ChkPos { get; set; }
        public string IdxType { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}