// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class InspectItemsList
 : Entity<int>    {
        
        public string PrdNo { get; set; }
        public string WsSpc { get; set; }
        public string WsFe { get; set; }
        public string WsInspectHz { get; set; }
        public string WsCollectMethod { get; set; }
        public string QcSpc { get; set; }
        public string QcFe { get; set; }
        public string QcInspectHz { get; set; }
        public string QcCollectMethod { get; set; }
        public string ZcNo { get; set; }
        public string SebNo { get; set; }
        public string ModNo { get; set; }
        public int? Vorder { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public decimal? MinDesign { get; set; }
        public decimal? MaxDesign { get; set; }
        public decimal? MinTech { get; set; }
        public decimal? MaxTech { get; set; }
        public string StandardTech { get; set; }
        public string InspectType { get; set; }
        public DateTime CreateTime { get; set; }
        public string Usr { get; set; }
        public string Usrname { get; set; }
        public DateTime? ShDate { get; set; }
        public string Chkman { get; set; }
        public string Status { get; set; }
        public DateTime? Upddate { get; set; }
        public string ShRem { get; set; }
        public string MonthCondition { get; set; }
        public string Busino { get; set; }
    }
}