// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class JhtpTemp
 : Entity<int>    {
        public string Pid { get; set; }
        public string Id { get; set; }
    }
}