// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class LblSupqc
 : Entity<int>    {
        
        public string No { get; set; }
        public string Busino { get; set; }
        public string PrdNo { get; set; }
        public string MtBarcode { get; set; }
        public string SupNo { get; set; }
        public string Attachment { get; set; }
        public DateTime Sysdate { get; set; }
        public string DelNo { get; set; }
    }
}