// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class LeLogisticsTasksHistory
 : Entity<int>    {
        
        public string No { get; set; }
        public string Status { get; set; }
        public int? ItemId { get; set; }
        public decimal? PlanQuantity { get; set; }
        public decimal? FinishedQuantity { get; set; }
        public decimal? Quantity { get; set; }
        public string ItemStatus { get; set; }
        public string OperateType { get; set; }
        public DateTime SysDate { get; set; }
        public string OperateUser { get; set; }
    }
}