// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class LeLogisticsTasks
 : Entity<int>    {
        
        public string No { get; set; }
        public string SourceNo { get; set; }
        public string StartingPoint { get; set; }
        public string EndPoint { get; set; }
        public string Status { get; set; }
        public DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public DateTime? DistributionDate { get; set; }
        public string CarrierUser { get; set; }
        public DateTime? FinishDate { get; set; }
        public string FinishUser { get; set; }
        public string ShippingCategory { get; set; }
        public string VehicleRequirements { get; set; }
        public DateTime? DeadlineDate { get; set; }
        public string WoNo { get; set; }
        public int? ProductionOrder { get; set; }
        public string Remark { get; set; }
    }
}