// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class LeTestItems
 : Entity<int>    {
        
        public int? Item { get; set; }
        public int? Mid { get; set; }
        public string ProdNo { get; set; }

        public virtual LeTestMain MidNavigation { get; set; }
    }
}