// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class LsbYzjMap
 : Entity<int>    {
        
        public string LsbNo { get; set; }
        public string YzjNo { get; set; }
        public DateTime Sysdate { get; set; }
        public DateTime Outtime { get; set; }
        public string TzNo { get; set; }
        public int? RlId { get; set; }
        public string RlTz { get; set; }
        public decimal? ZyCapacity { get; set; }
        public string SebNo { get; set; }
        public string BanNo { get; set; }
        public string ZcNo { get; set; }
        public string Unit { get; set; }
        public decimal? Temperature { get; set; }
    }
}