// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MdmCycleTime
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string TypeNo { get; set; }
        public string No { get; set; }
        public decimal? CycleTime { get; set; }
        public decimal? QtySingle { get; set; }
        public string Unit { get; set; }

        public virtual TfZc MidNavigation { get; set; }
    }
}