// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    /// <summary>
    /// 工厂布局
    /// </summary>
    public partial class MdmLayout
 : Entity<int>    {
        
        public string No { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Up { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string Usr { get; set; }
        public DateTime? SysDate { get; set; }
        public string UpdUsr { get; set; }
        public DateTime? UpdDate { get; set; }
        public bool? Isdelete { get; set; }
        public string MaterialWarehouse { get; set; }
        public string TargetWarehouse { get; set; }
    }
}