// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MdmMaterial
 : Entity<int>    {
        
        public string Code { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Spec { get; set; }
        public string FigureNo { get; set; }
        public string MeasuringUnit { get; set; }
        public string WeightUnit { get; set; }
        public string Describe { get; set; }
        public string WareHouseCode { get; set; }
        public decimal? MaxLimitQty { get; set; }
        public decimal? MinLimitQty { get; set; }
        public decimal? Multiple { get; set; }
        public string IsBom { get; set; }
        public string ProductionDepartment { get; set; }
        public string IsEffective { get; set; }
        public string EffectiveDate { get; set; }
        public string ExpirationDate { get; set; }
        public string IsDelete { get; set; }
        public DateTime? UpdateTime { get; set; }
        public string WareHouseName { get; set; }
        public string ProductionDepartmentName { get; set; }
    }
}