// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MdmPqip
 : Entity<int>    {
        public int? Frequency { get; set; }
        public string FrequencyType { get; set; }
        
        public string InspectionInstructor { get; set; }
        public int? InspectionMode { get; set; }
        public string InspectionType { get; set; }
        public int? InspectUnit { get; set; }
        public bool? IsPrint { get; set; }
        public string MaterialType { get; set; }
        public string ProcessNo { get; set; }
        public string ProductionNo { get; set; }
        public string SolutionFeature { get; set; }
        public string SolutionName { get; set; }
        public string SolutionNo { get; set; }
        public string SolutionType { get; set; }
        public string SuppCode { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public decimal? Aql { get; set; }
        public string Comment { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public int? RecordQty { get; set; }
        public int? SampleQty { get; set; }
        public int? SampleRule { get; set; }
        public int? InspectionSchemeId { get; set; }
        public string Version { get; set; }
        public bool? Efi { get; set; }
    }
}