// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MdmSpotCheckSchedule
 : Entity<int>    {
        
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string MaterialType { get; set; }
        public int? StartQty { get; set; }
        public int? TerminationQty { get; set; }
        public int? StricterQty { get; set; }
        public int? NormalQty { get; set; }
        public int? BroadenQty { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
    }
}