// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MdSpInfo
 : Entity<int>    {
        
        public string SpecNo { get; set; }
        public int Itm { get; set; }
        public string PartNo { get; set; }
        public string ChkContent { get; set; }
        public string Standard { get; set; }
        public string Method { get; set; }
        public string Opportunity { get; set; }
        public string Optype { get; set; }
        public string Result { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
    }
}