// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MesDncIntfcT
 : Entity<int>    {
        
        public string Interface { get; set; }
        public string Paras { get; set; }
        public DateTime Timestamp { get; set; }
        public string Name { get; set; }
    }
}