// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MesJobInfos
 : Entity<int>    {
        
        public string Jobtype { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Assemblyname { get; set; }
        public string Classname { get; set; }
        public string Jobargs { get; set; }
        public string Cronexpression { get; set; }
        public string Cronexpdesp { get; set; }
        public DateTime? Lastruntime { get; set; }
        public DateTime? Nextruntime { get; set; }
        public int? Runcount { get; set; }
        public int? State { get; set; }
        public int? Displayorder { get; set; }
        public string Usr { get; set; }
        public string Usrname { get; set; }
        public DateTime? Sysdate { get; set; }
        public string Updusr { get; set; }
        public string Updusrname { get; set; }
        public DateTime? Upddate { get; set; }
        public bool? DebugRun { get; set; }
        public string RunType { get; set; }
        public int? TcpListenPort { get; set; }
    }
}