// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfBan
 : Entity<int>    {
        public MfBan()
        {
            TfBan = new HashSet<TfBan>();
        }

        
        public string BanNo { get; set; }
        public string Name { get; set; }
        public bool? BanId { get; set; }
        public string Rem { get; set; }
        public short? TimeOut { get; set; }
        public string BegId { get; set; }
        public string BegTime { get; set; }
        public string EndId { get; set; }
        public string EndTime { get; set; }
        public bool? ActId { get; set; }
        public short? ActMin { get; set; }
        public short? ActRange { get; set; }
        public short? ActFx { get; set; }
        public int? HalfItm { get; set; }
        public bool? StopId { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public short? TotalTime { get; set; }
        public string BatchBegTime { get; set; }
        public string BatchEndTime { get; set; }

        public virtual ICollection<TfBan> TfBan { get; set; }
    }
}