// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfBom
 : Entity<int>    {
        public MfBom()
        {
            TfBom = new HashSet<TfBom>();
        }

        
        public string BomNo { get; set; }
        public string Name { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public string PfNo { get; set; }
        public string WhNo { get; set; }
        public string PrdKnd { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? CstMake { get; set; }
        public decimal? CstPrd { get; set; }
        public decimal? CstMan { get; set; }
        public decimal? CstOut { get; set; }
        public decimal? UsedTime { get; set; }
        public decimal? Cst { get; set; }
        public string UsrNo { get; set; }
        public string Dep { get; set; }
        public DateTime? ValidDd { get; set; }
        public DateTime? EndDd { get; set; }
        public DateTime? ClsDate { get; set; }
        public string SebNo { get; set; }
        public string ModNo { get; set; }
        public decimal? TimeCnt { get; set; }
        public string DepInc { get; set; }
        public string Spc { get; set; }
        public decimal? CstMl { get; set; }
        public string IdxNo { get; set; }
        public string Rem { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public bool? IsEffective { get; set; }
        public bool? Isdelete { get; set; }
        public string SrcNo { get; set; }
        public string SrcType { get; set; }
        public string CustNo { get; set; }

        public virtual ICollection<TfBom> TfBom { get; set; }
    }
}