// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfIj
 : Entity<int>    {
        public MfIj()
        {
            TfIj = new HashSet<TfIj>();
        }

        
        public string IjId { get; set; }
        public string IjNo { get; set; }
        public DateTime? IjDd { get; set; }
        public string IjReason { get; set; }
        public string FixCst { get; set; }
        public string AccNoD { get; set; }
        public string AccNoC { get; set; }
        public string Dep { get; set; }
        public string VohId { get; set; }
        public string VohNo { get; set; }
        public string RefNo { get; set; }
        public string BatNo { get; set; }
        public string ManNo { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public string PrtSw { get; set; }
        public string CpySw { get; set; }
        public string BilNo { get; set; }
        public string BilId { get; set; }
        public DateTime? ClsDate { get; set; }
        public string PosNo { get; set; }
        public decimal? Ijid1 { get; set; }
        public string CasNo { get; set; }
        public string BilType { get; set; }
        public string CnttNo { get; set; }
        public string AccNoSs { get; set; }
        public string AccNoSy { get; set; }
        public string MobId { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public short? FjNum { get; set; }
        public DateTime? SysDate { get; set; }
        public string PosId { get; set; }
        public string CusNo { get; set; }
        public int? TaskId { get; set; }
        public string PrtUsr { get; set; }
        public string SqId { get; set; }
        public string SqNo { get; set; }
        public int? SqItm { get; set; }
        public string Issvs { get; set; }
        public string FromcbCalc { get; set; }
        public string JhSoNo { get; set; }
        public string Tzzg { get; set; }
        public string YgNo { get; set; }
        public string CancelId { get; set; }
        public string CurIdIfrs { get; set; }
        public decimal? ExcRtoIfrs { get; set; }
        public DateTime? PrtDate { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string ScanId { get; set; }
        public string ScanUsr { get; set; }
        public DateTime? ScanDate { get; set; }
        public string ScanUsr1 { get; set; }
        public DateTime? ScanDate1 { get; set; }
        public string GroupKey { get; set; }
        public string BusiNo { get; set; }
        public string BilType1 { get; set; }
        public string BilTypeName { get; set; }
        public string Usr1 { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate1 { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan1 { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfIj> TfIj { get; set; }
    }
}