// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfJxzbSz
 : Entity<int>    {
        public MfJxzbSz()
        {
            TfJxzbSz = new HashSet<TfJxzbSz>();
        }

        
        public string JxszName { get; set; }
        public string Version { get; set; }
        public DateTime? StaDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string Dep { get; set; }
        public string Authdep { get; set; }
        public DateTime? Releasetime { get; set; }
        public string State { get; set; }
        public string No { get; set; }
        public DateTime? Billdate { get; set; }
        public string Rem { get; set; }
        public string Busino { get; set; }
        public string Biltype { get; set; }
        public string Biltypename { get; set; }
        public string Usr { get; set; }
        public string Usrname { get; set; }
        public DateTime? Upddate { get; set; }
        public string Updusrname { get; set; }
        public string Updusr { get; set; }
        public string Chkman { get; set; }
        public string Chkmanname { get; set; }
        public DateTime? Chkdate { get; set; }
        public bool? Isclose { get; set; }
        public DateTime? Clsdate { get; set; }
        public string Clsusr { get; set; }
        public string Clsusrname { get; set; }
        public string Chkmob { get; set; }
        public bool? Isprint { get; set; }
        public DateTime? Sysdate { get; set; }

        public virtual ICollection<TfJxzbSz> TfJxzbSz { get; set; }
    }
}