// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfMo
 : Entity<int>    {
        public MfMo()
        {
            TfMo = new HashSet<TfMo>();
        }

        
        public string MoNo { get; set; }
        public DateTime? MoDd { get; set; }
        public DateTime? StaDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string MrpNo { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string SoNo { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public DateTime? NeedDd { get; set; }
        public string Dep { get; set; }
        public string CusNo { get; set; }
        public string BatNo { get; set; }
        public string PrdNoMt { get; set; }
        public int? MtItm { get; set; }
        public string MoNoAdd { get; set; }
        public decimal? QtyFin { get; set; }
        public decimal? QtyMl { get; set; }
        public decimal? CstMake { get; set; }
        public decimal? CstPrd { get; set; }
        public decimal? CstOut { get; set; }
        public decimal? CstMan { get; set; }
        public decimal? UsedTime { get; set; }
        public decimal? Cst { get; set; }
        public DateTime? OpnDd { get; set; }
        public DateTime? FinDd { get; set; }
        public int? EstItm { get; set; }
        public string MlOk { get; set; }
        public string MdNo { get; set; }
        public decimal? QtyRk { get; set; }
        public decimal? QtyRkUnsh { get; set; }
        public string IdNo { get; set; }
        public decimal? QtyChk { get; set; }
        public bool? Control { get; set; }
        public string MoState { get; set; }
        public bool? MmCurml { get; set; }
        public string CnttNo { get; set; }
        public string SebNo { get; set; }
        public string GrpNo { get; set; }
        public string SupPrdNo { get; set; }
        public decimal? TimeCnt { get; set; }
        public bool? CfId { get; set; }
        public string CusOsNo { get; set; }
        public decimal? QtyQl { get; set; }
        public decimal? QtyQlUnsh { get; set; }
        public bool? QlId { get; set; }
        public bool? Q2Id { get; set; }
        public bool? Q3Id { get; set; }
        public DateTime? ZtDd { get; set; }
        public string SupPrdMark { get; set; }
        public decimal? QtyQs { get; set; }
        public decimal? QtyQsUnsh { get; set; }
        public decimal? QtyLost { get; set; }
        public bool? ZtId { get; set; }
        public string BilDspId { get; set; }
        public string Rem { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfMo> TfMo { get; set; }
    }
}