// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfQl
 : Entity<int>    {
        public MfQl()
        {
            TfQl = new HashSet<TfQl>();
        }

        
        public string QlId { get; set; }
        public string QlNo { get; set; }
        public DateTime? QlDd { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string QlType { get; set; }
        public string BatNo { get; set; }
        public string MoNo { get; set; }
        public string MrpNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Unit { get; set; }
        public string WhMtl { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? QtyRtn { get; set; }
        public decimal? Qty1Rtn { get; set; }
        public decimal? QtyRtnUnsh { get; set; }
        public decimal? Qty1RtnUnsh { get; set; }
        public string UsrNo { get; set; }
        public string Dep { get; set; }
        public string Rem { get; set; }
        public string CusNo { get; set; }
        public string CpySw { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public string PrtSw { get; set; }
        public DateTime? ClsDate { get; set; }
        public string IdNo { get; set; }
        public string BilType { get; set; }
        public string CnttNo { get; set; }
        public string MobId { get; set; }
        public DateTime? LockDate { get; set; }
        public string LockMan { get; set; }
        public short? FjNum { get; set; }
        public DateTime? SysDate { get; set; }
        public string CasNo { get; set; }
        public int? TaskId { get; set; }
        public string CusOsNo { get; set; }
        public string PrtUsr { get; set; }
        public string LqNo { get; set; }
        public string TzNo { get; set; }
        public string SoNo { get; set; }
        public string SoId { get; set; }
        public bool? CloseId { get; set; }
        public string CurId { get; set; }
        public decimal? AmtnPc { get; set; }
        public decimal? AmtnYz { get; set; }
        public int? PrtNum { get; set; }
        public string CancelId { get; set; }
        public string PoOk { get; set; }
        public string YlId { get; set; }
        public DateTime? PrtDate { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string ClsId { get; set; }
        public string BusiNo { get; set; }
        public string BilType1 { get; set; }
        public string BilTypeName { get; set; }
        public string Usr1 { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate1 { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan1 { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string Rem1 { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfQl> TfQl { get; set; }
    }
}