// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfSbaa
 : Entity<int>    {
        public MfSbaa()
        {
            TfSbaa = new HashSet<TfSbaa>();
        }

        
        public string AaNo { get; set; }
        public DateTime? AaDd { get; set; }
        public string CkId { get; set; }
        public string Dep { get; set; }
        public string SalNo { get; set; }
        public string VohId { get; set; }
        public string VohNo { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string CpySw { get; set; }
        public string PrtSw { get; set; }
        public string PrtUsr { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public DateTime? PrtDate { get; set; }
        public string ModId { get; set; }
        public string WxId { get; set; }
        public string WxNo { get; set; }
        public string Rem { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfSbaa> TfSbaa { get; set; }
    }
}