// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfSq
 : Entity<int>    {
        public MfSq()
        {
            TfSq = new HashSet<TfSq>();
        }

        
        public string SqNo { get; set; }
        public DateTime? SqDd { get; set; }
        public string Dep { get; set; }
        public string CusNo { get; set; }
        public string SalNo { get; set; }
        public string PoNo { get; set; }
        public string IncId { get; set; }
        public string Rem { get; set; }
        public DateTime? EstDd { get; set; }
        public string BilId { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public string PrtSw { get; set; }
        public string CpySw { get; set; }
        public string BatNo { get; set; }
        public string BilNo { get; set; }
        public DateTime? ClsDate { get; set; }
        public string PoDep { get; set; }
        public string ClsId { get; set; }
        public string BackId { get; set; }
        public string BilType { get; set; }
        public string CurId { get; set; }
        public decimal? ExcRto { get; set; }
        public string SoNo { get; set; }
        public string MobId { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public DateTime? SysDate { get; set; }
        public string CasNo { get; set; }
        public int? TaskId { get; set; }
        public string SoId { get; set; }
        public string PrtUsr { get; set; }
        public string CnttNo { get; set; }
        public string CancelId { get; set; }
        public DateTime? PrtDate { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string BusiNo { get; set; }
        public string BilType1 { get; set; }
        public string BilTypeName { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate1 { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan1 { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfSq> TfSq { get; set; }
    }
}