// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfTb
 : Entity<int>    {
        public MfTb()
        {
            TfTb = new HashSet<TfTb>();
        }

        
        public string TbNo { get; set; }
        public DateTime? TbDd { get; set; }
        public DateTime? PayDd { get; set; }
        public DateTime? ChkDd { get; set; }
        public string TradMth { get; set; }
        public string BatNo { get; set; }
        public string CusNo { get; set; }
        public string VohId { get; set; }
        public string VohNo { get; set; }
        public string Dep { get; set; }
        public string InvNo { get; set; }
        public string TaxId { get; set; }
        public string TwNo { get; set; }
        public string SendMth { get; set; }
        public string SendWh { get; set; }
        public string RpNo { get; set; }
        public string ZhangId { get; set; }
        public string CurId { get; set; }
        public decimal? ExcRto { get; set; }
        public string SalNo { get; set; }
        public string ArpNo { get; set; }
        public decimal? AmtnIrp { get; set; }
        public decimal? AmtIrp { get; set; }
        public decimal? TaxIrp { get; set; }
        public string PayMth { get; set; }
        public short? PayDays { get; set; }
        public short? ChkDays { get; set; }
        public short? IntDays { get; set; }
        public string PayRem { get; set; }
        public string CloseId { get; set; }
        public string Rem { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string CpySw { get; set; }
        public string ClsRem { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public string PrtSw { get; set; }
        public DateTime? ClsDate { get; set; }
        public string MmvohId { get; set; }
        public string EpNo { get; set; }
        public decimal? AmtnEp { get; set; }
        public decimal? RtoTax { get; set; }
        public string BilType { get; set; }
        public string KpId { get; set; }
        public string LzClsId { get; set; }
        public string MobId { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public short? FjNum { get; set; }
        public DateTime? SysDate { get; set; }
        public decimal? AmtCls { get; set; }
        public decimal? AmtnNetCls { get; set; }
        public decimal? TaxCls { get; set; }
        public string CasNo { get; set; }
        public int? TaskId { get; set; }
        public string TurnId { get; set; }
        public string TwId { get; set; }
        public string CusOsNo { get; set; }
        public string PrtUsr { get; set; }
        public decimal? QtyCls { get; set; }
        public string CancelId { get; set; }
        public decimal? RtoFqsk { get; set; }
        public string DateflagFqsk { get; set; }
        public DateTime? DateFqsk { get; set; }
        public int? QsFqsk { get; set; }
        public string CurIdIfrs { get; set; }
        public decimal? ExcRtoIfrs { get; set; }
        public decimal? AmtnEpIfrs { get; set; }
        public DateTime? PrtDate { get; set; }
        public decimal? Qty1Cls { get; set; }
        public string InvBilId { get; set; }
        public string InvBilNo { get; set; }
        public DateTime? LzClsDd { get; set; }
        public string BilComp { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string ScanId { get; set; }
        public string ScanUsr { get; set; }
        public DateTime? ScanDate { get; set; }
        public string DzUsr { get; set; }
        public DateTime? DzDate { get; set; }

        public virtual ICollection<TfTb> TfTb { get; set; }
    }
}