// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfVhid
 : Entity<int>    {
        public string BilId { get; set; }
        public string VohId { get; set; }
        public string Name { get; set; }
        public string RemId { get; set; }
        public string Dep { get; set; }
        public byte[] UpDd { get; set; }
        public string Redflag { get; set; }
        public string A { get; set; }
    }
}