// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfWjS
 : Entity<int>    {
        public MfWjS()
        {
            TfWjS = new HashSet<TfWjS>();
        }

        
        public string WxjId { get; set; }
        public string WxjNo { get; set; }
        public DateTime? WxjDd { get; set; }
        public string SalNo { get; set; }
        public string DepRep { get; set; }
        public string CusNo { get; set; }
        public string Dep { get; set; }
        public DateTime? BDdRep { get; set; }
        public DateTime? EDdRep { get; set; }
        public string RepNo { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public string Rem { get; set; }
        public string SebNo { get; set; }
        public string SalRep { get; set; }
        public decimal? TimeRep { get; set; }
        public string Status { get; set; }
        public string WsSbSal { get; set; }
        public string SalRepLeader { get; set; }
        public string SebEngineer { get; set; }

        public virtual ICollection<TfWjS> TfWjS { get; set; }
    }
}