// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfWxM
 : Entity<int>    {
        public MfWxM()
        {
            TfWxM = new HashSet<TfWxM>();
        }

        
        public string WxId { get; set; }
        public string WxNo { get; set; }
        public DateTime? WxDd { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string SalNo { get; set; }
        public string DepRep { get; set; }
        public string CusNo { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ClsDate { get; set; }
        public DateTime? SysDate { get; set; }
        public string MobId { get; set; }
        public string PrtSw { get; set; }
        public string CpySw { get; set; }
        public string BilType { get; set; }
        public string Dep { get; set; }
        public string Rem { get; set; }
        public string CloseId { get; set; }
        public string CurId { get; set; }
        public decimal? ExcRto { get; set; }
        public decimal? Amtn { get; set; }
        public decimal? Amt { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public string PrtUsr { get; set; }
        public string CancelId { get; set; }
        public DateTime? PrtDate { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string BusiNo { get; set; }
        public string BilType1 { get; set; }
        public string BilTypeName { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate1 { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan1 { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public DateTime? WxBeDate { get; set; }
        public DateTime? WxEnDate { get; set; }

        public virtual ICollection<TfWxM> TfWxM { get; set; }
    }
}