// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfZc
 : Entity<int>    {
        public MfZc()
        {
            TfZc = new HashSet<TfZc>();
        }

        
        public string BomNo { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public string Spc { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public string Rem { get; set; }
        public decimal? QtyBat { get; set; }
        public string PfNo { get; set; }
        public string Name { get; set; }
        public string Dep { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public DateTime? EffectDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string No { get; set; }
        public string SrcNo { get; set; }
        public string SrcType { get; set; }

        public virtual ICollection<TfZc> TfZc { get; set; }
    }
}