// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MfZg
 : Entity<int>    {
        public MfZg()
        {
            TfZg = new HashSet<TfZg>();
        }

        
        public string ZgId { get; set; }
        public string ZgNo { get; set; }
        public DateTime? ZgDd { get; set; }
        public string TradMth { get; set; }
        public string BatNo { get; set; }
        public string CusNo { get; set; }
        public string VohId { get; set; }
        public string VohNo { get; set; }
        public string Dep { get; set; }
        public string TaxId { get; set; }
        public string OsId { get; set; }
        public string OsNo { get; set; }
        public string SendMth { get; set; }
        public string SendWh { get; set; }
        public string ZhangId { get; set; }
        public string CurId { get; set; }
        public decimal? ExcRto { get; set; }
        public string SalNo { get; set; }
        public string Adr { get; set; }
        public string Rem { get; set; }
        public string PayMth { get; set; }
        public short? PayDays { get; set; }
        public short? ChkDays { get; set; }
        public string PayRem { get; set; }
        public DateTime? PayDd { get; set; }
        public DateTime? ChkDd { get; set; }
        public short? IntDays { get; set; }
        public string ClsRem { get; set; }
        public string PrtSw { get; set; }
        public string CpySw { get; set; }
        public decimal? DisCnt { get; set; }
        public string Contract { get; set; }
        public decimal? Amt { get; set; }
        public DateTime? ClsDate { get; set; }
        public string CusOsNo { get; set; }
        public string BilType { get; set; }
        public string CasNo { get; set; }
        public string ClsId { get; set; }
        public string Clsid1 { get; set; }
        public string Usr { get; set; }
        public string ChkMan { get; set; }
        public string ZbNo { get; set; }
        public string HcId { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string PoId { get; set; }
        public string MobId { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public short? FjNum { get; set; }
        public DateTime? SysDate { get; set; }
        public int? TaskId { get; set; }
        public string PrtUsr { get; set; }
        public string CnttNo { get; set; }
        public string CancelId { get; set; }
        public decimal? RtoFqsk { get; set; }
        public string DateflagFqsk { get; set; }
        public DateTime? DateFqsk { get; set; }
        public int? QsFqsk { get; set; }
        public string CurIdIfrs { get; set; }
        public decimal? ExcRtoIfrs { get; set; }
        public DateTime? PrtDate { get; set; }
        public short? AmtPoi { get; set; }
        public DateTime? ModifyDd { get; set; }
        public string ModifyMan { get; set; }
        public string ScanId { get; set; }
        public string ScanUsr { get; set; }
        public DateTime? ScanDate { get; set; }
        public string SgNo { get; set; }
        public string SgId { get; set; }
        public string BusiNo { get; set; }
        public string BilType1 { get; set; }
        public string BilTypeName { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate1 { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan1 { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate1 { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }

        public virtual ICollection<TfZg> TfZg { get; set; }
    }
}