// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MkYg
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public int? Itm { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string YgNo { get; set; }
        public string SpcNo { get; set; }
        public string ZcNo { get; set; }
        public string ModNo { get; set; }
        public string SebNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? QtyScrap { get; set; }
        public string Unit { get; set; }
        public decimal? UseTime { get; set; }
        public string Rem { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public DateTime? BilDd { get; set; }
        public string BomNo { get; set; }
        public decimal? QtyZc { get; set; }
        public int? KeyItm { get; set; }
        public string DjNo { get; set; }
        public string BanNo { get; set; }
        public string MoNo { get; set; }
        public string TzNo { get; set; }
        public string BatNo { get; set; }
        public string Barcode { get; set; }
        public DateTime? StaDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string SalNo { get; set; }
        public string DeliveryDep { get; set; }
        public string ResponsibilityDep { get; set; }
        public string BanGroupNo { get; set; }
        public string BackReason { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public bool? IsClose { get; set; }
        public string BusiNo { get; set; }
        public bool? IsDelete { get; set; }
        public string StationNo { get; set; }
        public string WorkGroup { get; set; }
    }
}