// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MoldWh
 : Entity<int>    {
        
        public string ModNo { get; set; }
        public int ModItm { get; set; }
        public DateTime? GrDd { get; set; }
        public decimal? CstGr { get; set; }
        public string CusNo { get; set; }
        public string StateId { get; set; }
        public int? UseTimes { get; set; }
        public decimal? HoursAll { get; set; }
        public decimal? QtyCrop { get; set; }
        public int? WxTimes { get; set; }
        public DateTime? WxDdL { get; set; }
        public DateTime? InvalidDd { get; set; }
        public string DepUse { get; set; }
        public string SalNoBg { get; set; }
        public DateTime? OpnDd { get; set; }
        public string Wh { get; set; }
        public DateTime? StopDd { get; set; }
        public string Rem { get; set; }
        public string Name { get; set; }
        public string Spc { get; set; }
        public int? UseNum { get; set; }
        public string ModId { get; set; }
        public string FtType { get; set; }
        public short? FtMm { get; set; }
        public decimal? AmtnFt { get; set; }
        public DateTime? FtMmLast { get; set; }
        public decimal? LiftYear { get; set; }
        public decimal? LiftTime { get; set; }
        public decimal? LiftCrop { get; set; }
        public string ChkQualified { get; set; }
        public DateTime? QualifiedDd { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}