// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsCalnoticeInfo
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string Ntno { get; set; }
        public string RpCalStatus { get; set; }
        public string RpCalStatusName { get; set; }
        public string MsNo { get; set; }
        public string MsName { get; set; }
        public string Initial { get; set; }
        public int MsType { get; set; }
        public string MsStatus { get; set; }
        public string Spc { get; set; }
        public string MngType { get; set; }
        public string CalMode { get; set; }
        public string CalResult { get; set; }
        public string Interval { get; set; }
        public int CalCyc { get; set; }
        public DateTime CalDate { get; set; }
        public DateTime Vld { get; set; }
        public string CalMan { get; set; }
        public string CalLocal { get; set; }
        public string CalDep { get; set; }
        public string UserNo { get; set; }
        public string UserDepNo { get; set; }
        public string UserDep { get; set; }
        public string Maker { get; set; }
        public string FactoryNo { get; set; }
        public string Rem { get; set; }
        public bool? IsToCal { get; set; }

        public virtual MsCalnotice MidNavigation { get; set; }
    }
}