// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsCalplanInfo
 : Entity<int>    {
        
        public int Mid { get; set; }
        public int Yy { get; set; }
        public int Mm { get; set; }
        public int Dd { get; set; }
        public string CalFlg { get; set; }
        public string CalResult { get; set; }

        public virtual MsCalplan MidNavigation { get; set; }
    }
}