// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsCalcycChange
 : Entity<int>    {
        
        public string MsNo { get; set; }
        public string MsName { get; set; }
        public string CalResult { get; set; }
        public string Interval { get; set; }
        public string IntervalNew { get; set; }
        public int? CalCyc { get; set; }
        public string CycUnit { get; set; }
        public int? CalCycNew { get; set; }
        public string CycUnitNew { get; set; }
        public DateTime? CalDate { get; set; }
        public DateTime? CalDateNew { get; set; }
        public DateTime? Vld { get; set; }
        public DateTime? VldNew { get; set; }
        public string ChangeReason { get; set; }
        public string FromBusiNo { get; set; }
        public string BusiId { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime? UpdDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public int? IsPrint { get; set; }
    }
}