// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsCalinfo
 : Entity<int>    {
        
        public string No { get; set; }
        public string MsNo { get; set; }
        public string MsName { get; set; }
        public int? MsType { get; set; }
        public string MsStatus { get; set; }
        public string IntervalNew { get; set; }
        public int? CalCycNew { get; set; }
        public string CycUnitNew { get; set; }
        public DateTime? CalDateNew { get; set; }
        public DateTime? VldNew { get; set; }
        public string CalResultNew { get; set; }
        public string AfterCalStatus { get; set; }
        public string CalInstNew { get; set; }
        public string ContactNew { get; set; }
        public decimal? CalCost { get; set; }
        public string CalContent { get; set; }
        public string CalMan { get; set; }
        public string CalLocal { get; set; }
        public string CalType { get; set; }
        public string CalNoteNo { get; set; }
        public string Rem { get; set; }
        public string CertNo1 { get; set; }
        public string CertNo2 { get; set; }
        public string CertNo3 { get; set; }
        public string CertNo4 { get; set; }
        public string CertNo5 { get; set; }
        public string SendCalDep { get; set; }
        public string MsStandardNo { get; set; }
        public string MsStandardContent { get; set; }
        public string CalRuleNo { get; set; }
        public DateTime? ReCalDate { get; set; }
        public string CertType { get; set; }
        public string CertTemp { get; set; }
        public string OutterCert { get; set; }
        public string CalStatus { get; set; }
        public string CalStatusName { get; set; }
        public string Usr { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public DateTime? UpdDate { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool IsPrint { get; set; }
        public string UsrName { get; set; }
        public string UpdUsrName { get; set; }
        public string ChkManName { get; set; }
        public string SoNo { get; set; }
        public int? SoId { get; set; }
    }
}