// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsCalnotice
 : Entity<int>    {
        public MsCalnotice()
        {
            MsCalnoticeInfo = new HashSet<MsCalnoticeInfo>();
        }

        
        public DateTime SendCalDate { get; set; }
        public string Constitutor { get; set; }
        public string SendCalMan { get; set; }
        public string Received { get; set; }
        public DateTime ReceivedDate { get; set; }
        public int WaitCalQty { get; set; }
        public int WaitNoteQty { get; set; }
        public int NotedQty { get; set; }
        public string SenderPhone { get; set; }
        public string SenderMail { get; set; }
        public string BillMonth { get; set; }
        public string SenderDep { get; set; }
        public string Title { get; set; }
        public string No { get; set; }
        public DateTime BillDate { get; set; }
        public string Rem { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime UpdDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public bool IsPrint { get; set; }

        public virtual ICollection<MsCalnoticeInfo> MsCalnoticeInfo { get; set; }
    }
}