// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsMeasureInfoOld
 : Entity<int>    {
        
        public string Name { get; set; }
        public string No { get; set; }
        public string Spc { get; set; }
        public string MsType { get; set; }
        public string Maker { get; set; }
        public string FactoryNo { get; set; }
        public DateTime? FactoryDate { get; set; }
        public string Dep { get; set; }
        public string Precision { get; set; }
        public string Scope { get; set; }
        public string CalMode { get; set; }
        public string Abc { get; set; }
        public bool? IsAlert { get; set; }
        public DateTime? BuyDate { get; set; }
        public string MsStatus { get; set; }
        public decimal? Poprice { get; set; }
        public string Keeper { get; set; }
        public bool? IsStandar { get; set; }
        public string UseLocal { get; set; }
        public string MsDrawingNo { get; set; }
        public byte[] MsPic { get; set; }
        public string Zjm { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public DateTime? UpdDate { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}