// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MsmngStatusinfo
 : Entity<int>    {
        
        public string MsNo { get; set; }
        public string MsName { get; set; }
        public string Status { get; set; }
        public string StatusName { get; set; }
        public string RpCalStatus { get; set; }
        public string RpCalStatusName { get; set; }
        public string FromBusiNo { get; set; }
        public string BusiId { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime UpdDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool IsPrint { get; set; }
    }
}