// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class MyWh
 : Entity<int>    {
        
        public string Wh { get; set; }
        public string Name { get; set; }
        public string Attrib { get; set; }
        public string Dep { get; set; }
        public string Adr { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string UpWh { get; set; }
        public string CntMan { get; set; }
        public bool? Invalid { get; set; }
        public bool? Dubious { get; set; }
        public DateTime? StopDd { get; set; }
        public string CodeNo { get; set; }
        public bool? ChkWh { get; set; }
        public string Rem { get; set; }
        public string SendcusName { get; set; }
        public string ConMan { get; set; }
        public string CusNo { get; set; }
        public bool? Islc { get; set; }
        public string SpcId { get; set; }
        public byte[] UpDd { get; set; }
        public bool? Isiowh { get; set; }
        public bool? Isyl { get; set; }
        public string DeproNo { get; set; }
        public string NamePy { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}