// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PcOutPut
 : Entity<int>    {
        public PcOutPut()
        {
            PcInOutPutRelation = new HashSet<PcInOutPutRelation>();
            PcOutPutDefect = new HashSet<PcOutPutDefect>();
        }

        public string Barcode { get; set; }
        public string BatchNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string BusiNo { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public string ChkMob { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string DevNo { get; set; }
        
        public bool? IsClose { get; set; }
        public bool? IsPrint { get; set; }
        public string MoNo { get; set; }
        public string ProcessNo { get; set; }
        public string ProdNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? QtyScrap { get; set; }
        public string Rem { get; set; }
        public DateTime? ReportDate { get; set; }
        public string ReportGuid { get; set; }
        public string StationNo { get; set; }
        public DateTime SysDate { get; set; }
        public string Unit { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrExec { get; set; }
        public string UsrName { get; set; }
        public string VerNo { get; set; }
        public string WoNo { get; set; }
        public string OutBarcode { get; set; }

        public virtual ICollection<PcInOutPutRelation> PcInOutPutRelation { get; set; }
        public virtual ICollection<PcOutPutDefect> PcOutPutDefect { get; set; }
    }
}