// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PerfOutputT
 : Entity<int>    {
        
        public string SysDate { get; set; }
        public string BanNo { get; set; }
        public string BanGroup { get; set; }
        public string Workshop { get; set; }
        public string ZcNo { get; set; }
        public string SebNo { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public int? Totalcount { get; set; }
        public int? Qualified { get; set; }
        public int? Unqualified { get; set; }
        public int? Scrap { get; set; }
        public int? Backoff { get; set; }
        public int? Handletype { get; set; }
        public string ModNo { get; set; }
    }
}