// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PpWorkPlan
 : Entity<int>    {
        
        public string PlanType { get; set; }
        public string PlanTypeDesc { get; set; }
        public string No { get; set; }
        public string WorkShop { get; set; }
        public string WorkShopCode { get; set; }
        public string PartNo { get; set; }
        public decimal? Quantity { get; set; }
        public string Unit { get; set; }
        public string UnitDesc { get; set; }
        public string CreateUser { get; set; }
        public string UserName { get; set; }
        public string PlanStartDate { get; set; }
        public string PlannEndDate { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string FactoryCode { get; set; }
        public string FactoryName { get; set; }
        public string IsDelete { get; set; }
        public DateTime? UpdateTime { get; set; }
        public string DocStatus { get; set; }
    }
}