// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PpWorkCalendar
 : Entity<int>    {
        
        public string LayoutNo { get; set; }
        public string LayoutName { get; set; }
        public DateTime? WorkDate { get; set; }
        public string ShiftNo { get; set; }
        public string ShiftName { get; set; }
        public string WorkGroup { get; set; }
        public string WorkGroupName { get; set; }
        public DateTime StartTime { get; set; }
        public string StartTimeType { get; set; }
        public DateTime EndTime { get; set; }
        public string EndTimeType { get; set; }
        public decimal? EffectiveHours { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public bool? IsDelete { get; set; }
    }
}