// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PpWorkOrderProcs
 : Entity<int>    {
        public PpWorkOrderProcs()
        {
            PpWorkOrderStation = new HashSet<PpWorkOrderStation>();
        }

        
        public int Mid { get; set; }
        public string MoNo { get; set; }
        public string WoNo { get; set; }
        public string WkCenterNo { get; set; }
        public string ProcessNo { get; set; }
        public decimal? QtyFin { get; set; }
        public decimal? QtyPass { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? QtyScrap { get; set; }

        public virtual PpWorkOrder MidNavigation { get; set; }
        public virtual ICollection<PpWorkOrderStation> PpWorkOrderStation { get; set; }
    }
}