// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PrdStationPara
 : Entity<int>    {
        
        public string PrdNo { get; set; }
        public string PdLineNo { get; set; }
        public string ZcNo { get; set; }
        public string StationNo { get; set; }
        public string ParaNo { get; set; }
        public string ParaName { get; set; }
        public string UpLimit { get; set; }
        public string LowLimit { get; set; }
        public string ParaType { get; set; }
        public int? Sort { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}