// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PrdSpc
 : Entity<int>    {
        public string SpcId { get; set; }
        public string SpcName { get; set; }
        public decimal? QtyBox { get; set; }
        public decimal? WgUnit { get; set; }
        public short? QtyBoxP { get; set; }
        public short? QtyTier { get; set; }
    }
}