// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Prdt1Info
 : Entity<int>    {
        
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdSpc { get; set; }
        public string Unit { get; set; }
        public string Wh { get; set; }
        public byte? InOut { get; set; }
        public decimal? Qty { get; set; }
        public DateTime? SysDate { get; set; }
    }
}