// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PrdtChangeInfos
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string PrdNo { get; set; }
        public DateTime StaTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Usr { get; set; }
        public string Usrname { get; set; }
        public DateTime? Sysdate { get; set; }
        public DateTime? Upddate { get; set; }
        public string Updusr { get; set; }
        public string Updusrname { get; set; }
    }
}