// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PrdtCus2
 : Entity<int>    {
        
        public string CusNo { get; set; }
        public string PrdNo { get; set; }
        public string SupPrdNo { get; set; }
        public string SupPrdName { get; set; }
        public string Rem { get; set; }
        public decimal? PakGw { get; set; }
        public bool? NeedChkBarCode { get; set; }
        public decimal? SmallPackageQty { get; set; }
    }
}