// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Prdt1
 : Entity<int>    {
        
        public string Wh { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public decimal? QtyInt { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? AmtCst { get; set; }
        public decimal? QtyMax { get; set; }
        public decimal? QtyMin { get; set; }
        public decimal? QtyLrn { get; set; }
        public decimal? QtyBrw { get; set; }
        public decimal? QtyOnWay { get; set; }
        public decimal? QtyOnPrc { get; set; }
        public decimal? QtyOnRsv { get; set; }
        public decimal? QtyOnOdr { get; set; }
        public DateTime? LstOtd { get; set; }
        public DateTime? LstInd { get; set; }
        public DateTime? LstSfd { get; set; }
        public decimal? UpInt { get; set; }
        public decimal? CstInt { get; set; }
        public decimal? CstStd { get; set; }
        public decimal? CstPo { get; set; }
        public decimal? CstSal { get; set; }
        public decimal? UpStd { get; set; }
        public decimal? UpSal { get; set; }
        public decimal? Qty1Lrn { get; set; }
        public decimal? Qty1Brw { get; set; }
        public decimal? UpPo { get; set; }
        public decimal? QtySa { get; set; }
        public decimal? QtyRk { get; set; }
        public decimal? QtyZg { get; set; }
        public decimal? QtyCk { get; set; }
        public decimal? QtySq { get; set; }
        public string Rem { get; set; }
        public DateTime? ChqcDd { get; set; }
        public decimal? QtySw { get; set; }
        public decimal? QtyWx { get; set; }
        public decimal? QtyWs { get; set; }
        public decimal? QtyWsKc { get; set; }
        public decimal? QtyQl { get; set; }
        public decimal? QtyQ2 { get; set; }
        public decimal? QtyQ2Yl { get; set; }
        public decimal? QtyQ3 { get; set; }
        public decimal? CstBx { get; set; }
        public decimal? QtySqr { get; set; }
        public decimal? QtySqc { get; set; }
        public decimal? QtyLock { get; set; }
        public decimal? QtyJh { get; set; }
        public DateTime? ScDd { get; set; }
        public DateTime? LstOtdQc { get; set; }
        public DateTime? LstIndQc { get; set; }
        public byte[] UpDd { get; set; }
        public decimal? Qty1Lock { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}