// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class PrdtUt
 : Entity<int>    {
        
        public string No { get; set; }
        public string UtId { get; set; }
        public string Ut { get; set; }
    }
}