// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Predefreason
 : Entity<int>    {
        
        public string No { get; set; }
        public string Name { get; set; }
        public string CallTypeNo { get; set; }
        public int? Sort { get; set; }
        public string ZcNo { get; set; }
    }
}