// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcBarcode
 : Entity<int>    {
        
        public string Barcode { get; set; }
        public int? Flag { get; set; }
        public DateTime? Sysdate { get; set; }
    }
}