// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcFinished
 : Entity<int>    {
        
        /// <summary>
        /// 表单
        /// </summary>
        public string PfaNo { get; set; }
        /// <summary>
        /// 产品
        /// </summary>
        public string PrdNo { get; set; }
        /// <summary>
        /// 起始日期
        /// </summary>
        public DateTime? FromDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        public DateTime? ToDate { get; set; }
        /// <summary>
        /// 送检数量
        /// </summary>
        public decimal? Qty { get; set; }
        /// <summary>
        /// 用户编号
        /// </summary>
        public string Usr { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string UsrName { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? SysDate { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? UpdDate { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Comment { get; set; }
        /// <summary>
        /// 周期类别 10.首件 20.末件 30.件数 40.分钟 50.小时 60.天
        /// </summary>
        public int? CycleType { get; set; }
        /// <summary>
        /// 周期
        /// </summary>
        public int? Cycle { get; set; }
    }
}