// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcInspFreq
 : Entity<int>    {
        
        public string FreqName { get; set; }
        public int? RreqValue { get; set; }
        public string Unit { get; set; }
        public DateTime? Sysdate { get; set; }
    }
}