// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcPrdInspectSchemes
 : Entity<int>    {
        
        public string WsSpc { get; set; }
        public string IsWsFirstInspect { get; set; }
        public string IsWsLastInspect { get; set; }
        public string IsWsInspect { get; set; }
        public string WsInspectHz { get; set; }
        public string WsInspectType { get; set; }
        public string WsInspectCnt { get; set; }
        public string WsCollectMethod { get; set; }
        public string QcSpc { get; set; }
        public string IsQcFirstInspect { get; set; }
        public string IsQcLastInspect { get; set; }
        public string IsQcInspect { get; set; }
        public string QcInspectHz { get; set; }
        public string QcInspectType { get; set; }
        public string QcInspectCnt { get; set; }
        public string QcCollectMethod { get; set; }
        public string PrdNo { get; set; }
        public string ZcNo { get; set; }
        public string DeviceNo { get; set; }
        public string Mould { get; set; }
        public string WeatherCondition { get; set; }
        public string MonthCondition { get; set; }
        public string InspectProjectName { get; set; }
        public string MinTolerance1 { get; set; }
        public string MaxTolerance1 { get; set; }
        public string MinScope1 { get; set; }
        public string MaxScope1 { get; set; }
        public string MinTolerance2 { get; set; }
        public string MaxTolerance2 { get; set; }
        public string MinScope2 { get; set; }
        public string MaxScope2 { get; set; }
        public string StandardScopeValue { get; set; }
        public string InspectType { get; set; }
        public DateTime? CreateDate { get; set; }
        public string ZcName { get; set; }
        public DateTime? EffDate { get; set; }
        public string InspectProjectNo { get; set; }
        public int? Sort { get; set; }
    }
}