// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcRecordvalue
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string ItemNo { get; set; }
        public string QcItm { get; set; }
        public string QcValue { get; set; }
        public string SalNo { get; set; }
        public string SpcNo { get; set; }
        public string Descp { get; set; }
        public decimal? NumMax { get; set; }
        public decimal? NumMin { get; set; }
        public string Upsybol { get; set; }
        public string Lowsybol { get; set; }
        public int? SpId { get; set; }
        public string QcModel { get; set; }
        public string QcResult { get; set; }
        public string QcUnit { get; set; }
        public bool? IsSubmit { get; set; }
        public decimal? InspectionQty { get; set; }
        public string InspectionFunc { get; set; }
        public string ParamType { get; set; }
        public string QcEnumBusiNo { get; set; }
        public decimal? StandardValue { get; set; }
        public int? FirstValueId { get; set; }

        public virtual QcRecord MidNavigation { get; set; }
    }
}