// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QcTool
 : Entity<int>    {
        
        public string ToolNo { get; set; }
        public string Name { get; set; }
    }
}