// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmInspectSd
 : Entity<int>    {
        
        /// <summary>
        /// 检验样本ID
        /// </summary>
        public int Mid { get; set; }
        /// <summary>
        /// 设备号
        /// </summary>
        public string DeviceNo { get; set; }
        /// <summary>
        /// 产品编码
        /// </summary>
        public string ProductNo { get; set; }
        /// <summary>
        /// 检测时间
        /// </summary>
        public DateTime? InspectDate { get; set; }
        /// <summary>
        /// 检查项中文名
        /// </summary>
        public string InspectName { get; set; }
        /// <summary>
        /// 检测项代码
        /// </summary>
        public string InspectCode { get; set; }
        /// <summary>
        /// 检测值下限
        /// </summary>
        public string LowerLimit { get; set; }
        /// <summary>
        /// 检测值上限
        /// </summary>
        public string UpperLimit { get; set; }
        /// <summary>
        /// 检测标准值
        /// </summary>
        public string StandardValue { get; set; }
        /// <summary>
        /// 实测值
        /// </summary>
        public string RealValue { get; set; }
        /// <summary>
        /// 单位
        /// </summary>
        public string Unit { get; set; }
        public string InspectType { get; set; }
        public string BarCode { get; set; }
        public DateTime? InputDate { get; set; }
        public string CastingBatchNo { get; set; }
        public string StoveNo { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 是否合格
        /// </summary>
        public string Result { get; set; }
        /// <summary>
        /// 更新时间戳
        /// </summary>
        public byte[] UpdateStamp { get; set; }
        public DateTime? Sysdate { get; set; }
    }
}