// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmProcessInspection
 : Entity<int>    {
        public string Attachment { get; set; }
        
        public string No { get; set; }
        public string ProcessNo { get; set; }
        public string ProdName { get; set; }
        public string ProdNo { get; set; }
        public string ProdSpc { get; set; }
        public DateTime StartDate { get; set; }
        public string WkCenterNo { get; set; }
        public string WoNo { get; set; }
    }
}