// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmTibarcode
 : Entity<int>    {
        public string Barcode { get; set; }
        public string Comment { get; set; }
        public DateTime? HandleDate { get; set; }
        public int? HandleResult { get; set; }
        public string HandleUser { get; set; }
        
        public int? Mid { get; set; }
        public decimal? Qty { get; set; }

        public virtual QmTisub MidNavigation { get; set; }
    }
}