// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmTisub
 : Entity<int>    {
        public QmTisub()
        {
            QmTibarcode = new HashSet<QmTibarcode>();
        }

        public string BatchNo { get; set; }
        public string Comment { get; set; }
        
        public DateTime? InspectionDate { get; set; }
        public bool? IsCheck { get; set; }
        public bool? IsSample { get; set; }
        public int? Mid { get; set; }
        public DateTime? ProducedDate { get; set; }
        public string ProductionNo { get; set; }
        public decimal? QtyPs { get; set; }
        public decimal? QtyRtn { get; set; }
        public string RawMaterialBatch { get; set; }
        public string RbillNo { get; set; }
        public int? RbillSid { get; set; }
        public string RbusiName { get; set; }
        public string RbusiNo { get; set; }
        public decimal? Siqty { get; set; }
        public int? WhId { get; set; }
        public decimal? QtyRck { get; set; }
        public string SourceLocation { get; set; }
        public string TargetWareHouse { get; set; }
        public bool? Result { get; set; }
        public string StorageLocation { get; set; }

        public virtual QmTi MidNavigation { get; set; }
        public virtual ICollection<QmTibarcode> QmTibarcode { get; set; }
    }
}