// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmTysub
 : Entity<int>    {
        public QmTysub()
        {
            QmTybarcode = new HashSet<QmTybarcode>();
        }

        public string BatchNo { get; set; }
        public string Comment { get; set; }
        
        public DateTime? InspectionDate { get; set; }
        public int? Mid { get; set; }
        public string PrcId { get; set; }
        public string ProductionNo { get; set; }
        public decimal? QtyChk { get; set; }
        public decimal? QtyChkLost { get; set; }
        public decimal? QtyChkOk { get; set; }
        public decimal? QtyLostRtn { get; set; }
        public decimal? QtyOkRtn { get; set; }
        public decimal? QtyRtn { get; set; }
        public string RbillNo { get; set; }
        public int? RbillSid { get; set; }
        public string RbusiName { get; set; }
        public string RbusiNo { get; set; }
        public string SpcNo { get; set; }
        public int? WhId { get; set; }
        public decimal? Qty { get; set; }
        public decimal? QtyRbill { get; set; }
        public string UnqulifiedType { get; set; }
        public DateTime? ProducedDate { get; set; }
        public string SourceLocation { get; set; }
        public string TargetWareHouse { get; set; }

        public virtual QmTy MidNavigation { get; set; }
        public virtual ICollection<QmTybarcode> QmTybarcode { get; set; }
    }
}