// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QmTy
 : Entity<int>    {
        public QmTy()
        {
            QmTysub = new HashSet<QmTysub>();
        }

        public string BillNo { get; set; }
        public string BillStatus { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string BusiNo { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public string ChkMob { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string DeptNo { get; set; }
        
        public int? InspectorId { get; set; }
        public bool? IsClose { get; set; }
        public bool? IsPrint { get; set; }
        public string Rem { get; set; }
        public string SourceBillNo { get; set; }
        public string SuppCode { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public int? ChkKnd { get; set; }

        public virtual ICollection<QmTysub> QmTysub { get; set; }
    }
}