// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class QueryInspectionResult
 : Entity<int>    {
        public string QcItm { get; set; }
        public string QcResult { get; set; }
        public string InspectionFunc { get; set; }
        public string Descp { get; set; }
        public string QcValue { get; set; }
        public decimal? NumMin { get; set; }
        public decimal? NumMax { get; set; }
        public string Upsybol { get; set; }
        public string Lowsybol { get; set; }
        public string No { get; set; }
        public string TypeName { get; set; }
        public string SourceBillNo { get; set; }
        
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public string PrdNo { get; set; }
        public string ProductionName { get; set; }
        public string Spc { get; set; }
        public int? SamplingRule { get; set; }
        public decimal? SampleQty { get; set; }
        public decimal? RecordQty { get; set; }
    }
}