// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RespInfo
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string RespSalNo { get; set; }
        public DateTime? RespDate { get; set; }
        public string ResetSalNo { get; set; }
        public DateTime? ResetDate { get; set; }
        public DateTime SysDate { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string BusiNo { get; set; }
        public string SourceNo { get; set; }
        public string Rem { get; set; }
        public string RespComment { get; set; }
        public string ToBillNo { get; set; }
        public string FcNo { get; set; }
        public string FcName { get; set; }
    }
}