// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmCuttersSerialNumber
 : Entity<int>    {
        
        public string SerialNo { get; set; }
        public string CutterNo { get; set; }
        public string CutterName { get; set; }
        public string State { get; set; }
        public int? QtyStandard { get; set; }
        public int? QtyMax { get; set; }
        public int? QtyWarn { get; set; }
        public int? QtyMachining { get; set; }
        public string StorageLoc { get; set; }
        public DateTime? WhseDate { get; set; }
        public DateTime? ScrapedDate { get; set; }
        public string SupNo { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
    }
}