// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmCuttersCode
 : Entity<int>    {
        
        public string CutterNo { get; set; }
        public string CutterName { get; set; }
        public string CutterDesc { get; set; }
        public string TypeNo { get; set; }
        public decimal? QtyStandard { get; set; }
        public decimal? FactorMax { get; set; }
        public decimal? FactorWarn { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
    }
}