// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmCuttersTrace
 : Entity<int>    {
        
        public string Optype { get; set; }
        public string Usr { get; set; }
        public DateTime SysDate { get; set; }
        public string WoNo { get; set; }
        public string SebNo { get; set; }
        public string CutterNo { get; set; }
        public string CutterSn { get; set; }
        public string ZcStep { get; set; }
        public string InstallSite { get; set; }
        public string StationNo { get; set; }
    }
}