// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmFixtureProdectMapping
 : Entity<int>    {
        
        public string Name { get; set; }
        public string ProdectCode { get; set; }
        public string ProdectName { get; set; }
        public string FixtureCode { get; set; }
        public string FixtureName { get; set; }
        public string TypeNature { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
    }
}