// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmFixtrueUse
 : Entity<int>    {
        public string FixtureSn { get; set; }
        public string FixtureCode { get; set; }
        public string FixtureName { get; set; }
        
        public string ProcessNo { get; set; }
        public string StationNo { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
    }
}