// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmMoldRepairRecordItem
 : Entity<int>    {
        public RmMoldRepairRecordItem()
        {
            RmMoldRepairRecordReason = new HashSet<RmMoldRepairRecordReason>();
        }

        public DateTime? EndDate { get; set; }
        
        public int? Item { get; set; }
        public int Mid { get; set; }
        public string ModNo { get; set; }
        public string ModSn { get; set; }
        public decimal? Qty { get; set; }
        public int? SrcItemId { get; set; }
        public DateTime? StartDate { get; set; }
        public string PartNo { get; set; }
        public string ModType { get; set; }
        public string CancelReason { get; set; }
        public string RepCode { get; set; }
        public string RepContent { get; set; }
        public string Status { get; set; }
        public string UsrCancel { get; set; }
        public string UsrRep { get; set; }
        public string UsrValid { get; set; }

        public virtual RmMoldRepairRecord MidNavigation { get; set; }
        public virtual ICollection<RmMoldRepairRecordReason> RmMoldRepairRecordReason { get; set; }
    }
}