// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmMoldParts
 : Entity<int>    {
        public RmMoldParts()
        {
            RmMoldSparePartInfo = new HashSet<RmMoldSparePartInfo>();
        }

        public bool? Disable { get; set; }
        
        public string ModNo { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string ParentNo { get; set; }
        public int? Sort { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string Dept { get; set; }

        public virtual ICollection<RmMoldSparePartInfo> RmMoldSparePartInfo { get; set; }
    }
}