// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmMoldInspTaskItems
 : Entity<int>    {
        public string Content { get; set; }
        public string DataType { get; set; }
        public string EnumNo { get; set; }
        
        public int? Item { get; set; }
        public decimal? LowLimit { get; set; }
        public string LowSybol { get; set; }
        public string Method { get; set; }
        public int Mid { get; set; }
        public string PartNo { get; set; }
        public string Result { get; set; }
        public int? SrcItemId { get; set; }
        public string Standard { get; set; }
        public decimal? UpLimit { get; set; }
        public string UpSybol { get; set; }
        public string Unit { get; set; }
        public bool? IsFail { get; set; }

        public virtual RmMoldInspTask MidNavigation { get; set; }
    }
}