// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class RmMoldRepairRequestFault
 : Entity<int>    {
        public string FaultCode { get; set; }
        public string FaultDesc { get; set; }
        
        public int Mid { get; set; }
        public string ModNo { get; set; }
        public string ModSn { get; set; }
        public string PartNo { get; set; }

        public virtual RmMoldRepairRequestItem MidNavigation { get; set; }
    }
}