// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbbyPrj
 : Entity<int>    {
        
        public int Mid { get; set; }
        public short Yy { get; set; }
        public short Mm { get; set; }
        public short Dd { get; set; }
        public string BydjNo { get; set; }
        public string RunFlag { get; set; }
    }
}