// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbChangeList
 : Entity<int>    {
        public string No { get; set; }
        public string Name { get; set; }
        public decimal? Qty { get; set; }
        public string SalNo { get; set; }
        public DateTime? ChangeDd { get; set; }
        public string ChangeReason { get; set; }
        public string Rem { get; set; }
        public string BilNo { get; set; }
    }
}