// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbMtRuntime
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string SpecType { get; set; }
        public string SpecNo { get; set; }
        public string StaNo { get; set; }
        public decimal TotalRunTime { get; set; }
        public decimal TimeFromLatestMt { get; set; }
        public int? MtTimes { get; set; }
        public int QtyCycle { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime? UpdDate { get; set; }
    }
}