// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbPrdtPara
 : Entity<int>    {
        public SbPrdtPara()
        {
            SbPrdtParas = new HashSet<SbPrdtParas>();
        }

        
        public string No { get; set; }
        public string Name { get; set; }
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string Rem { get; set; }
        public DateTime? BillDate { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime? UpdDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public bool? IsPrint { get; set; }
        public string MouldNo { get; set; }
        public string Temperature { get; set; }
        public string Months { get; set; }
        public string MouldName { get; set; }
        public string CoolMode { get; set; }
        public DateTime? EffDate { get; set; }
        public string ZcNo { get; set; }
        public byte[] TimeStamp { get; set; }
        public string DataModel { get; set; }
        public string Version { get; set; }
        public int? Frequency { get; set; }
        public string FrequencyType { get; set; }
        public DateTime? ExpiryDate { get; set; }

        public virtual ICollection<SbPrdtParas> SbPrdtParas { get; set; }
    }
}