// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbPrdtParas
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string Itm { get; set; }
        public string ParaNo { get; set; }
        public string ParaName { get; set; }
        public string Ut { get; set; }
        public decimal? UpLimit { get; set; }
        public decimal? LowLimit { get; set; }
        public decimal? Standard { get; set; }
        public string LowSybol { get; set; }
        public string UpSybol { get; set; }
        public string Ptype { get; set; }
        public string Manner { get; set; }
        public string Formula { get; set; }
        public string UtId { get; set; }
        public string DefaultVal { get; set; }
        public byte[] TimeStamp { get; set; }

        public virtual SbPrdtPara MidNavigation { get; set; }
    }
}