// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbRunRecord
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public DateTime StdTime { get; set; }
        public DateTime? EndTime { get; set; }
        public decimal? TimeDiff { get; set; }
        public string TimeUnit { get; set; }
        public string StaNo { get; set; }
        public string StaProp { get; set; }
        public string Rem { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public DateTime? UpdDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}