// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbSpRecord
 : Entity<int>    {
        
        public int Mid { get; set; }
        public int Itm { get; set; }
        public string SpNo { get; set; }
        public string Name { get; set; }
        public decimal? Qty { get; set; }
        public string Rem { get; set; }
    }
}