// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SbStatusChanges
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public string Bgtype { get; set; }
        public string BgProperty { get; set; }
        public string Dep { get; set; }
        public string PreDep { get; set; }
        public DateTime? ExpDd { get; set; }
        public DateTime? PreExpDd { get; set; }
        public decimal? Oec { get; set; }
        public decimal? PreOec { get; set; }
        public string State { get; set; }
        public string PreState { get; set; }
        public string Rem { get; set; }

        public virtual SbStatusChange MidNavigation { get; set; }
    }
}