// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class ScSbxxb
 : Entity<int>    {
        
        public string Sbbh { get; set; }
        public string Sbmc { get; set; }
        public string Csbh { get; set; }
        public string Csmc { get; set; }
        public byte? Cslx { get; set; }
        public string Xsw { get; set; }
    }
}