// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Sebei
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string Name { get; set; }
        public string Dep { get; set; }
        public string Model { get; set; }
        public string Abctype { get; set; }
        public string State { get; set; }
        public decimal? Height { get; set; }
        public decimal? CirIn { get; set; }
        public decimal? Weight { get; set; }
        public string XyzStroke { get; set; }
        public string SpindlePower { get; set; }
        public string MinDistance { get; set; }
        public string AtcContent { get; set; }
        public string TableSize { get; set; }
        public string ContourSize { get; set; }
        public string MesaLoad { get; set; }
        public string EqptWeight { get; set; }
        public string Speed { get; set; }
        public string EqptPowC { get; set; }
        public DateTime? GrDd { get; set; }
        public string Spc { get; set; }
        public string CusNo { get; set; }
        public int? ServiceLife { get; set; }
        public decimal? Power { get; set; }
        public DateTime? RelDd { get; set; }
        public DateTime? SetDd { get; set; }
        public DateTime? OpnDd { get; set; }
        public DateTime? BfDd { get; set; }
        public decimal? Oec { get; set; }
        public string Rem { get; set; }
        public decimal? LenB { get; set; }
        public decimal? LenE { get; set; }
        public string Ut { get; set; }
        public decimal? QtyDay { get; set; }
        public string FxKnd { get; set; }
        public string FxNo { get; set; }
        public string UpNo { get; set; }
        public byte[] Sbimage { get; set; }
        public string Ecuse { get; set; }
        public decimal? Tax { get; set; }
        public decimal? AmtnNet { get; set; }
        public string CostCenter { get; set; }
        public string InstallSite { get; set; }
        public string Mfno { get; set; }
        public string Responsible { get; set; }
        public string PdLine { get; set; }
        public decimal? TotalRunTime { get; set; }
        public decimal? TimeFromLatestMt { get; set; }
        public int? MtTimes { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public string AbbName { get; set; }
        public string SerialNo { get; set; }
    }
}