// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SebState
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public int ItmSb { get; set; }
        public DateTime? GrDd { get; set; }
        public decimal? Cst { get; set; }
        public string CusNo { get; set; }
        public string StateId { get; set; }
        public string SalNoBg { get; set; }
        public DateTime? OpnDd { get; set; }
        public DateTime? WxDdL { get; set; }
        public DateTime? InvalidDd { get; set; }
        public string Rem { get; set; }
        public string Dep { get; set; }
        public string Name { get; set; }
        public string OldState { get; set; }
        public string SebId { get; set; }
        public string Spc { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}