// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Setdefvalues
 : Entity<int>    {
        
        public string Usr { get; set; }
        public string BusiId { get; set; }
        public int Itm { get; set; }
        public string Flag { get; set; }
        public string BusiNo { get; set; }
        public string Rem { get; set; }
        public byte[] Content { get; set; }
    }
}