// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class ShiftScheduling
 : Entity<int>    {
        public string No { get; set; }
        public string Name { get; set; }
        public DateTime Ssdate { get; set; }
        public string Deptno { get; set; }
        public string ShiftNo { get; set; }
        public string TeamNo { get; set; }
        public string Usrname { get; set; }
        public DateTime? Sysdate { get; set; }
        public string Updusr { get; set; }
        public DateTime? Upddate { get; set; }
        public string Chkman { get; set; }
        public string Chkmanname { get; set; }
        public DateTime? Chkdate { get; set; }
        public string Chkmob { get; set; }
        public bool? Isprint { get; set; }
        public string Updusrname { get; set; }
        
        public string Usr { get; set; }
    }
}