// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Sprd
 : Entity<int>    {
        
        public string Wh { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public short Yy { get; set; }
        public short Mm { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? QtyLn { get; set; }
        public decimal? QtyBr { get; set; }
        public decimal? Qty1Ln { get; set; }
        public decimal? Qty1Br { get; set; }
        public decimal? Cst { get; set; }
        public decimal? Uup { get; set; }
        public decimal? CstStd { get; set; }
        public string Rem { get; set; }
        public decimal? QtyBoxItm { get; set; }
        public decimal? CstIfrs { get; set; }
        public decimal? CstStdIfrs { get; set; }
        public decimal? UupIfrs { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}