// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StBarcodesplit
 : Entity<int>    {
        
        public string SourceBarcode { get; set; }
        public string ToBarcode { get; set; }
        public string PrdNo { get; set; }
        public DateTime SysDate { get; set; }
    }
}