// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StBarcodeinfos
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string RbillType { get; set; }
        public string RbillNo { get; set; }
        public int? Itm { get; set; }
        public int? EstItm { get; set; }
        public string PrdNo { get; set; }
        public string PrdSnm { get; set; }
        public string PrdName { get; set; }
        public string PrdSpc { get; set; }
        public string BatNo { get; set; }
        public string Barcode { get; set; }
        public DateTime? BillDate { get; set; }
        public DateTime? CodeDate { get; set; }
        public bool? Isprint { get; set; }
        public DateTime? PrintDate { get; set; }
        public DateTime? MakeDate { get; set; }
        public int? ValidDays { get; set; }
        public DateTime? ValidDate { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public string Unit { get; set; }
        public string Unit1 { get; set; }
        public string Resbarcode { get; set; }
        public string Memo { get; set; }
        public string CusNo { get; set; }
        public string CusName { get; set; }
        public string TrayNo { get; set; }
        public string CylNo { get; set; }
        public string ShipNo { get; set; }
        public string Ran { get; set; }

        public virtual StBarcodeinfo MidNavigation { get; set; }
    }
}