// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StBarcoderes
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string RbillType { get; set; }
        public string RbillNo { get; set; }
        public int? Itm { get; set; }
        public int? EstItm { get; set; }
        public DateTime? BillDate { get; set; }
        public string CusNo { get; set; }
        public string PrdNo { get; set; }
        public string Unit { get; set; }
        public string Unit1 { get; set; }
        public string BatNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public string Unitpk2 { get; set; }
        public decimal? Qtypk2 { get; set; }
        public decimal? Qtypak { get; set; }
        public string SalNo { get; set; }
        public string Dep { get; set; }
        public string BusiNo { get; set; }
        public string Memo { get; set; }
    }
}