// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StBarcodeinfo
 : Entity<int>    {
        public StBarcodeinfo()
        {
            StBarcodeinfos = new HashSet<StBarcodeinfos>();
        }

        
        public string No { get; set; }
        public DateTime? BillDate { get; set; }
        public string BusiNo { get; set; }
        public string Memo { get; set; }
        public int BillclsId { get; set; }
        public int UserId { get; set; }
        public DateTime InputDate { get; set; }
        public int Flag { get; set; }
        public string AuNo { get; set; }
        public int ChkUserId { get; set; }
        public DateTime? ChkDate { get; set; }
        public int IsPrint { get; set; }
        public int CloseUserId { get; set; }
        public DateTime? CloseDate { get; set; }

        public virtual ICollection<StBarcodeinfos> StBarcodeinfos { get; set; }
    }
}