// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StBarcodemergeinfo
 : Entity<int>    {
        public string BarcodeOld { get; set; }
        public string BarcodeNew { get; set; }
        public DateTime? Createtime { get; set; }
    }
}