// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class StTdcodePallet
 : Entity<int>    {
        
        public string Pcode { get; set; }
        public string Tdcode { get; set; }
        public DateTime? Sysdate { get; set; }
        public int Mid { get; set; }

        public virtual StPalletcodeInfo MidNavigation { get; set; }
    }
}