// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysAuditFlowDetails
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string BusiNo { get; set; }
        public string ChkMob { get; set; }
        public int Item { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string Rem { get; set; }
        public string Agent { get; set; }
        public short? ValidTime { get; set; }
        public short? DelayTime { get; set; }
        public string Tonext { get; set; }
        public string Signer { get; set; }
        public string SigningAgent { get; set; }
        public bool? IsTitle { get; set; }
        public string CdtSql { get; set; }

        public virtual SysAuditFlow MidNavigation { get; set; }
    }
}