// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysAudBillInfo
 : Entity<int>    {
        public SysAudBillInfo()
        {
            SysAudBillItem = new HashSet<SysAudBillItem>();
        }

        
        public string AudNo { get; set; }
        public DateTime? AudDate { get; set; }
        public string BusiNo { get; set; }
        public string BillNo { get; set; }
        public DateTime? BillDate { get; set; }
        public int? BillId { get; set; }
        public string BillUsrDept { get; set; }
        public string BillCreateUser { get; set; }
        public string BillType { get; set; }
        public string BillRemark { get; set; }
        public string CustNo { get; set; }
        public string UsrExec { get; set; }
        public string UsrExecDept { get; set; }
        public DateTime? SubMitDate { get; set; }
        public string UsrCur { get; set; }
        public string UsrCurAgent { get; set; }
        public string UsrPre { get; set; }
        public string UsrClose { get; set; }
        public string UsrOther { get; set; }
        public string AudState { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string MenuNo { get; set; }
        public string Result { get; set; }

        public virtual ICollection<SysAudBillItem> SysAudBillItem { get; set; }
    }
}