// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysBarcodeInfo
 : Entity<int>    {
        
        public string RuleId { get; set; }
        public string Variable { get; set; }
        public string PrevDate { get; set; }
        public int? MaxSn { get; set; }
    }
}