// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysBillsource
 : Entity<int>    {
        
        public string MenuNo { get; set; }
        public string QueryNo { get; set; }
        public DateTime InputDate { get; set; }
    }
}