// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysBillnoRuleSet
 : Entity<int>    {
        
        public string Encoded { get; set; }
        public bool? CanOrder { get; set; }
        public int? DefaultOrder { get; set; }
        public bool? Enabled { get; set; }
        public string BitsSet { get; set; }
        public string MaxBits { get; set; }
        public string MinBits { get; set; }
        public string DataType { get; set; }
        public byte? CodeBits { get; set; }
        public string EncodeType { get; set; }
    }
}