// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysBillnoRule
 : Entity<int>    {
        public string BillId { get; set; }
        public string BillDesc { get; set; }
        public string DateFormat { get; set; }
        public byte? BillType { get; set; }
        public byte? Dept { get; set; }
        public byte? Maker { get; set; }
        public byte? Db { get; set; }
        public byte? Other { get; set; }
        public string SelfIdCode { get; set; }
        public byte? SerialNum { get; set; }
        public string GetDelBill { get; set; }
        public string BillModifiable { get; set; }
        public string IsSelfIdCode { get; set; }
        public byte? ActCodeBits { get; set; }
        
    }
}