// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysCodenoRule
 : Entity<int>    {
        public SysCodenoRule()
        {
            SysCodenoRules = new HashSet<SysCodenoRules>();
        }

        
        public string RuleId { get; set; }
        public int RuleOrder { get; set; }
        public int RuleType { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual ICollection<SysCodenoRules> SysCodenoRules { get; set; }
    }
}