// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysCodenoRules
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string CombiId { get; set; }
        public string CombiType { get; set; }
        public int CombiOrder { get; set; }
        public string ItemType { get; set; }
        public string FixChar { get; set; }
        public int? ItemLen { get; set; }
        public string Format { get; set; }
        public string Align { get; set; }
        public string CoverChar { get; set; }
        public string VarField { get; set; }
        public string UpdateTime { get; set; }

        public virtual SysCodenoRule MidNavigation { get; set; }
    }
}