// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysDataRules
 : Entity<int>    {
        
        public string BusiNo { get; set; }
        public string TableName { get; set; }
        public string MenuNo { get; set; }
        public string Rules { get; set; }
        public DateTime SysDate { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public bool? IsValid { get; set; }
    }
}