// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysFlowchart
 : Entity<int>    {
        
        public Guid? BackImage { get; set; }
        public string BackImgLayOut { get; set; }
        public Guid? FlowChart { get; set; }
        public string Name { get; set; }
        public string No { get; set; }
        public string MenuNo { get; set; }
        public string ShowTipType { get; set; }
        public string FlowType { get; set; }
        public string BomNo { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
    }
}