// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysInterfaceUrl
 : Entity<int>    {
        
        public string InterfaceName { get; set; }
        public string InterfaceCode { get; set; }
        public int Environment { get; set; }
        public string Url { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public bool? IsDeleted { get; set; }
        public string CreateUserNo { get; set; }
        public DateTime? CreateTime { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? UpdateTime { get; set; }
        public string Uc01 { get; set; }
        public string Uc02 { get; set; }
        public string Uc03 { get; set; }
        public string Uc04 { get; set; }
        public string Uc05 { get; set; }
        public string ErpFormTyoe { get; set; }
        public string ErpFormType { get; set; }
    }
}