// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysLangData
 : Entity<int>    {
        
        public string TableName { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string L0 { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string Korean { get; set; }
    }
}