// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysProperty
 : Entity<int>    {
        
        public string MenuNo { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string ItemValue { get; set; }
        public string ItemValueType { get; set; }
        public int ItemSort { get; set; }
        public int EditType { get; set; }
        public string EditNo { get; set; }
        public string EditField { get; set; }
        public bool IsSystem { get; set; }
        public string Rem { get; set; }
        public DateTime? UpdDate { get; set; }
        public DateTime? SysDate { get; set; }
        public string UpdUsr { get; set; }
    }
}