// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysParams
 : Entity<int>    {
        
        public string Paramgroupcode { get; set; }
        public string Paramgroupdesc { get; set; }
        public string Paramcode { get; set; }
        public string Paramdesc { get; set; }
        public string Paramvalue { get; set; }
        public bool? Isavailable { get; set; }
        public string Usr { get; set; }
        public string Usrname { get; set; }
        public DateTime Sysdate { get; set; }
        public DateTime? Upddate { get; set; }
        public string Updusrname { get; set; }
        public string Updusr { get; set; }
        public int? SortIndex { get; set; }
    }
}