// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysRoleUser
 : Entity<int>    {
        
        public int Mid { get; set; }
        public int UserId { get; set; }

        public virtual SysRole MidNavigation { get; set; }
        public virtual SysUser User { get; set; }
    }
}