// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysRole
 : Entity<int>    {
        public SysRole()
        {
            SysRoleData = new HashSet<SysRoleData>();
            SysRoleField = new HashSet<SysRoleField>();
            SysRoleMenu = new HashSet<SysRoleMenu>();
            SysRoleUser = new HashSet<SysRoleUser>();
        }

        
        public int ParentId { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string CusNo { get; set; }
        public string Remark { get; set; }

        public virtual ICollection<SysRoleData> SysRoleData { get; set; }
        public virtual ICollection<SysRoleField> SysRoleField { get; set; }
        public virtual ICollection<SysRoleMenu> SysRoleMenu { get; set; }
        public virtual ICollection<SysRoleUser> SysRoleUser { get; set; }
    }
}