// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysRoleData
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string BusiNo { get; set; }
        public int ObjectId { get; set; }
        public string ObjectNo { get; set; }
        public string ObjectName { get; set; }

        public virtual SysRole MidNavigation { get; set; }
    }
}