// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysRoleMenu
 : Entity<int>    {
        public SysRoleMenu()
        {
            SysRoleMenuActions = new HashSet<SysRoleMenuActions>();
        }

        
        public int Mid { get; set; }
        public string MenuNo { get; set; }
        public int? IView { get; set; }
        public bool? IAdd { get; set; }
        public int? IEdit { get; set; }
        public int? IDelete { get; set; }
        public bool? IPrint { get; set; }
        public bool? IExport { get; set; }
        public bool? IProperty { get; set; }
        public int? ISubmit { get; set; }
        public int? IunSubmit { get; set; }
        public int? IAudit { get; set; }
        public int? IunAudit { get; set; }
        public int? IViewAudit { get; set; }
        public int? IClose { get; set; }
        public int? IunClose { get; set; }

        public virtual SysRole MidNavigation { get; set; }
        public virtual ICollection<SysRoleMenuActions> SysRoleMenuActions { get; set; }
    }
}