// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysRoleField
 : Entity<int>    {
        
        public int Mid { get; set; }
        public int Type { get; set; }
        public string BusiNo { get; set; }
        public string FieldName { get; set; }
        public bool Visible { get; set; }
        public bool Editable { get; set; }

        public virtual SysRole MidNavigation { get; set; }
    }
}