// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysSummaryReporttemplate
 : Entity<int>    {
        
        public string BusiNo { get; set; }
        public string Category { get; set; }
        public int UserId { get; set; }
        public Guid ViewData { get; set; }
        public bool IsDefault { get; set; }
        public string Remark { get; set; }
    }
}