// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysTerminalItems
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string Rem { get; set; }
        public string StationName { get; set; }
        public string StationNo { get; set; }
        public string TmName { get; set; }
        public string TmNo { get; set; }

        public virtual SysTerminal MidNavigation { get; set; }
    }
}