// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysUpdateLog
 : Entity<int>    {
        public string Id { get; set; }
        public string Busino { get; set; }
        public string Tablename { get; set; }
        public int? Updid { get; set; }
        public int? Delid { get; set; }
        public int? Insid { get; set; }
        public DateTime? Time { get; set; }
    }
}