// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysUser
 : Entity<int>    {
        public SysUser()
        {
            SysRoleUser = new HashSet<SysRoleUser>();
        }

        
        public int ParentId { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public int? EmpId { get; set; }
        public int? DeptId { get; set; }
        public int UserType { get; set; }
        public bool IsLock { get; set; }
        public string Remark { get; set; }
        public DateTime DInputDate { get; set; }
        public string Dep { get; set; }
        public string CardNo { get; set; }
        public string EMail { get; set; }
        public string Sex { get; set; }
        public bool? Logon { get; set; }
        public string Wechat { get; set; }
        public string EngName { get; set; }
        public string WorkGroup { get; set; }
        public string Superior { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<SysRoleUser> SysRoleUser { get; set; }
    }
}