// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysUniqueset
 : Entity<int>    {
        
        public string BusiNo { get; set; }
        public string GroupNo { get; set; }
        public string FieldName { get; set; }
        public string Memo { get; set; }
    }
}