// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class SysWarning
 : Entity<int>    {
        
        public string No { get; set; }
        public string Name { get; set; }
        public string WarningSql { get; set; }
        public int ItemCount { get; set; }
        public string Memo { get; set; }
        public int UserId { get; set; }
        public DateTime InputDate { get; set; }
        public int Flag { get; set; }
        public int Knd { get; set; }
    }
}