// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Tasks
 : Entity<int>    {
        
        public string CasNo { get; set; }
        public int TaskId { get; set; }
        public int? Up { get; set; }
        public int? SqItm { get; set; }
        public string Name { get; set; }
        public string PeriodId { get; set; }
        public DateTime? StartDd { get; set; }
        public DateTime? EndDd { get; set; }
        public DateTime? RestrictDd { get; set; }
        public DateTime? DoneDd { get; set; }
        public string Type { get; set; }
        public string MileId { get; set; }
        public string Rem { get; set; }
        public string Priority { get; set; }
        public decimal? Duration { get; set; }
        public decimal? DurInput { get; set; }
        public string ClsId { get; set; }
        public string PrStatus { get; set; }
        public string Usr { get; set; }
        public string RunUsr { get; set; }
        public string QcUsr { get; set; }
        public string DelegateId { get; set; }
        public string Wbs { get; set; }
        public short? LayerNum { get; set; }
        public string UpdatingId { get; set; }
        public string DurKey { get; set; }
        public string IdxNo { get; set; }
        public string GanttId { get; set; }
        public string DenyId { get; set; }
        public short? WorkCnt { get; set; }
        public string SumId { get; set; }
        public string Status { get; set; }
        public int? UpPeriod { get; set; }
        public string ClsMan { get; set; }
        public string PrdNo { get; set; }
        public string CusNo { get; set; }
        public string OsName { get; set; }
        public string Pgm { get; set; }
        public DateTime? TaskDd { get; set; }
        public string Dep { get; set; }
        public string SalNo { get; set; }
        public string TaskNo { get; set; }
        public string ChkMan { get; set; }
        public DateTime? ClsDate { get; set; }
        public string PmtIdYr { get; set; }
        public decimal? AmtnActYr { get; set; }
        public decimal? RtnRtoYr { get; set; }
        public decimal? PayRtoYr { get; set; }
        public decimal? BizRtoYr { get; set; }
        public string MobId { get; set; }
        public string PrtSw { get; set; }
        public string UpDefChk { get; set; }
        public string TaskNoCopy { get; set; }
        public string EpNo { get; set; }
        public string LockMan { get; set; }
        public DateTime? LockDate { get; set; }
        public string ChkFl { get; set; }
        public DateTime? SysDate { get; set; }
    }
}