// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbJobbooking
 : Entity<int>    {
        public DateTime? Inputdate { get; set; }
        public string Ban { get; set; }
        public string Bangroup { get; set; }
        public string Equipmentcode { get; set; }
        public string Equipmentname { get; set; }
        public string Productcode { get; set; }
        public string Productname { get; set; }
        public string Mould { get; set; }
        public int? Diecastnumber { get; set; }
        public int? Wastenumber { get; set; }
        public int? Qualifiednumber { get; set; }
        public int? Noqualifiednumber { get; set; }
        public int? Upnumber { get; set; }
        public int? Downnumber { get; set; }
        public int? Totalnumber { get; set; }
        public int? Datasource { get; set; }
        public string Creator { get; set; }
        public DateTime? Createdate { get; set; }
        public string Modifyuser { get; set; }
        public DateTime? Modifydate { get; set; }
        
        public string Workshopno { get; set; }
        public string Workshop { get; set; }
        public string Zcno { get; set; }
        public string Zcname { get; set; }
        public string BanNo { get; set; }
        public string Spec { get; set; }
        public string Producestatus { get; set; }
    }
}