// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbOeeCq
 : Entity<int>    {
        
        public DateTime? StatDate { get; set; }
        public string BanNo { get; set; }
        public string SebNo { get; set; }
        public decimal? Item1 { get; set; }
        public decimal? Item2 { get; set; }
        public decimal? Item3 { get; set; }
        public decimal? Item4 { get; set; }
        public decimal? Item5 { get; set; }
        public long? Totaltime { get; set; }
        public long? Losstime { get; set; }
        public decimal? Value { get; set; }
        public string Oee { get; set; }
        public DateTime? Createtime { get; set; }
        public string Jxname { get; set; }
        public decimal? Item6 { get; set; }
        public decimal? Item7 { get; set; }
        public decimal? Item8 { get; set; }
        public byte? Handletype { get; set; }
    }
}