// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbRate
 : Entity<int>    {
        public string SebNo { get; set; }
        public string BanNo { get; set; }
        public DateTime? SysDate { get; set; }
        public decimal? Rate { get; set; }
        public string Type { get; set; }
        public long Id { get; set; }
    }
}