// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbSbrecordCameraMap
 : Entity<int>    {
        public long Id { get; set; }
        public long? SbrecordId { get; set; }
        public long? CameraQrcode { get; set; }
        public string CameraSj { get; set; }
        public string CameraSbbh { get; set; }
    }
}