// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbSzdata
 : Entity<int>    {
        public DateTime? StatDate { get; set; }
        public string BanNo { get; set; }
        public string Cjbh { get; set; }
        public string Cjmc { get; set; }
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public int? Xjs { get; set; }
        public int? Sjs { get; set; }
        public int? Zgs { get; set; }
        public int? Zjzs { get; set; }
        public int? Xjfps { get; set; }
        public int? Hgs { get; set; }
    }
}