// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbSzbhzCq
 : Entity<int>    {
        
        public string StatDate { get; set; }
        public string BanNo { get; set; }
        public string SebNo { get; set; }
        public string Csbh { get; set; }
        public int? Startvalue { get; set; }
        public int? Endvalue { get; set; }
        public int? Beyondcount { get; set; }
        public int? Value { get; set; }
        public int? Handletype { get; set; }
        public DateTime? Createtime { get; set; }
        public string PrdNo { get; set; }
        public int? PrdTime { get; set; }
        public string StaTime { get; set; }
        public string EndTime { get; set; }
    }
}