// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbSzbDaystatisticlog
 : Entity<int>    {
        public string Logid { get; set; }
        public string Phase { get; set; }
        public DateTime? Executebegin { get; set; }
        public DateTime? Executeend { get; set; }
    }
}