// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbXrayhgl
 : Entity<int>    {
        public string Dayno { get; set; }
        public string Item { get; set; }
        public string Value { get; set; }
    }
}