// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbXrayZb
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string Defecttype { get; set; }
        public int? Defectnumber { get; set; }
    }
}