// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TbXray
 : Entity<int>    {
        public DateTime? Inputdate { get; set; }
        public string Ban { get; set; }
        public string Bangroup { get; set; }
        public string Equipment { get; set; }
        public string Productcode { get; set; }
        public string Productname { get; set; }
        public string Mould { get; set; }
        public string Productspec { get; set; }
        public int? Qualifiednumber { get; set; }
        public int? Noqualifiednumber { get; set; }
        public int? Checktotal { get; set; }
        public string Producestatus { get; set; }
        public string Creator { get; set; }
        public DateTime? Createdate { get; set; }
        public string Modifyuser { get; set; }
        public DateTime? Modifydate { get; set; }
        
        public string Equipmentno { get; set; }
        public int? Midhubdefect { get; set; }
        public int? Spokedefect { get; set; }
        public int? Rimdefect { get; set; }
        public string BanNo { get; set; }
    }
}