// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfBan
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string BanNo { get; set; }
        public int RngItm { get; set; }
        public string StrTime1 { get; set; }
        public string StrTime2 { get; set; }
        public string StrTime3 { get; set; }
        public string StrTime4 { get; set; }
        public string StrTime5 { get; set; }
        public string StrTime6 { get; set; }
        public string StrTime7 { get; set; }
        public string RngName { get; set; }
        public string IoId { get; set; }
        public short? OverMin { get; set; }
        public bool? KqId { get; set; }
        public bool? CardId { get; set; }
        public short? VldMin { get; set; }

        public virtual MfBan MidNavigation { get; set; }
    }
}