// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfGrS
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string GrId { get; set; }
        public string GrNo { get; set; }
        public int Itm { get; set; }
        public DateTime? GrDd { get; set; }
        public string SebNo { get; set; }
        public int? ItmSb { get; set; }
        public string Ut { get; set; }
        public string SalNoBg { get; set; }
        public string DepUse { get; set; }
        public string Name { get; set; }
        public decimal? AmtnNet { get; set; }
        public decimal? TaxRto { get; set; }
        public decimal? Tax { get; set; }
        public decimal? Amt { get; set; }
        public decimal? Amtn { get; set; }
        public DateTime? OpnDd { get; set; }
        public string ExpNo { get; set; }
        public string EpNo { get; set; }
        public string Rem { get; set; }
        public string ToOth { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public int? BilPreItm { get; set; }
        public string Mark { get; set; }
        public decimal? AmtFp { get; set; }
        public decimal? AmtnNetFp { get; set; }
        public decimal? TaxFp { get; set; }
        public decimal? QtyFp { get; set; }
        public string BackId { get; set; }
        public int? PreItm { get; set; }
        public string FxName { get; set; }
        public string FxKnd { get; set; }
        public string FxSpc { get; set; }
        public string Adr { get; set; }
        public string ShareMth { get; set; }
        public short? UseYears { get; set; }
        public decimal? ShareRest { get; set; }
        public string YtNo { get; set; }
        public decimal? Qty1Fp { get; set; }

        public virtual MfGrS MidNavigation { get; set; }
    }
}