// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfJj
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public string ZcNo { get; set; }
        public string BomNo { get; set; }
        public string SebNo { get; set; }
        public string Ygxz { get; set; }
        public DateTime UpDd { get; set; }
        public int Itm { get; set; }
        public decimal? Qty { get; set; }
        public decimal? AmtnUnit { get; set; }
        public decimal? UpUnit { get; set; }
        public decimal? AmtnBonu { get; set; }
        public decimal? AmtnKc { get; set; }
        public string Rem { get; set; }

        public virtual MfJj MidNavigation { get; set; }
    }
}