// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMdInout
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string ModNo { get; set; }
        public string Wh { get; set; }
        public string StorageNo { get; set; }
        public string ModStgState { get; set; }
        public string ModUseState { get; set; }

        public virtual MfMdInout MidNavigation { get; set; }
    }
}