// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMm0
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string MmId { get; set; }
        public string MmNo { get; set; }
        public int Itm { get; set; }
        public DateTime? MmDd { get; set; }
        public string MoNo { get; set; }
        public string TwNo { get; set; }
        public string SoNo { get; set; }
        public string CusOsNo { get; set; }
        public string Dep { get; set; }
        public string BatNo { get; set; }
        public string PrdNo { get; set; }
        public string IdNo { get; set; }
        public string PrdMark { get; set; }
        public string PrdName { get; set; }
        public string Unit { get; set; }
        public string Wh { get; set; }
        public DateTime? ValidDd { get; set; }
        public string FreeId { get; set; }
        public int? PreItm { get; set; }
        public int? EstItm { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? QtyRtn { get; set; }
        public decimal? QtySa { get; set; }
        public decimal? AmtnVal { get; set; }
        public decimal? CstMake { get; set; }
        public decimal? CstPrd { get; set; }
        public decimal? CstOut { get; set; }
        public decimal? CstMan { get; set; }
        public decimal? Cst { get; set; }
        public decimal? UsedTime { get; set; }
        public decimal? TimeCnt { get; set; }
        public decimal? CstSmake { get; set; }
        public decimal? CstSprd { get; set; }
        public decimal? CstSout { get; set; }
        public decimal? CstSman { get; set; }
        public decimal? CstStd { get; set; }
        public decimal? UsedStime { get; set; }
        public decimal? TimeScnt { get; set; }
        public string OldMmId { get; set; }
        public string OldMmNo { get; set; }
        public int? MmItm { get; set; }
        public string CalcId { get; set; }
        public string ZcFlag { get; set; }
        public string CnttNo { get; set; }
        public string CasNo { get; set; }
        public int? TaskId { get; set; }
        public DateTime? RkDd { get; set; }
        public string DepRk { get; set; }
        public string Rem { get; set; }
        public string MlNo { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public int? BilItm { get; set; }
        public string QcFlag { get; set; }
        public decimal? UpMain { get; set; }
        public decimal? UpStd { get; set; }
        public decimal? CstIfrs { get; set; }
        public decimal? CstManIfrs { get; set; }
        public decimal? CstMakIfrs { get; set; }
        public decimal? CstPrdIfrs { get; set; }
        public decimal? CstOutIfrs { get; set; }
        public decimal? CstStdIfrs { get; set; }
        public decimal? CstSmanIfrs { get; set; }
        public decimal? CstSmakIfrs { get; set; }
        public decimal? CstSprdIfrs { get; set; }
        public decimal? CstSoutIfrs { get; set; }
        public string GoWr { get; set; }
        public decimal? UpMainIfrs { get; set; }
        public decimal? UpStdIfrs { get; set; }
        public string DcQtylost { get; set; }
        public string FcpTypeis1 { get; set; }
        public string FcpTypeis2 { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? Qty1Lost { get; set; }
        public DateTime? ScDd { get; set; }

        public virtual MfMm0 MidNavigation { get; set; }
    }
}