// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMmjh
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string JhNo { get; set; }
        public int Itm { get; set; }
        public DateTime? JhDd { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public string PrdName { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? QtyPt { get; set; }
        public DateTime? EstDd { get; set; }
        public string BatNo { get; set; }
        public string Rem { get; set; }
        public string IdNo { get; set; }
        public string PfNo { get; set; }
        public decimal? Qty1 { get; set; }
        public int? EstItm { get; set; }
        public string SupPrdNo { get; set; }

        public virtual MfMmjh MidNavigation { get; set; }
    }
}