// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMo
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string MoNo { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? QtyRsv { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? Qty { get; set; }
        public string BatNo { get; set; }
        public string Rem { get; set; }
        public decimal? Cst { get; set; }
        public string ZcNo { get; set; }
        public bool? TwId { get; set; }
        public string UseinNo { get; set; }
        public string PrdNoChg { get; set; }
        public decimal? Qty1Rsv { get; set; }
        public string IdNo { get; set; }
        public decimal? QtyTs { get; set; }
        public decimal? QtyTsUnsh { get; set; }
        public int? TsItm { get; set; }
        public int? EstItm { get; set; }
        public int? PreItm { get; set; }
        public decimal? LosRto { get; set; }
        public decimal? QtyStd { get; set; }
        public string SebNo { get; set; }
        public string GrpNo { get; set; }
        public string ZcPrd { get; set; }
        public string ChgRto { get; set; }
        public int? ChgItm { get; set; }
        public decimal? QtyChgRto { get; set; }
        public decimal? QtyQl { get; set; }
        public decimal? QtyQlUnsh { get; set; }
        public decimal? QtyDm { get; set; }
        public decimal? QtyDmUnsh { get; set; }
        public decimal? Qty1Dm { get; set; }
        public decimal? QtyBl { get; set; }
        public decimal? CstMl { get; set; }
        public decimal? CstMan { get; set; }
        public decimal? CstMak { get; set; }
        public decimal? CstPrd { get; set; }
        public decimal? CstOut { get; set; }
        public decimal? QtyBom { get; set; }
        public string QcFlag { get; set; }
        public decimal? QtyBlUnsh { get; set; }
        public decimal? QtyBas { get; set; }

        public virtual MfMo MidNavigation { get; set; }
    }
}