// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMp3
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string MpNo { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? Up { get; set; }
        public decimal? Cst { get; set; }
        public decimal? UpSo { get; set; }
        public decimal? AmtnSo { get; set; }
        public string SoNo { get; set; }
        public DateTime? EstDd { get; set; }
        public string BatNo { get; set; }
        public string Rem { get; set; }
        public string MoNo { get; set; }
        public decimal? QtyAd { get; set; }
        public decimal? QtyMo { get; set; }
        public DateTime? StaDd { get; set; }
        public DateTime? EndDd { get; set; }
        public string Dep { get; set; }
        public string MoNoAdd { get; set; }
        public string CpySw { get; set; }
        public string CusNo { get; set; }
        public bool? TwId { get; set; }
        public int? EstItm { get; set; }
        public string CurId { get; set; }
        public decimal? AmtTw { get; set; }
        public decimal? UpTw { get; set; }
        public string IdNo { get; set; }
        public int? OsItm { get; set; }
        public string CusOsNo { get; set; }
        public string SoId { get; set; }
        public bool? CfId { get; set; }
        public bool? MlByMm { get; set; }
        public string DzId { get; set; }
        public int? Llc { get; set; }
        public bool? Drc { get; set; }
        public string BomNo { get; set; }
        public string CnttNo { get; set; }
        public int? PreItm { get; set; }
        public decimal? QtyAm { get; set; }
        public decimal? UpQty1 { get; set; }
        public decimal? QtyStd { get; set; }
        public decimal? Qty1Am { get; set; }
        public string BilType { get; set; }
        public int? DecItm { get; set; }
        public int? HbItm { get; set; }
        public string DgMoNo { get; set; }
        public string HbId { get; set; }
        public bool? Tflag { get; set; }
    }
}