// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfMp1
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string MpNo { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? Up { get; set; }
        public decimal? QtyMaxSo { get; set; }
        public decimal? QtySo { get; set; }
        public decimal? QtyNon { get; set; }
        public string BatNo { get; set; }
        public string SoNo { get; set; }
        public string Rem { get; set; }
        public DateTime? EstDd { get; set; }
        public decimal? QtyMin { get; set; }
        public decimal? QtyOnWay { get; set; }
        public decimal? QtyOnPrc { get; set; }
        public decimal? QtyOnRsv { get; set; }
        public decimal? QtyOnOdr { get; set; }
        public decimal? QtyLrn { get; set; }
        public decimal? QtyBrw { get; set; }
        public decimal? Qty { get; set; }
        public string CpySw { get; set; }
        public int? EstItm { get; set; }
        public string Number { get; set; }
        public DateTime? StaDd { get; set; }
        public string IdNo { get; set; }
        public string PoYes { get; set; }
        public string EstItmstr { get; set; }
        public decimal? QtyStd { get; set; }
        public decimal? QtyLost { get; set; }
        public string BilId { get; set; }
        public string PrdNo1 { get; set; }
        public string PrdMark1 { get; set; }
        public string EcnId { get; set; }
        public string BomNo { get; set; }
        public int? OsItm { get; set; }
        public decimal? QtyPo { get; set; }
        public string CusOsNo { get; set; }
        public decimal? ChgRto { get; set; }
        public string ZcPrd { get; set; }
        public decimal? QtySq { get; set; }
        public int? Llc { get; set; }
        public decimal? QtyCtl { get; set; }
        public string Drc { get; set; }
        public string CnttNo { get; set; }
        public string ChgId { get; set; }
        public string PrdNoChg { get; set; }
        public string BomNoP { get; set; }
        public decimal? QtySw { get; set; }
        public decimal? QtyQ3 { get; set; }
        public decimal? QtyWx { get; set; }
        public decimal? QtyQ2Yl { get; set; }
        public decimal? QtyWsKc { get; set; }
        public string ChgRtoStr { get; set; }
        public decimal? QtyAdd { get; set; }
        public string MrpNo { get; set; }
        public decimal? QtySqc { get; set; }
        public decimal? QtySqr { get; set; }
        public decimal? QtyJh { get; set; }
    }
}