// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfPromv
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string DepNo { get; set; }
        public string DepName { get; set; }
        public string BarcodeNo { get; set; }
        public string ZcNo { get; set; }
        public string ZcName { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdSpc { get; set; }
        public string BatNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public string Unit { get; set; }
        public string RbillType { get; set; }
        public string RbillNo { get; set; }
        public int Itm { get; set; }

        public virtual MfPromv MidNavigation { get; set; }
    }
}