// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfQyM
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string QyNo { get; set; }
        public int Itm { get; set; }
        public DateTime? QyDd { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string ModNo { get; set; }
        public int? ItmMj { get; set; }
        public string Rem { get; set; }
        public string Wh { get; set; }

        public virtual MfQyM MidNavigation { get; set; }
    }
}