// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfRsc
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string RscNo { get; set; }
        public int Itm { get; set; }
        public DateTime? RscDd { get; set; }
        public string ModNo { get; set; }
        public int? ItmMod { get; set; }
        public decimal? UseHours { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string Wh { get; set; }
        public string Rem { get; set; }
        public int? UseNum { get; set; }

        public virtual MfRsc MidNavigation { get; set; }
    }
}