// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfRxS
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string RxId { get; set; }
        public string RxNo { get; set; }
        public int Itm { get; set; }
        public DateTime? RxDd { get; set; }
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public string SebPart { get; set; }
        public string FaAppearance { get; set; }
        public string WxjContent { get; set; }
        public int? ItmSb { get; set; }
        public string DepRep { get; set; }
        public string Rem { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string FaResson { get; set; }
        public string FaType { get; set; }
        public string Lessons { get; set; }
        public string RsNo { get; set; }
        public string RsDesp { get; set; }

        public virtual MfRxS MidNavigation { get; set; }
    }
}