// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfSojh
 : Entity<int>    {
        public string OsNo { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string BomNo { get; set; }
        public string Wh { get; set; }
        public string Ut { get; set; }
        public string Sup1 { get; set; }
        public decimal? Qty { get; set; }
        public DateTime? OsDd { get; set; }
        public DateTime? EstDd { get; set; }
        public string BatNo { get; set; }
        public string Rem { get; set; }
        public string OsId { get; set; }
        public int? Itm { get; set; }
        public string CusOsNo { get; set; }
        public string Spc { get; set; }
        public string Knd { get; set; }
        public decimal? QtyPo { get; set; }
        public string CusNo { get; set; }
    }
}