// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfSqd
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string SqId { get; set; }
        public string SqNo { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdMark { get; set; }
        public string Spc { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? QtyMl { get; set; }
        public decimal? QtyMlUnsh { get; set; }
        public string Rem { get; set; }
        public int? EstItm { get; set; }
        public int? PreItm { get; set; }
        public decimal? QtyMled { get; set; }
        public decimal? QtyMledUnsh { get; set; }
        public string SpcNo { get; set; }
        public string IdNo { get; set; }
        public string BatNo { get; set; }

        public virtual MfSqd MidNavigation { get; set; }
    }
}