// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfStS
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string StNo { get; set; }
        public int Itm { get; set; }
        public DateTime? StDd { get; set; }
        public string SebNo { get; set; }
        public int? ItmSb { get; set; }
        public string RepNo { get; set; }
        public string ToOth { get; set; }
        public string Rem { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public DateTime? OpnDd { get; set; }

        public virtual MfStS MidNavigation { get; set; }
    }
}