// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfStM
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string StId { get; set; }
        public string StNo { get; set; }
        public int Itm { get; set; }
        public DateTime? StDd { get; set; }
        public string ModNo { get; set; }
        public int? ItmMj { get; set; }
        public string RepNo { get; set; }
        public string Rem { get; set; }
        public string ToOth { get; set; }
        public string Spc { get; set; }
        public DateTime? OpnDd { get; set; }
        public decimal? AmtnBf { get; set; }
        public decimal? AmtnFt { get; set; }
        public string OldStateId { get; set; }

        public virtual MfStM MidNavigation { get; set; }
    }
}