// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfTb
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string TbNo { get; set; }
        public int? Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? Qty1Lost { get; set; }
        public decimal? QtyRtn { get; set; }
        public decimal? QtyRtnUnsh { get; set; }
        public decimal? Up { get; set; }
        public decimal? UpQty1 { get; set; }
        public decimal? UpLost { get; set; }
        public decimal? UpQty1Lost { get; set; }
        public decimal? AmtnNet { get; set; }
        public decimal? Tax { get; set; }
        public decimal? Amt { get; set; }
        public string BatNo { get; set; }
        public string TwNo { get; set; }
        public string MlNo { get; set; }
        public string MmNo { get; set; }
        public string MoNo { get; set; }
        public string Rem { get; set; }
        public string PakUnit { get; set; }
        public decimal? PakExc { get; set; }
        public decimal? PakNw { get; set; }
        public string PakWeightUnit { get; set; }
        public decimal? PakGw { get; set; }
        public decimal? PakMeast { get; set; }
        public string PakMeastUnit { get; set; }
        public string CpySw { get; set; }
        public int? EstItm { get; set; }
        public string TzNo2 { get; set; }
        public string IdNo { get; set; }
        public decimal? RtoTax { get; set; }
        public string ComposeIdno { get; set; }
        public decimal? AmtFp { get; set; }
        public decimal? AmtnNetFp { get; set; }
        public decimal? TaxFp { get; set; }
        public decimal? QtyFp { get; set; }
        public decimal? AmtnEp { get; set; }
        public decimal? AmtnEp1 { get; set; }
        public int? PreItm { get; set; }
        public decimal? RtoEp { get; set; }
        public int? TaskId { get; set; }
        public string SlNo { get; set; }
        public int? SlItm { get; set; }
        public string TwId { get; set; }
        public string CusOsNo { get; set; }
        public decimal? CstStd { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public int? BilItm { get; set; }
        public string QcFlag { get; set; }
        public string ShNoCus { get; set; }
        public DateTime? RkDd { get; set; }
        public DateTime? ValidDd { get; set; }
        public bool? FreeId { get; set; }
        public string DepRk { get; set; }
        public decimal? DisCnt { get; set; }
        public decimal? AmtDisCnt { get; set; }
        public decimal? AmtZgFp { get; set; }
        public decimal? AmtnNetZgFp { get; set; }
        public decimal? TaxZgFp { get; set; }
        public decimal? UpStd { get; set; }
        public decimal? AmtnIfrs { get; set; }
        public decimal? AmtnNetIfrs { get; set; }
        public decimal? AmtnEpIfrs { get; set; }
        public decimal? CstStdIfrs { get; set; }
        public decimal? CstStdMlIfrs { get; set; }
        public decimal? CstSmanIfrs { get; set; }
        public decimal? CstSmakIfrs { get; set; }
        public decimal? CstSprdIfrs { get; set; }
        public decimal? CstSoutIfrs { get; set; }
        public decimal? PakGwN { get; set; }
        public string SupPrdNo { get; set; }
        public string SupPrdMark { get; set; }
        public DateTime? ScDd { get; set; }
        public decimal? TaxIfrs { get; set; }
        public decimal? UpStdIfrs { get; set; }
        public decimal? Qty1Fp { get; set; }
        public string DcQtylost { get; set; }
        public decimal? PakNwN { get; set; }

        public virtual MfTb MidNavigation { get; set; }
    }
}