// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfTy
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string TyId { get; set; }
        public string TyNo { get; set; }
        public int Itm { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public string PrdMark { get; set; }
        public string Wh { get; set; }
        public string Unit { get; set; }
        public decimal? QtyChk { get; set; }
        public decimal? QtyOk { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? QtyRtn { get; set; }
        public string ChkResult { get; set; }
        public string Rem { get; set; }
        public string BilNo { get; set; }
        public string TiNo { get; set; }
        public string BatNo { get; set; }
        public string MoNo { get; set; }
        public string CpySw { get; set; }
        public string SpcNo { get; set; }
        public string PrcId { get; set; }
        public string BuildBil { get; set; }
        public string BuildBilId { get; set; }
        public int? EstItm { get; set; }
        public string MmNo { get; set; }
        public int? PreItm { get; set; }
        public decimal? QtyPre { get; set; }
        public decimal? QtyPreUnsh { get; set; }
        public string ZcNo { get; set; }
        public string IdNo { get; set; }
        public decimal? QcUp { get; set; }
        public decimal? Qty1Chk { get; set; }
        public decimal? Qty1Ok { get; set; }
        public decimal? Qty1Lost { get; set; }
        public string EstBuildBil { get; set; }
        public string FreeId { get; set; }
        public int? CkItm { get; set; }
        public string RkNo { get; set; }
        public string ComposeIdno { get; set; }
        public DateTime? ValidDd { get; set; }
        public string SlNo { get; set; }
        public string TiItm { get; set; }
        public string ShNoCus { get; set; }
        public string AutoMv { get; set; }
        public string MvtoNo { get; set; }
        public decimal? QtyOkRtn { get; set; }
        public decimal? QtyOkRtnUnsh { get; set; }
        public decimal? QtyLostRtn { get; set; }
        public decimal? QtyLostRtnUnsh { get; set; }
        public string MmId { get; set; }
        public string RtnId { get; set; }
        public int? KeyItm { get; set; }
        public string CasNo { get; set; }
        public int? TaskId { get; set; }
        public decimal? UsedTime { get; set; }
        public string GfNo { get; set; }
        public string CusOsNo { get; set; }
        public decimal? Amtn { get; set; }
        public decimal? Up { get; set; }
        public decimal? Tax { get; set; }
        public decimal? TaxRto { get; set; }
        public decimal? Amt { get; set; }
        public string PcNo { get; set; }
        public decimal? QtyQc { get; set; }
        public DateTime? RkDd { get; set; }
        public string DepRk { get; set; }
        public DateTime? ValidDdNew { get; set; }
        public string CnttNo { get; set; }
        public string LsNo { get; set; }
        public decimal? AmtDisCnt { get; set; }
        public DateTime? RechkDd { get; set; }
        public DateTime? ProduDd { get; set; }
        public string FxNo { get; set; }
        public string FxName { get; set; }
        public string QcValueAvg { get; set; }
        public bool? BilFlag { get; set; }

        public virtual MfTy MidNavigation { get; set; }
    }
}