// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfUnqcRecord
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string UnqcType { get; set; }
        public int UnqcQty { get; set; }
        public string UnqcModel { get; set; }
        public string UnqcReason { get; set; }
        public string Rem { get; set; }

        public virtual MfUnqcRecord MidNavigation { get; set; }
    }
}