// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TfWxM
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string WxId { get; set; }
        public string WxNo { get; set; }
        public int Itm { get; set; }
        public DateTime? WxDd { get; set; }
        public DateTime? EDdRep { get; set; }
        public string ModNo { get; set; }
        public int? ItmMj { get; set; }
        public string RepNo { get; set; }
        public DateTime? InwhDd { get; set; }
        public string InwhId { get; set; }
        public string Rem { get; set; }
        public string DepRep { get; set; }
        public string BilId { get; set; }
        public string BilNo { get; set; }
        public string ToOth { get; set; }
        public DateTime? BDdRep { get; set; }
        public decimal? Amtn { get; set; }
        public decimal? Amt { get; set; }
        public string Spc { get; set; }
        public string OldStateId { get; set; }
        public string RsNo { get; set; }
        public string RsDesp { get; set; }

        public virtual MfWxM MidNavigation { get; set; }
    }
}