// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TmpSzb
 : Entity<int>    {
        public string Rq { get; set; }
        public int? Minqty { get; set; }
        public int? Maxqty { get; set; }
        public int? Qty { get; set; }
        public int? Setflag { get; set; }
        public string Ban { get; set; }
    }
}