// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TmpSzbdata
 : Entity<int>    {
        public string Sj { get; set; }
        public string Sbbh { get; set; }
        public string Csbh { get; set; }
        public string Cssz { get; set; }
        public byte? Cszt { get; set; }
        public string BanNo { get; set; }
        public string SysDate { get; set; }
    }
}