// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TomesYplacebar
 : Entity<int>    {
        
        public string BillCodeVch { get; set; }
        public string RbillCodeVch { get; set; }
        public string RbillTypeVch { get; set; }
        public string MasterCodeVch { get; set; }
        public string MasterNameVch { get; set; }
        public string PlaceBarVch { get; set; }
        public string PlaceNameVch { get; set; }
        public string ConIdVch { get; set; }
        public string TrayCodeVch { get; set; }
        public decimal? BarNumDbl { get; set; }
        public string BarCodeVch { get; set; }
        public string LotNoVch { get; set; }
        public string LotSelfNoVch { get; set; }
        public string PlaceBarStatusVch { get; set; }
        public DateTime? OperateDt { get; set; }
    }
}