// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TzSeb
 : Entity<int>    {
        
        public string TzNo { get; set; }
        public string SebNo { get; set; }
        public int Mid { get; set; }
    }
}