// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class TzSpectrumInfo
 : Entity<int>    {
        
        public string SebNo { get; set; }
        public string No { get; set; }
        public DateTime? TzDd { get; set; }
        public string TzNo { get; set; }
        public decimal Value { get; set; }
        public string Lowsybol { get; set; }
        public decimal? NumMin { get; set; }
        public string Upsybol { get; set; }
        public decimal? NumMax { get; set; }
        public string BatNo { get; set; }
        public string Scope { get; set; }
        public bool? Outrng { get; set; }
        public DateTime? Sysdate { get; set; }
        public string ZcNo { get; set; }
        public string QcModel { get; set; }
        public string Typeno { get; set; }
        public DateTime? Impdate { get; set; }
    }
}