// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class UnacceptedProductionHandleSub
 : Entity<int>    {
        public UnacceptedProductionHandleSub()
        {
            UnacceptedProductionHandleSubResult = new HashSet<UnacceptedProductionHandleSubResult>();
        }

        public string BatchNoOrBarcode { get; set; }
        public string DefectNo { get; set; }
        public string DefectPhenomenon { get; set; }
        public string HandleMode { get; set; }
        
        public int? Mid { get; set; }
        public string ProductionNo { get; set; }
        public int? Qty { get; set; }

        public virtual UnacceptedProductionHandle MidNavigation { get; set; }
        public virtual ICollection<UnacceptedProductionHandleSubResult> UnacceptedProductionHandleSubResult { get; set; }
    }
}