// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class UnacceptedProductionHandleSubResult
 : Entity<int>    {
        public string Barcode { get; set; }
        public string Comment { get; set; }
        
        public int? Mid { get; set; }
        public int? Qty { get; set; }
        public string Result { get; set; }
        public bool? Remarketing { get; set; }

        public virtual UnacceptedProductionHandleSub MidNavigation { get; set; }
    }
}