// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VEqptInfo
 : Entity<int>    {
        public string EqptNo { get; set; }
        public string PrmNo { get; set; }
        public string PrmValue { get; set; }
        public DateTime? SysDate { get; set; }
        public string TableName { get; set; }
        public string DatabaseName { get; set; }
        public string SebNo { get; set; }
        public string No { get; set; }
        public string ZcNo { get; set; }
        public string PrmName { get; set; }
    }
}