// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VfixtureBom
 : Entity<int>    {
        public long? Id { get; set; }
        public string FixtureCode { get; set; }
        public string PartCode { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ParentNo { get; set; }
        public int? PartId { get; set; }
    }
}