// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VJlbatno
 : Entity<int>    {
        public string SebNo { get; set; }
        public string BanNo { get; set; }
        public string ZcNo { get; set; }
        public string RlTz { get; set; }
    }
}