// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VLogisticsScheduling
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public string SourceLocation { get; set; }
        public string TargetLocation { get; set; }
        public string Location { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? ShippedQuantity { get; set; }
        public decimal? FinishQuantity { get; set; }
        public DateTime? DeadLineDate { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string Billstatus { get; set; }
        public string Billno { get; set; }
        public string Type { get; set; }
        public string Statusname { get; set; }
        public string Barcodesourcelocation { get; set; }
        public string Barcodesourcelocationname { get; set; }
        public string WoNo { get; set; }
        public int ProductionOrder { get; set; }
        public DateTime? StartDate { get; set; }
        public decimal DeliveryLead { get; set; }
    }
}