// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VmkYgOee
 : Entity<int>    {
        public string TzNo { get; set; }
        public DateTime? Sysdate { get; set; }
        public decimal? LlTotal { get; set; }
        public decimal? QtyOk { get; set; }
        public decimal? QtyLost { get; set; }
        public string ZcNo { get; set; }
        public string SebNo { get; set; }
        public string PrdNo { get; set; }
        public decimal Weight { get; set; }
    }
}