// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VMoldBom
 : Entity<int>    {
        public long? Id { get; set; }
        public string ModNo { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string ParentNo { get; set; }
        public string Type { get; set; }
        public int? Sort { get; set; }
        public int? PartId { get; set; }
    }
}