// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Vmoniseblist
 : Entity<int>    {
        public string WorkShop { get; set; }
        public string SebNo { get; set; }
        public string SebName { get; set; }
        public string ZcName { get; set; }
        public int ZcIdx { get; set; }
    }
}