// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VOnTraySingleTrace
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string Pcode { get; set; }
        public DateTime? Sysdate { get; set; }
        public string Tdcode { get; set; }
        public string PrdNo { get; set; }
        public DateTime? StaTime { get; set; }
        public string PrdName { get; set; }
        public string ZcNo { get; set; }
    }
}