// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VOutForm
 : Entity<int>    {
        
        public int? ItemId { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string No { get; set; }
        public string SourceNo { get; set; }
        public string SourceNoForm { get; set; }
        public string SourceNameForm { get; set; }
        public string TargetNoForm { get; set; }
        public string TargetNameForm { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public string SourceLocation { get; set; }
        public string SourceLocationName { get; set; }
        public string Location { get; set; }
        public string LocationName { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public string ProdSnm { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? FinishQuantity { get; set; }
        public string ProdNo { get; set; }
        public string BatchNo { get; set; }
        public string Unit { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string ItemStatus { get; set; }
    }
}