// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VOutFormApplyItemStorage
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public decimal? Quantity { get; set; }
        public string SourceLocation { get; set; }
        public string Location { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Remark { get; set; }
        public string MasterWareHouseNo { get; set; }
        public decimal AllQty { get; set; }
        public decimal AllFroQty { get; set; }
        public decimal AllCanQty { get; set; }
        public decimal ShippedQuantity { get; set; }
        public string MasterWareHouseName { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public decimal? TurnNum { get; set; }
        public decimal? MaxDeliveryQuantity { get; set; }
        public decimal? MinDeliveryQuantity { get; set; }
        public string OrderNumber { get; set; }
        public string ErporderNumber { get; set; }
    }
}