// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VPackagefeed
 : Entity<int>    {
        public int Mid { get; set; }
        public int? Tid { get; set; }
        public string SebNo { get; set; }
        public string ZcNo { get; set; }
        public string BanNo { get; set; }
        public string MrpNo { get; set; }
        public string MprdName { get; set; }
        public string PrdNo { get; set; }
        public string PrdName { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public string BatNo { get; set; }
        public DateTime? MlDd { get; set; }
    }
}