// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VPickMaterialDetail
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string SourceWareHouseNo { get; set; }
        public string SourceWareHouseName { get; set; }
        public string FormNo { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime? NeedPickMaterialTime { get; set; }
        public DateTime? StartDate { get; set; }
        public int? WorkOrder { get; set; }
        public string AddInfo { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string TargetWareHouseNo { get; set; }
        public string TargetWareHouseName { get; set; }
        public string MprodNo { get; set; }
        public string MprodName { get; set; }
        public string MprodSpc { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public decimal? AvailableStorage { get; set; }
        public decimal? PlanQuantity { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? FinishQuantity { get; set; }
        public decimal? Unfinishedquantity { get; set; }
    }
}