// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VPlso
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string PlanNo { get; set; }
        public int? Item { get; set; }
        public DateTime? PlanDate { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string LayoutNo { get; set; }
        public string Unit { get; set; }
        public decimal? Qty { get; set; }
        public DateTime? ReqDate { get; set; }
        public string VerNo { get; set; }
        public string DeptNo { get; set; }
    }
}