// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VPrdtProcess
 : Entity<int>    {
        
        public string PrdNo { get; set; }
        public string BomNo { get; set; }
        public int? ZcItm { get; set; }
        public string ZcNo { get; set; }
        public string ZcName { get; set; }
        public string SebNo { get; set; }
        public string WorkCenter { get; set; }
        public bool? IsBottleneck { get; set; }
        public long? Idx { get; set; }
    }
}