// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VProductionFeed
 : Entity<int>    {
        public DateTime? MlDd { get; set; }
        public string MlNo { get; set; }
        public string TzNo { get; set; }
        public string MrpNo { get; set; }
        public string PrdNo { get; set; }
        public string BatNo { get; set; }
        public decimal? Qty { get; set; }
    }
}