// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VProcessTraceCode
 : Entity<int>    {
        public long? Id { get; set; }
        public string ProcessTraceCode { get; set; }
        public string DeviceNo { get; set; }
        public string SourceOrder { get; set; }
        public string ProcessNo { get; set; }
        public string ProductNo { get; set; }
        public string ProductionDate { get; set; }
    }
}