// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VQcDataRec
 : Entity<int>    {
        
        public string TraceCode { get; set; }
        public string No { get; set; }
        public long? Itemno { get; set; }
        public string QcItm { get; set; }
        public string QcValue { get; set; }
        public string NumMin { get; set; }
        public string Lowsybol { get; set; }
        public string NumMax { get; set; }
        public string Upsybol { get; set; }
        public string SalNo { get; set; }
        public string PrjName { get; set; }
        public string QcResult { get; set; }
        public DateTime? Sysdate { get; set; }
    }
}