// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VQcPrdMeasureRecord
 : Entity<int>    {
        
        public long? Mid { get; set; }
        public string PartName { get; set; }
        public string Revisionnumber { get; set; }
        public string Serialnumber { get; set; }
        public DateTime? Ddate { get; set; }
        public string Dtime { get; set; }
        public long? Detailid { get; set; }
        public string Dimension { get; set; }
        public string Description { get; set; }
        public string Axis { get; set; }
        public decimal? Meas { get; set; }
    }
}