// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VQmInspectSBatchReview
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string SampleNo { get; set; }
        public string DeviceNo { get; set; }
        public string InspectDevice { get; set; }
        public string ProductNo { get; set; }
        public string InspectType { get; set; }
        public string Result { get; set; }
        public string TraceNo { get; set; }
        public string CastingBatchNo { get; set; }
        public string BillNo { get; set; }
        public string BillStatus { get; set; }
        public DateTime? InspectDate { get; set; }
        public string ProcedureCode { get; set; }
        public string BanNo { get; set; }
        public string DeviceName { get; set; }
        public string TargetDeviceName { get; set; }
        public string TargetDeviceNo { get; set; }
        public string ProcedureName { get; set; }
        public int? IsCheck { get; set; }
        public string IsTransform { get; set; }
        public string AdvanceSampleNo { get; set; }
        public string TzNo { get; set; }
    }
}