// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VQmsio
 : Entity<int>    {
        public string No { get; set; }
        public string ProductNo { get; set; }
        public string SuppCode { get; set; }
        public string BatchNo { get; set; }
        public string PfaNo { get; set; }
        
    }
}