// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VRollBackList
 : Entity<int>    {
        public long? Id { get; set; }
        public string IdNo { get; set; }
        public string TzNo { get; set; }
        public string ZcNo { get; set; }
        public string PcBan { get; set; }
        public string MrpNo { get; set; }
        public string SebNo { get; set; }
        public string MoNo { get; set; }
        public string Unit { get; set; }
        public string BomNo { get; set; }
        public string StationNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? QtyFin { get; set; }
        public decimal? QtyChk { get; set; }
        public decimal? QtyLost { get; set; }
        public decimal? QtyScrap { get; set; }
        public DateTime? OpnDd { get; set; }
    }
}