// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VRosFilterXl
 : Entity<int>    {
        public string BillNo { get; set; }
        public string SourceBillNo { get; set; }
        public string BillStatus { get; set; }
        public int? InspectTc { get; set; }
        public string SuppCode { get; set; }
        public string DeptNo { get; set; }
        public int? SendInspectorId { get; set; }
        public bool? IsCheck { get; set; }
        public string ProductionNo { get; set; }
        public string ProductionName { get; set; }
        public string Spc { get; set; }
        public string Unit { get; set; }
        public string Snm { get; set; }
        public string InspectionType { get; set; }
        public decimal? Siqty { get; set; }
        public string BatchNo { get; set; }
        public string RawMaterialBatch { get; set; }
        public DateTime? ProducedDate { get; set; }
        public DateTime? InspectionDate { get; set; }
        public string Comment { get; set; }
        public decimal? QtyRtn { get; set; }
        public decimal? QtyRck { get; set; }
        public decimal? QtyPs { get; set; }
        public bool? IsSample { get; set; }
        public string BusiNo { get; set; }
        
        public int? Subid { get; set; }
        public string SourceLocation { get; set; }
        public string SourceLocationName { get; set; }
        public string TargetWareHouse { get; set; }
        public string TargetWareHouseName { get; set; }
        public string ViewDetail { get; set; }
        public string CreateAi { get; set; }
        public string CreateInspectionOrder { get; set; }
        public bool? IsEfi { get; set; }
        public string SuppName { get; set; }
        public string SuppSnm { get; set; }
        public DateTime SysDate { get; set; }
        public string UsrName { get; set; }
        public string Asn { get; set; }
        public string StorageLocation { get; set; }
        public decimal? 合格数量 { get; set; }
        public decimal? 让步接收数量 { get; set; }
        public decimal? 厂内检验报废数量 { get; set; }
        public decimal? 供应商检验报废数量 { get; set; }
        public decimal? 退回数量 { get; set; }
        public decimal? 待处置数量 { get; set; }
        public decimal? 报废数量 { get; set; }
    }
}