// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VSafeTyInventoryList
 : Entity<int>    {
        public string WareHouseNo { get; set; }
        public string WarehouseName { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string ProdSnm { get; set; }
        public string ProdSpc { get; set; }
        public string Ut { get; set; }
        public decimal Quantity { get; set; }
        public decimal Minquantity { get; set; }
        public decimal InventoryReplenishment { get; set; }
        public decimal MaxQuantity { get; set; }
    }
}