// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VStorageSummary
 : Entity<int>    {
        
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public string ProdSnm { get; set; }
        public string WareHouseNo { get; set; }
        public string WarehouseName { get; set; }
        public string BatchNo { get; set; }
        public string Unit { get; set; }
        public decimal? Quantity { get; set; }
        public decimal FrozenQuantity { get; set; }
        public decimal FreezeQuantity { get; set; }
        public decimal? AvailableQuantity { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierSnm { get; set; }
    }
}