// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VStorage
 : Entity<int>    {
        public long? Id { get; set; }
        public string Masterwarehouseno { get; set; }
        public string MasterWareHouseName { get; set; }
        public string Location { get; set; }
        public string LocationName { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public string ProdSnm { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierSnm { get; set; }
        public decimal? Quantity { get; set; }
        public decimal FrozenQuantity { get; set; }
        public decimal LockQuantity { get; set; }
        public decimal FreezeQuantity { get; set; }
        public decimal? AvailableQuantity { get; set; }
    }
}