// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VTdcodeBusi
 : Entity<int>    {
        public long? Rn { get; set; }
        
        public string Barcode { get; set; }
        public string PrdNo { get; set; }
        public string ZcNo { get; set; }
        public string TzNo { get; set; }
        public DateTime StaTime { get; set; }
        public string SebNo { get; set; }
        public string CodeStatus { get; set; }
        public string ModName { get; set; }
    }
}