// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VTdCodeBusi1
 : Entity<int>    {
        public string Barcode { get; set; }
        public string PrdNo { get; set; }
        public string CodeStatus { get; set; }
        public DateTime? PassTime { get; set; }
        public string ZcNo { get; set; }
        public string SebNo { get; set; }
        public string TzNo { get; set; }
        public string JhNo { get; set; }
        public string IdNo { get; set; }
        public long? Id { get; set; }
    }
}