// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VWkStationProcess
 : Entity<int>    {
        public string ZcNo { get; set; }
        public string Name { get; set; }
        public string TmNo { get; set; }
        public int? SortIdx { get; set; }
        public long? Id { get; set; }
    }
}