// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VWorkOrderMats
 : Entity<int>    {
        
        public int Mid { get; set; }
        public string WoNo { get; set; }
        public string ProcessNo { get; set; }
        public string ProcessName { get; set; }
        public string WareHouseNo { get; set; }
        public string WareHouseName { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string ProdSpc { get; set; }
        public string ProdSnm { get; set; }
        public decimal? Quantity { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public string Rem { get; set; }
        public string WkCenterNo { get; set; }
        public string WkCenterName { get; set; }
        public DateTime? StartDate { get; set; }
        public int? WorkOrder { get; set; }
        public string AddInfo { get; set; }
    }
}