// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VXlight
 : Entity<int>    {
        
        public string TzNo { get; set; }
        public string MdNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Sm { get; set; }
        public decimal? QtyScrap { get; set; }
        public decimal? QtyChk { get; set; }
        public string Name { get; set; }
        public DateTime? StaTime { get; set; }
        public string Barcode { get; set; }
        public string CodeStatus { get; set; }
    }
}