// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class VZzpcprd
 : Entity<int>    {
        public long? Id { get; set; }
        public string PrdNo { get; set; }
        public string Name { get; set; }
        public string RtoId { get; set; }
        public string SebNo { get; set; }
        public string MoNo { get; set; }
        public string SoNo { get; set; }
        public string IdNo { get; set; }
        public decimal? Jhqty { get; set; }
        public string Knd { get; set; }
        public bool? IsPieceMng { get; set; }
        public string Unit { get; set; }
        public string TzDd { get; set; }
        public string PcBan { get; set; }
        public int? MtItm { get; set; }
        public string BatNo { get; set; }
    }
}