// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WhEntryInfo
 : Entity<int>    {
        public string EntryNo { get; set; }
        public int? EntryType { get; set; }
        public string Inout { get; set; }
        public DateTime? EntDate { get; set; }
        public string EntState { get; set; }
        public string Wh { get; set; }
        public string Billno { get; set; }
        public string Billtype { get; set; }
        public string PartnerNo { get; set; }
        public string ToBilNo { get; set; }
        public string ToBusiNo { get; set; }
        public string CreateUserId { get; set; }
        public string CreateTime { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? UpdateTime { get; set; }
    }
}