// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmAsnItem
 : Entity<int>    {
        public WmAsnItem()
        {
            WmAsnBarcodeInfo = new HashSet<WmAsnBarcodeInfo>();
        }

        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public decimal? Quantity { get; set; }
        public string Location { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Remark { get; set; }
        public decimal? FinishQuantity { get; set; }
        public string SourceNo { get; set; }
        public string Status { get; set; }
        public string MaterialBatchNo { get; set; }
        public decimal? PrintQuantity { get; set; }
        public decimal? RefuseQuantity { get; set; }
        public string TargetWareHouseNo { get; set; }
        public string OrderNo { get; set; }
        public string ItemNo { get; set; }

        public virtual WmAsn MidNavigation { get; set; }
        public virtual ICollection<WmAsnBarcodeInfo> WmAsnBarcodeInfo { get; set; }
    }
}