// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmBarcodeSource
 : Entity<int>    {
        public WmBarcodeSource()
        {
            WmBarcode = new HashSet<WmBarcode>();
        }

        
        public string SrcType { get; set; }
        public string SrcNo { get; set; }
        public string SrcBarcode { get; set; }
        public int? Item { get; set; }
        public string VendorNo { get; set; }
        public string ProdNo { get; set; }
        public string ProdName { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public decimal? Qty { get; set; }
        public decimal? PkgConver { get; set; }
        public decimal? QtyPkg { get; set; }
        public string Dept { get; set; }
        public int? SrcItemId { get; set; }
        public string No { get; set; }
        public DateTime? BillDate { get; set; }
        public string Rem { get; set; }
        public string BusiNo { get; set; }
        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsrName { get; set; }
        public string UpdUsr { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public DateTime? ChkDate { get; set; }
        public bool? IsClose { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public string ChkMob { get; set; }
        public bool? IsPrint { get; set; }
        public string BarcodeType { get; set; }
        public string ProdSpec { get; set; }
        public string MoldNo { get; set; }

        public virtual ICollection<WmBarcode> WmBarcode { get; set; }
    }
}