// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmFormItem
 : Entity<int>    {
        public WmFormItem()
        {
            WmFormBarcodeInfo = new HashSet<WmFormBarcodeInfo>();
        }

        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public decimal? Quantity { get; set; }
        public string Location { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Remark { get; set; }
        public string SourceLocation { get; set; }
        public string Status { get; set; }
        public decimal? FinishQuantity { get; set; }
        public string SourceNo { get; set; }
        public string MaterialBatchNo { get; set; }
        public decimal? ShippedQuantity { get; set; }
        public DateTime? DeadLineDate { get; set; }
        public string SourceLineNumber { get; set; }
        public string WoNo { get; set; }
        public string ErporderNumber { get; set; }
        public string OrderNumber { get; set; }
        public string AcceptanceItemId { get; set; }

        public virtual WmForm MidNavigation { get; set; }
        public virtual ICollection<WmFormBarcodeInfo> WmFormBarcodeInfo { get; set; }
    }
}