// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmInventoryPlanItem
 : Entity<int>    {
        public WmInventoryPlanItem()
        {
            WmInventoryPlanBarcode = new HashSet<WmInventoryPlanBarcode>();
        }

        public decimal? AccountQuantity { get; set; }
        public decimal? ActualQuantity { get; set; }
        
        public decimal? LackQuantity { get; set; }
        public int? Mid { get; set; }
        public decimal? MuchQuantity { get; set; }
        public string ProdNo { get; set; }
        public string Remark { get; set; }
        public string Unit { get; set; }

        public virtual WmInventoryPlan MidNavigation { get; set; }
        public virtual ICollection<WmInventoryPlanBarcode> WmInventoryPlanBarcode { get; set; }
    }
}