// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmOnShelfGuideItem
 : Entity<int>    {
        public WmOnShelfGuideItem()
        {
            WmOnShelfGuideBarcode = new HashSet<WmOnShelfGuideBarcode>();
        }

        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public decimal? PlanQuantity { get; set; }
        public decimal? Quantity { get; set; }
        public string Unit { get; set; }
        public string BatchNo { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string SourceLocation { get; set; }
        public string TargetLocation { get; set; }

        public virtual WmOnShelfGuide MidNavigation { get; set; }
        public virtual ICollection<WmOnShelfGuideBarcode> WmOnShelfGuideBarcode { get; set; }
    }
}