// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmOnShelfGuideRule
 : Entity<int>    {
        public decimal? Capacity { get; set; }
        
        public bool? IsDelete { get; set; }
        public bool? IsSingle { get; set; }
        public string Location { get; set; }
        public string Priority { get; set; }
        public string ProdNo { get; set; }
        public DateTime SysDate { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
    }
}