// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmOrderBarsQty
 : Entity<int>    {
        public string BatchNo { get; set; }
        public DateTime? FeedingTime { get; set; }
        
        public string ProcessNo { get; set; }
        public string ProdNo { get; set; }
        public string ProdNoMat { get; set; }
        public int? Qty { get; set; }
        public int? QtyBars { get; set; }
        public int? QtyPrint { get; set; }
        public string StationNo { get; set; }
        public string Status { get; set; }
        public DateTime SysDate { get; set; }
        public string TraceNo { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string UserExec { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string WoNo { get; set; }
    }
}