// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmOutFormApplyBarcodeInfo
 : Entity<int>    {
        
        public int? Mid { get; set; }
        public string ProdNo { get; set; }
        public string BatchNo { get; set; }
        public string PackageNo { get; set; }
        public decimal? Quantity { get; set; }
        public string Unit { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string SourceLocation { get; set; }
        public string Location { get; set; }

        public virtual WmOutFormApplyItem MidNavigation { get; set; }
    }
}