// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmPackageBom
 : Entity<int>    {
        public WmPackageBom()
        {
            WmPackageBomItems = new HashSet<WmPackageBomItems>();
        }

        public string BilType { get; set; }
        public string BilTypeName { get; set; }
        public string BomNo { get; set; }
        public string BomNoSub { get; set; }
        public string BusiNo { get; set; }
        public DateTime? ChkDate { get; set; }
        public string ChkMan { get; set; }
        public string ChkManName { get; set; }
        public string ChkMob { get; set; }
        public DateTime? ClsDate { get; set; }
        public string ClsUsr { get; set; }
        public string ClsUsrName { get; set; }
        public DateTime? EffectiveDate { get; set; }
        
        public bool? IsClose { get; set; }
        public bool? IsPrint { get; set; }
        public string PkgSn { get; set; }
        public string PkgSnSub { get; set; }
        public string PkgType { get; set; }
        public string PkgTypeSub { get; set; }
        public string ProdName { get; set; }
        public string ProdNo { get; set; }
        public string ProdSpec { get; set; }
        public string ProdType { get; set; }
        public int? Qty { get; set; }
        public int? QtySub { get; set; }
        public string Rem { get; set; }
        public DateTime SysDate { get; set; }
        public string Unit { get; set; }
        public DateTime? UpdDate { get; set; }
        public string UpdUsr { get; set; }
        public string UpdUsrName { get; set; }
        public string Usr { get; set; }
        public string UsrName { get; set; }
        public string VerNo { get; set; }
        public bool? IsSmallestPackage { get; set; }

        public virtual ICollection<WmPackageBomItems> WmPackageBomItems { get; set; }
    }
}