// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmPackageBomItems
 : Entity<int>    {
        public string BomNo { get; set; }
        
        public int? Item { get; set; }
        public int Mid { get; set; }
        public string ProdName { get; set; }
        public string ProdNo { get; set; }
        public string ProdSpec { get; set; }
        public decimal? Qty { get; set; }
        public string Unit { get; set; }
        public string WhseNo { get; set; }

        public virtual WmPackageBom MidNavigation { get; set; }
    }
}