// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class WmStock
 : Entity<int>    {
        
        public string FactoryNo { get; set; }
        public string WarehouseNo { get; set; }
        public string MaterialNo { get; set; }
        public decimal Quantity { get; set; }
        public string BatchNo { get; set; }
        public string IsDelete { get; set; }
        public DateTime? UpdateTime { get; set; }
    }
}