// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

using Volo.Abp.Domain.Entities;

namespace FarVision.Mes
{
    public partial class Ychj
 : Entity<int>    {
        public int 序号 { get; set; }
        public DateTime? 日期 { get; set; }
        public string 时间 { get; set; }
        public string 标识号 { get; set; }
        public string 炉号 { get; set; }
        public string 班号 { get; set; }
        public decimal? FeMn { get; set; }
        public decimal? FeS { get; set; }
        public decimal? FeCr { get; set; }
        public decimal? C { get; set; }
        public decimal? B1 { get; set; }
    }
}