using Microsoft.EntityFrameworkCore;
using FarVision.Mes.Users;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore.Modeling;
using Volo.Abp.Identity;
using Volo.Abp.Users.EntityFrameworkCore;

namespace FarVision.Mes.EntityFrameworkCore
{
    /* This is your actual DbContext used on runtime.
     * It includes only your entities.
     * It does not include entities of the used modules, because each module has already
     * its own DbContext class. If you want to share some database tables with the used modules,
     * just create a structure like done for AppUser.
     *
     * Don't use this DbContext for database migrations since it does not contain tables of the
     * used modules (as explained above). See MesMigrationsDbContext for migrations.
     */
    [ConnectionStringName("Default")]
    public class MesDbContext : AbpDbContext<MesDbContext>
    {
        public DbSet<AppUser> Users { get; set; }

        /* Add DbSet properties for your Aggregate Roots / Entities here.
         * Also map them inside MesDbContextModelCreatingExtensions.ConfigureMes
         */

        public MesDbContext(DbContextOptions<MesDbContext> options)
            : base(options)
        {

        }

        public virtual DbSet<Accn> Accn { get; set; }
        public virtual DbSet<Actualdcr> Actualdcr { get; set; }
        public virtual DbSet<Actualpara> Actualpara { get; set; }
        public virtual DbSet<Aifilter> Aifilter { get; set; }
        public virtual DbSet<AlertMessageHisT> AlertMessageHisT { get; set; }
        public virtual DbSet<AlertMessageT> AlertMessageT { get; set; }
        public virtual DbSet<AlertPdpara> AlertPdpara { get; set; }
        public virtual DbSet<AlertRulesT> AlertRulesT { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Baclose> Baclose { get; set; }
        public virtual DbSet<Bacomp> Bacomp { get; set; }
        public virtual DbSet<BarcodeProductMap> BarcodeProductMap { get; set; }
        public virtual DbSet<BatNo> BatNo { get; set; }
        public virtual DbSet<BatRec1> BatRec1 { get; set; }
        public virtual DbSet<BatchgRec> BatchgRec { get; set; }
        public virtual DbSet<BfBusiFieldC> BfBusiFieldC { get; set; }
        public virtual DbSet<BfDataHistory> BfDataHistory { get; set; }
        public virtual DbSet<BfFieldSelectList> BfFieldSelectList { get; set; }
        public virtual DbSet<BfFilter> BfFilter { get; set; }
        public virtual DbSet<BfLayout> BfLayout { get; set; }
        public virtual DbSet<BfRptTempletC> BfRptTempletC { get; set; }
        public virtual DbSet<BfRptTempletS> BfRptTempletS { get; set; }
        public virtual DbSet<BfRptTemplets1> BfRptTemplets1 { get; set; }
        public virtual DbSet<BilSpc> BilSpc { get; set; }
        public virtual DbSet<Billbase> Billbase { get; set; }
        public virtual DbSet<BlobTemp> BlobTemp { get; set; }
        public virtual DbSet<CallInfo> CallInfo { get; set; }
        public virtual DbSet<Calltype> Calltype { get; set; }
        public virtual DbSet<CameraSebMap> CameraSebMap { get; set; }
        public virtual DbSet<Casn> Casn { get; set; }
        public virtual DbSet<Ceshi> Ceshi { get; set; }
        public virtual DbSet<CmmMeasureRec> CmmMeasureRec { get; set; }
        public virtual DbSet<CmmMeasureRecItem> CmmMeasureRecItem { get; set; }
        public virtual DbSet<CnttSgt> CnttSgt { get; set; }
        public virtual DbSet<Combitable> Combitable { get; set; }
        public virtual DbSet<CsiTemp> CsiTemp { get; set; }
        public virtual DbSet<CurId> CurId { get; set; }
        public virtual DbSet<CusBox> CusBox { get; set; }
        public virtual DbSet<CusWh> CusWh { get; set; }
        public virtual DbSet<Cust> Cust { get; set; }
        public virtual DbSet<CycleTime> CycleTime { get; set; }
        public virtual DbSet<Database> Database { get; set; }
        public virtual DbSet<DcCsRecord> DcCsRecord { get; set; }
        public virtual DbSet<Dcrresult> Dcrresult { get; set; }
        public virtual DbSet<DctDevice> DctDevice { get; set; }
        public virtual DbSet<DctDeviceAlarm> DctDeviceAlarm { get; set; }
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<DeviceShift> DeviceShift { get; set; }
        public virtual DbSet<DieChangeInfos> DieChangeInfos { get; set; }
        public virtual DbSet<DncAlarmRec> DncAlarmRec { get; set; }
        public virtual DbSet<DncProcessParasRec> DncProcessParasRec { get; set; }
        public virtual DbSet<DncTtlT> DncTtlT { get; set; }
        public virtual DbSet<EqpAlertTrace> EqpAlertTrace { get; set; }
        public virtual DbSet<EqpDeviceWarning> EqpDeviceWarning { get; set; }
        public virtual DbSet<EqpMaintainPlan> EqpMaintainPlan { get; set; }
        public virtual DbSet<EqpMaintainSpec> EqpMaintainSpec { get; set; }
        public virtual DbSet<EqpMtOrder> EqpMtOrder { get; set; }
        public virtual DbSet<EqpMtRunTime> EqpMtRunTime { get; set; }
        public virtual DbSet<EqpMtorderInfo> EqpMtorderInfo { get; set; }
        public virtual DbSet<EqpMtspecInfo> EqpMtspecInfo { get; set; }
        public virtual DbSet<EqpPartChangeRecord> EqpPartChangeRecord { get; set; }
        public virtual DbSet<EqpPartInfo> EqpPartInfo { get; set; }
        public virtual DbSet<EqpRunRecord> EqpRunRecord { get; set; }
        public virtual DbSet<EqpRunStatus> EqpRunStatus { get; set; }
        public virtual DbSet<EqpRunStatusDef> EqpRunStatusDef { get; set; }
        public virtual DbSet<EqpSparePart> EqpSparePart { get; set; }
        public virtual DbSet<EqptInfoEa2113> EqptInfoEa2113 { get; set; }
        public virtual DbSet<EvnNo> EvnNo { get; set; }
        public virtual DbSet<EvnParmInfo> EvnParmInfo { get; set; }
        public virtual DbSet<EvnParmRecord> EvnParmRecord { get; set; }
        public virtual DbSet<EvnParmRecordValue> EvnParmRecordValue { get; set; }
        public virtual DbSet<ExImpTemp> ExImpTemp { get; set; }
        public virtual DbSet<FaultCause> FaultCause { get; set; }
        public virtual DbSet<Fieldstable> Fieldstable { get; set; }
        public virtual DbSet<Fifoincludelist> Fifoincludelist { get; set; }
        public virtual DbSet<Filedstable> Filedstable { get; set; }
        public virtual DbSet<FixtureRlosp> FixtureRlosp { get; set; }
        public virtual DbSet<FlowCheck> FlowCheck { get; set; }
        public virtual DbSet<FrXt> FrXt { get; set; }
        public virtual DbSet<FurnaceBinding> FurnaceBinding { get; set; }
        public virtual DbSet<FxKnd> FxKnd { get; set; }
        public virtual DbSet<GxOtherItems> GxOtherItems { get; set; }
        public virtual DbSet<GxOtherMain> GxOtherMain { get; set; }
        public virtual DbSet<HfplRec> HfplRec { get; set; }
        public virtual DbSet<HfplRecs> HfplRecs { get; set; }
        public virtual DbSet<Indx> Indx { get; set; }
        public virtual DbSet<Indx1> Indx1 { get; set; }
        public virtual DbSet<InspectItemsList> InspectItemsList { get; set; }
        public virtual DbSet<Jhtp2Temp> Jhtp2Temp { get; set; }
        public virtual DbSet<JhtpTemp> JhtpTemp { get; set; }
        public virtual DbSet<LblSupqc> LblSupqc { get; set; }
        public virtual DbSet<LblSupqcBars> LblSupqcBars { get; set; }
        public virtual DbSet<LeLogisticsTasks> LeLogisticsTasks { get; set; }
        public virtual DbSet<LeLogisticsTasksHistory> LeLogisticsTasksHistory { get; set; }
        public virtual DbSet<LeLogisticsTasksItem> LeLogisticsTasksItem { get; set; }
        public virtual DbSet<LeTestItems> LeTestItems { get; set; }
        public virtual DbSet<LeTestMain> LeTestMain { get; set; }
        public virtual DbSet<LsbYzjMap> LsbYzjMap { get; set; }
        public virtual DbSet<Major> Major { get; set; }
        public virtual DbSet<MdSpInfo> MdSpInfo { get; set; }
        public virtual DbSet<MdmAqlsample> MdmAqlsample { get; set; }
        public virtual DbSet<MdmAttribute> MdmAttribute { get; set; }
        public virtual DbSet<MdmAttributeValue> MdmAttributeValue { get; set; }
        public virtual DbSet<MdmBom> MdmBom { get; set; }
        public virtual DbSet<MdmBomdetail> MdmBomdetail { get; set; }
        public virtual DbSet<MdmCustomer> MdmCustomer { get; set; }
        public virtual DbSet<MdmCycleTime> MdmCycleTime { get; set; }
        public virtual DbSet<MdmFixtureFaultBom> MdmFixtureFaultBom { get; set; }
        public virtual DbSet<MdmFixtureFaultBomdetail> MdmFixtureFaultBomdetail { get; set; }
        public virtual DbSet<MdmFixtureFaultCause> MdmFixtureFaultCause { get; set; }
        public virtual DbSet<MdmFixtureFaultPhenomenon> MdmFixtureFaultPhenomenon { get; set; }
        public virtual DbSet<MdmFormAttribute> MdmFormAttribute { get; set; }
        public virtual DbSet<MdmLayout> MdmLayout { get; set; }
        public virtual DbSet<MdmMaterial> MdmMaterial { get; set; }
        public virtual DbSet<MdmParameterType> MdmParameterType { get; set; }
        public virtual DbSet<MdmPqip> MdmPqip { get; set; }
        public virtual DbSet<MdmProcessBom> MdmProcessBom { get; set; }
        public virtual DbSet<MdmProcessProductMap> MdmProcessProductMap { get; set; }
        public virtual DbSet<MdmProdCapacity> MdmProdCapacity { get; set; }
        public virtual DbSet<MdmSpotCheckSchedule> MdmSpotCheckSchedule { get; set; }
        public virtual DbSet<MdmSupplier> MdmSupplier { get; set; }
        public virtual DbSet<MdmWareHouse> MdmWareHouse { get; set; }
        public virtual DbSet<MdmWorkCenter> MdmWorkCenter { get; set; }
        public virtual DbSet<MdmWorkCenterMap> MdmWorkCenterMap { get; set; }
        public virtual DbSet<MesDncIntfcT> MesDncIntfcT { get; set; }
        public virtual DbSet<MesJobData> MesJobData { get; set; }
        public virtual DbSet<MesJobInfos> MesJobInfos { get; set; }
        public virtual DbSet<MesJobLog> MesJobLog { get; set; }
        public virtual DbSet<MfBan> MfBan { get; set; }
        public virtual DbSet<MfBom> MfBom { get; set; }
        public virtual DbSet<MfByjl> MfByjl { get; set; }
        public virtual DbSet<MfCk> MfCk { get; set; }
        public virtual DbSet<MfCs> MfCs { get; set; }
        public virtual DbSet<MfDs> MfDs { get; set; }
        public virtual DbSet<MfGrM> MfGrM { get; set; }
        public virtual DbSet<MfGrS> MfGrS { get; set; }
        public virtual DbSet<MfIc> MfIc { get; set; }
        public virtual DbSet<MfIj> MfIj { get; set; }
        public virtual DbSet<MfJh> MfJh { get; set; }
        public virtual DbSet<MfJj> MfJj { get; set; }
        public virtual DbSet<MfJxzbJs> MfJxzbJs { get; set; }
        public virtual DbSet<MfJxzbSz> MfJxzbSz { get; set; }
        public virtual DbSet<MfMdInout> MfMdInout { get; set; }
        public virtual DbSet<MfMjaa> MfMjaa { get; set; }
        public virtual DbSet<MfMkYg> MfMkYg { get; set; }
        public virtual DbSet<MfMl> MfMl { get; set; }
        public virtual DbSet<MfMm0> MfMm0 { get; set; }
        public virtual DbSet<MfMmjh> MfMmjh { get; set; }
        public virtual DbSet<MfMo> MfMo { get; set; }
        public virtual DbSet<MfMp> MfMp { get; set; }
        public virtual DbSet<MfMsc> MfMsc { get; set; }
        public virtual DbSet<MfPos> MfPos { get; set; }
        public virtual DbSet<MfPromv> MfPromv { get; set; }
        public virtual DbSet<MfPss> MfPss { get; set; }
        public virtual DbSet<MfPss0Z> MfPss0Z { get; set; }
        public virtual DbSet<MfQl> MfQl { get; set; }
        public virtual DbSet<MfQyM> MfQyM { get; set; }
        public virtual DbSet<MfQyS> MfQyS { get; set; }
        public virtual DbSet<MfRsc> MfRsc { get; set; }
        public virtual DbSet<MfRxM> MfRxM { get; set; }
        public virtual DbSet<MfRxS> MfRxS { get; set; }
        public virtual DbSet<MfSbaa> MfSbaa { get; set; }
        public virtual DbSet<MfSbycbg> MfSbycbg { get; set; }
        public virtual DbSet<MfSq> MfSq { get; set; }
        public virtual DbSet<MfSqd> MfSqd { get; set; }
        public virtual DbSet<MfStM> MfStM { get; set; }
        public virtual DbSet<MfStS> MfStS { get; set; }
        public virtual DbSet<MfTb> MfTb { get; set; }
        public virtual DbSet<MfTi> MfTi { get; set; }
        public virtual DbSet<MfTw> MfTw { get; set; }
        public virtual DbSet<MfTy> MfTy { get; set; }
        public virtual DbSet<MfTyprocjyZ> MfTyprocjyZ { get; set; }
        public virtual DbSet<MfTz> MfTz { get; set; }
        public virtual DbSet<MfUnqcRecord> MfUnqcRecord { get; set; }
        public virtual DbSet<MfUnqcprdhl> MfUnqcprdhl { get; set; }
        public virtual DbSet<MfVhid> MfVhid { get; set; }
        public virtual DbSet<MfWjM> MfWjM { get; set; }
        public virtual DbSet<MfWjS> MfWjS { get; set; }
        public virtual DbSet<MfWxM> MfWxM { get; set; }
        public virtual DbSet<MfWxS> MfWxS { get; set; }
        public virtual DbSet<MfZc> MfZc { get; set; }
        public virtual DbSet<MfZg> MfZg { get; set; }
        public virtual DbSet<MkYg> MkYg { get; set; }
        public virtual DbSet<Mkpg> Mkpg { get; set; }
        public virtual DbSet<Mkpgs> Mkpgs { get; set; }
        public virtual DbSet<MmMaterielRequest> MmMaterielRequest { get; set; }
        public virtual DbSet<MmMaterielRequestList> MmMaterielRequestList { get; set; }
        public virtual DbSet<ModDisqualreason> ModDisqualreason { get; set; }
        public virtual DbSet<ModRecord> ModRecord { get; set; }
        public virtual DbSet<MojGrp> MojGrp { get; set; }
        public virtual DbSet<Mold> Mold { get; set; }
        public virtual DbSet<MoldMaintainPlan> MoldMaintainPlan { get; set; }
        public virtual DbSet<MoldMaintainSpec> MoldMaintainSpec { get; set; }
        public virtual DbSet<MoldMtOrder> MoldMtOrder { get; set; }
        public virtual DbSet<MoldMtorderInfo> MoldMtorderInfo { get; set; }
        public virtual DbSet<MoldMtspecInfo> MoldMtspecInfo { get; set; }
        public virtual DbSet<MoldSpareparts> MoldSpareparts { get; set; }
        public virtual DbSet<MoldTypeinfo> MoldTypeinfo { get; set; }
        public virtual DbSet<MoldWh> MoldWh { get; set; }
        public virtual DbSet<MoldingDeviateT> MoldingDeviateT { get; set; }
        public virtual DbSet<MoldingDeviatesT> MoldingDeviatesT { get; set; }
        public virtual DbSet<MoldingRulesT> MoldingRulesT { get; set; }
        public virtual DbSet<MsAlert> MsAlert { get; set; }
        public virtual DbSet<MsBorrow> MsBorrow { get; set; }
        public virtual DbSet<MsCalcycChange> MsCalcycChange { get; set; }
        public virtual DbSet<MsCalinfo> MsCalinfo { get; set; }
        public virtual DbSet<MsCalinstitution> MsCalinstitution { get; set; }
        public virtual DbSet<MsCalnotice> MsCalnotice { get; set; }
        public virtual DbSet<MsCalnoticeInfo> MsCalnoticeInfo { get; set; }
        public virtual DbSet<MsCalplan> MsCalplan { get; set; }
        public virtual DbSet<MsCalplanInfo> MsCalplanInfo { get; set; }
        public virtual DbSet<MsCalrule> MsCalrule { get; set; }
        public virtual DbSet<MsFlowStatus> MsFlowStatus { get; set; }
        public virtual DbSet<MsMeasureInfo> MsMeasureInfo { get; set; }
        public virtual DbSet<MsMeasureInfoOld> MsMeasureInfoOld { get; set; }
        public virtual DbSet<MsMeasureStatus> MsMeasureStatus { get; set; }
        public virtual DbSet<MsMeasureType> MsMeasureType { get; set; }
        public virtual DbSet<MsRepair> MsRepair { get; set; }
        public virtual DbSet<Msgcache> Msgcache { get; set; }
        public virtual DbSet<MsmngStatusinfo> MsmngStatusinfo { get; set; }
        public virtual DbSet<MyWh> MyWh { get; set; }
        public virtual DbSet<NyxhRecord> NyxhRecord { get; set; }
        public virtual DbSet<OpWorkstart> OpWorkstart { get; set; }
        public virtual DbSet<Opsballot> Opsballot { get; set; }
        public virtual DbSet<PadInspectionOrderCategoryTotalQty> PadInspectionOrderCategoryTotalQty { get; set; }
        public virtual DbSet<PadInspectionOrderList> PadInspectionOrderList { get; set; }
        public virtual DbSet<Padppfi> Padppfi { get; set; }
        public virtual DbSet<PcBatchreview> PcBatchreview { get; set; }
        public virtual DbSet<PcInOutPutRelation> PcInOutPutRelation { get; set; }
        public virtual DbSet<PcIntegrityCheck> PcIntegrityCheck { get; set; }
        public virtual DbSet<PcOrderHeaterNum> PcOrderHeaterNum { get; set; }
        public virtual DbSet<PcOutPut> PcOutPut { get; set; }
        public virtual DbSet<PcOutPutDefect> PcOutPutDefect { get; set; }
        public virtual DbSet<PcTraceabilityDataPortal> PcTraceabilityDataPortal { get; set; }
        public virtual DbSet<PcTraceabilityLog> PcTraceabilityLog { get; set; }
        public virtual DbSet<PcTransfer> PcTransfer { get; set; }
        public virtual DbSet<PcUsrLogin> PcUsrLogin { get; set; }
        public virtual DbSet<PcWorkStationDeviceMapping> PcWorkStationDeviceMapping { get; set; }
        public virtual DbSet<PdHandover> PdHandover { get; set; }
        public virtual DbSet<PerfLosstimeT> PerfLosstimeT { get; set; }
        public virtual DbSet<PerfOeeT> PerfOeeT { get; set; }
        public virtual DbSet<PerfOutputT> PerfOutputT { get; set; }
        public virtual DbSet<PhotoTemp> PhotoTemp { get; set; }
        public virtual DbSet<PidsTemp> PidsTemp { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PpMoschedTemp> PpMoschedTemp { get; set; }
        public virtual DbSet<PpPlanOrder> PpPlanOrder { get; set; }
        public virtual DbSet<PpPlanOrders> PpPlanOrders { get; set; }
        public virtual DbSet<PpProductionOrder> PpProductionOrder { get; set; }
        public virtual DbSet<PpProductionOrders> PpProductionOrders { get; set; }
        public virtual DbSet<PpWorkCalendar> PpWorkCalendar { get; set; }
        public virtual DbSet<PpWorkOrder> PpWorkOrder { get; set; }
        public virtual DbSet<PpWorkOrderMats> PpWorkOrderMats { get; set; }
        public virtual DbSet<PpWorkOrderProcs> PpWorkOrderProcs { get; set; }
        public virtual DbSet<PpWorkOrderStation> PpWorkOrderStation { get; set; }
        public virtual DbSet<PpWorkPlan> PpWorkPlan { get; set; }
        public virtual DbSet<PrdParainfo> PrdParainfo { get; set; }
        public virtual DbSet<PrdParatype> PrdParatype { get; set; }
        public virtual DbSet<PrdSpc> PrdSpc { get; set; }
        public virtual DbSet<PrdStandard> PrdStandard { get; set; }
        public virtual DbSet<PrdStation> PrdStation { get; set; }
        public virtual DbSet<PrdStationPara> PrdStationPara { get; set; }
        public virtual DbSet<PrdTools> PrdTools { get; set; }
        public virtual DbSet<Prdandwh> Prdandwh { get; set; }
        public virtual DbSet<Prdt> Prdt { get; set; }
        public virtual DbSet<Prdt1> Prdt1 { get; set; }
        public virtual DbSet<Prdt1Info> Prdt1Info { get; set; }
        public virtual DbSet<PrdtChangeInfos> PrdtChangeInfos { get; set; }
        public virtual DbSet<PrdtCus1> PrdtCus1 { get; set; }
        public virtual DbSet<PrdtCus2> PrdtCus2 { get; set; }
        public virtual DbSet<PrdtUt> PrdtUt { get; set; }
        public virtual DbSet<Predefreason> Predefreason { get; set; }
        public virtual DbSet<Processinfo> Processinfo { get; set; }
        public virtual DbSet<QcBarcode> QcBarcode { get; set; }
        public virtual DbSet<QcDefectType> QcDefectType { get; set; }
        public virtual DbSet<QcFinished> QcFinished { get; set; }
        public virtual DbSet<QcInspFreq> QcInspFreq { get; set; }
        public virtual DbSet<QcItem> QcItem { get; set; }
        public virtual DbSet<QcPrdInspectSchemes> QcPrdInspectSchemes { get; set; }
        public virtual DbSet<QcPrdMeasureRecord> QcPrdMeasureRecord { get; set; }
        public virtual DbSet<QcPrdMeasureRecordItem> QcPrdMeasureRecordItem { get; set; }
        public virtual DbSet<QcPrdMeasureSchemes> QcPrdMeasureSchemes { get; set; }
        public virtual DbSet<QcPrdMeasureSchemesItem> QcPrdMeasureSchemesItem { get; set; }
        public virtual DbSet<QcPrdSqc> QcPrdSqc { get; set; }
        public virtual DbSet<QcPrdSqcItem> QcPrdSqcItem { get; set; }
        public virtual DbSet<QcPrj> QcPrj { get; set; }
        public virtual DbSet<QcPrjItem> QcPrjItem { get; set; }
        public virtual DbSet<QcPrjType> QcPrjType { get; set; }
        public virtual DbSet<QcRecord> QcRecord { get; set; }
        public virtual DbSet<QcRecordvalue> QcRecordvalue { get; set; }
        public virtual DbSet<QcTool> QcTool { get; set; }
        public virtual DbSet<Qcinterfacerecordd> Qcinterfacerecordd { get; set; }
        public virtual DbSet<Qcinterfacerecordm> Qcinterfacerecordm { get; set; }
        public virtual DbSet<Qcinterfacerecordv> Qcinterfacerecordv { get; set; }
        public virtual DbSet<Qciteminterface> Qciteminterface { get; set; }
        public virtual DbSet<QmInspectBill> QmInspectBill { get; set; }
        public virtual DbSet<QmInspectPlan> QmInspectPlan { get; set; }
        public virtual DbSet<QmInspectS> QmInspectS { get; set; }
        public virtual DbSet<QmInspectSd> QmInspectSd { get; set; }
        public virtual DbSet<QmInspectT> QmInspectT { get; set; }
        public virtual DbSet<QmInspectTd> QmInspectTd { get; set; }
        public virtual DbSet<QmInspectingOrder> QmInspectingOrder { get; set; }
        public virtual DbSet<QmInspectingRecord> QmInspectingRecord { get; set; }
        public virtual DbSet<QmInspectionTypeDevice> QmInspectionTypeDevice { get; set; }
        public virtual DbSet<QmMfQcXj> QmMfQcXj { get; set; }
        public virtual DbSet<QmProcessInspection> QmProcessInspection { get; set; }
        public virtual DbSet<QmSendInspectingOrder> QmSendInspectingOrder { get; set; }
        public virtual DbSet<QmSioBci> QmSioBci { get; set; }
        public virtual DbSet<QmTfQcXj> QmTfQcXj { get; set; }
        public virtual DbSet<QmTi> QmTi { get; set; }
        public virtual DbSet<QmTibarcode> QmTibarcode { get; set; }
        public virtual DbSet<QmTisub> QmTisub { get; set; }
        public virtual DbSet<QmTy> QmTy { get; set; }
        public virtual DbSet<QmTybarcode> QmTybarcode { get; set; }
        public virtual DbSet<QmTysub> QmTysub { get; set; }
        public virtual DbSet<QpisPicMap> QpisPicMap { get; set; }
        public virtual DbSet<QueryInspectionResult> QueryInspectionResult { get; set; }
        public virtual DbSet<RespInfo> RespInfo { get; set; }
        public virtual DbSet<RjgTzMap> RjgTzMap { get; set; }
        public virtual DbSet<RlSbei> RlSbei { get; set; }
        public virtual DbSet<RmCutterProdectMapping> RmCutterProdectMapping { get; set; }
        public virtual DbSet<RmCuttersCode> RmCuttersCode { get; set; }
        public virtual DbSet<RmCuttersLoss> RmCuttersLoss { get; set; }
        public virtual DbSet<RmCuttersProdMap> RmCuttersProdMap { get; set; }
        public virtual DbSet<RmCuttersSerialNumber> RmCuttersSerialNumber { get; set; }
        public virtual DbSet<RmCuttersTrace> RmCuttersTrace { get; set; }
        public virtual DbSet<RmCuttersUse> RmCuttersUse { get; set; }
        public virtual DbSet<RmFixtrueHis> RmFixtrueHis { get; set; }
        public virtual DbSet<RmFixtrueUse> RmFixtrueUse { get; set; }
        public virtual DbSet<RmFixtureLedger> RmFixtureLedger { get; set; }
        public virtual DbSet<RmFixtureProdectMapping> RmFixtureProdectMapping { get; set; }
        public virtual DbSet<RmFixtureSerialNumber> RmFixtureSerialNumber { get; set; }
        public virtual DbSet<RmMeasuringLedger> RmMeasuringLedger { get; set; }
        public virtual DbSet<RmMeasuringProdectMapping> RmMeasuringProdectMapping { get; set; }
        public virtual DbSet<RmMeasuringSerialNumber> RmMeasuringSerialNumber { get; set; }
        public virtual DbSet<RmMoldFaultDef> RmMoldFaultDef { get; set; }
        public virtual DbSet<RmMoldFaultReason> RmMoldFaultReason { get; set; }
        public virtual DbSet<RmMoldHis> RmMoldHis { get; set; }
        public virtual DbSet<RmMoldInspItems> RmMoldInspItems { get; set; }
        public virtual DbSet<RmMoldInspProgram> RmMoldInspProgram { get; set; }
        public virtual DbSet<RmMoldInspTask> RmMoldInspTask { get; set; }
        public virtual DbSet<RmMoldInspTaskItems> RmMoldInspTaskItems { get; set; }
        public virtual DbSet<RmMoldParts> RmMoldParts { get; set; }
        public virtual DbSet<RmMoldProdectMapping> RmMoldProdectMapping { get; set; }
        public virtual DbSet<RmMoldRepairRecord> RmMoldRepairRecord { get; set; }
        public virtual DbSet<RmMoldRepairRecordItem> RmMoldRepairRecordItem { get; set; }
        public virtual DbSet<RmMoldRepairRecordReason> RmMoldRepairRecordReason { get; set; }
        public virtual DbSet<RmMoldRepairRequest> RmMoldRepairRequest { get; set; }
        public virtual DbSet<RmMoldRepairRequestFault> RmMoldRepairRequestFault { get; set; }
        public virtual DbSet<RmMoldRepairRequestItem> RmMoldRepairRequestItem { get; set; }
        public virtual DbSet<RmMoldSparePartInfo> RmMoldSparePartInfo { get; set; }
        public virtual DbSet<RmMoldWhse> RmMoldWhse { get; set; }
        public virtual DbSet<RmToolType> RmToolType { get; set; }
        public virtual DbSet<Salm> Salm { get; set; }
        public virtual DbSet<SbChangeList> SbChangeList { get; set; }
        public virtual DbSet<SbChangeListView> SbChangeListView { get; set; }
        public virtual DbSet<SbDisqualreason> SbDisqualreason { get; set; }
        public virtual DbSet<SbFaultMeasure> SbFaultMeasure { get; set; }
        public virtual DbSet<SbLhjl> SbLhjl { get; set; }
        public virtual DbSet<SbMaintainPlan> SbMaintainPlan { get; set; }
        public virtual DbSet<SbMaintainRunRecord> SbMaintainRunRecord { get; set; }
        public virtual DbSet<SbMaintainSpec> SbMaintainSpec { get; set; }
        public virtual DbSet<SbMtOrder> SbMtOrder { get; set; }
        public virtual DbSet<SbMtRuntime> SbMtRuntime { get; set; }
        public virtual DbSet<SbMtorderInfo> SbMtorderInfo { get; set; }
        public virtual DbSet<SbMtspecInfo> SbMtspecInfo { get; set; }
        public virtual DbSet<SbOpMapping> SbOpMapping { get; set; }
        public virtual DbSet<SbParaBase> SbParaBase { get; set; }
        public virtual DbSet<SbParaRecord> SbParaRecord { get; set; }
        public virtual DbSet<SbParaSet> SbParaSet { get; set; }
        public virtual DbSet<SbPartchangeRecord> SbPartchangeRecord { get; set; }
        public virtual DbSet<SbPartinfo> SbPartinfo { get; set; }
        public virtual DbSet<SbPrdtPara> SbPrdtPara { get; set; }
        public virtual DbSet<SbPrdtParas> SbPrdtParas { get; set; }
        public virtual DbSet<SbQrcoderecord> SbQrcoderecord { get; set; }
        public virtual DbSet<SbRecord> SbRecord { get; set; }
        public virtual DbSet<SbRunRecord> SbRunRecord { get; set; }
        public virtual DbSet<SbRunRecordInfo> SbRunRecordInfo { get; set; }
        public virtual DbSet<SbRunStatus> SbRunStatus { get; set; }
        public virtual DbSet<SbSpRecord> SbSpRecord { get; set; }
        public virtual DbSet<SbSparePart> SbSparePart { get; set; }
        public virtual DbSet<SbSpareparts> SbSpareparts { get; set; }
        public virtual DbSet<SbStatusChange> SbStatusChange { get; set; }
        public virtual DbSet<SbStatusChanges> SbStatusChanges { get; set; }
        public virtual DbSet<SbTypeinfo> SbTypeinfo { get; set; }
        public virtual DbSet<Sbb> Sbb { get; set; }
        public virtual DbSet<Sbby> Sbby { get; set; }
        public virtual DbSet<SbbyDj> SbbyDj { get; set; }
        public virtual DbSet<SbbyNr> SbbyNr { get; set; }
        public virtual DbSet<SbbyPlan> SbbyPlan { get; set; }
        public virtual DbSet<SbbyPlanInfo> SbbyPlanInfo { get; set; }
        public virtual DbSet<SbbyPrj> SbbyPrj { get; set; }
        public virtual DbSet<ScSbxxb> ScSbxxb { get; set; }
        public virtual DbSet<SeasonDef> SeasonDef { get; set; }
        public virtual DbSet<SebIdx2> SebIdx2 { get; set; }
        public virtual DbSet<SebMojPw> SebMojPw { get; set; }
        public virtual DbSet<SebScope> SebScope { get; set; }
        public virtual DbSet<SebState> SebState { get; set; }
        public virtual DbSet<SebWr> SebWr { get; set; }
        public virtual DbSet<Sebei> Sebei { get; set; }
        public virtual DbSet<SebeiRecord> SebeiRecord { get; set; }
        public virtual DbSet<Setdefvalues> Setdefvalues { get; set; }
        public virtual DbSet<ShDj> ShDj { get; set; }
        public virtual DbSet<ShList> ShList { get; set; }
        public virtual DbSet<ShiftScheduling> ShiftScheduling { get; set; }
        public virtual DbSet<Sifilter> Sifilter { get; set; }
        public virtual DbSet<SourceInfo> SourceInfo { get; set; }
        public virtual DbSet<SpcLst> SpcLst { get; set; }
        public virtual DbSet<SpectrumTemp> SpectrumTemp { get; set; }
        public virtual DbSet<Sprd> Sprd { get; set; }
        public virtual DbSet<Sprd1> Sprd1 { get; set; }
        public virtual DbSet<StBarcodechange> StBarcodechange { get; set; }
        public virtual DbSet<StBarcodeinfo> StBarcodeinfo { get; set; }
        public virtual DbSet<StBarcodeinfos> StBarcodeinfos { get; set; }
        public virtual DbSet<StBarcodemergeinfo> StBarcodemergeinfo { get; set; }
        public virtual DbSet<StBarcoderes> StBarcoderes { get; set; }
        public virtual DbSet<StBarcodesplit> StBarcodesplit { get; set; }
        public virtual DbSet<StPalletcodeInfo> StPalletcodeInfo { get; set; }
        public virtual DbSet<StTdcodeBusi> StTdcodeBusi { get; set; }
        public virtual DbSet<StTdcodeBusiRecord> StTdcodeBusiRecord { get; set; }
        public virtual DbSet<StTdcodeInfo> StTdcodeInfo { get; set; }
        public virtual DbSet<StTdcodePallet> StTdcodePallet { get; set; }
        public virtual DbSet<StTdcodeTemp> StTdcodeTemp { get; set; }
        public virtual DbSet<StationSeb> StationSeb { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<SysAccountClose> SysAccountClose { get; set; }
        public virtual DbSet<SysAccountCloseItem> SysAccountCloseItem { get; set; }
        public virtual DbSet<SysAttachment> SysAttachment { get; set; }
        public virtual DbSet<SysAudBillInfo> SysAudBillInfo { get; set; }
        public virtual DbSet<SysAudBillItem> SysAudBillItem { get; set; }
        public virtual DbSet<SysAuditFlow> SysAuditFlow { get; set; }
        public virtual DbSet<SysAuditFlowDetails> SysAuditFlowDetails { get; set; }
        public virtual DbSet<SysAuditFlowUsr> SysAuditFlowUsr { get; set; }
        public virtual DbSet<SysBarcodeInfo> SysBarcodeInfo { get; set; }
        public virtual DbSet<SysBarcodeRule> SysBarcodeRule { get; set; }
        public virtual DbSet<SysBillnoInfo> SysBillnoInfo { get; set; }
        public virtual DbSet<SysBillnoInfoDel> SysBillnoInfoDel { get; set; }
        public virtual DbSet<SysBillnoRule> SysBillnoRule { get; set; }
        public virtual DbSet<SysBillnoRuleSet> SysBillnoRuleSet { get; set; }
        public virtual DbSet<SysBillnoTemp> SysBillnoTemp { get; set; }
        public virtual DbSet<SysBillsource> SysBillsource { get; set; }
        public virtual DbSet<SysBusino> SysBusino { get; set; }
        public virtual DbSet<SysCodenoRule> SysCodenoRule { get; set; }
        public virtual DbSet<SysCodenoRules> SysCodenoRules { get; set; }
        public virtual DbSet<SysDataRules> SysDataRules { get; set; }
        public virtual DbSet<SysFile> SysFile { get; set; }
        public virtual DbSet<SysFlow> SysFlow { get; set; }
        public virtual DbSet<SysFlowchart> SysFlowchart { get; set; }
        public virtual DbSet<SysFlowchartauthset> SysFlowchartauthset { get; set; }
        public virtual DbSet<SysFormnoInfo> SysFormnoInfo { get; set; }
        public virtual DbSet<SysInterfaceLog> SysInterfaceLog { get; set; }
        public virtual DbSet<SysInterfaceQueue> SysInterfaceQueue { get; set; }
        public virtual DbSet<SysInterfaceUrl> SysInterfaceUrl { get; set; }
        public virtual DbSet<SysLangData> SysLangData { get; set; }
        public virtual DbSet<SysMenuLocalSet> SysMenuLocalSet { get; set; }
        public virtual DbSet<SysMenuZc> SysMenuZc { get; set; }
        public virtual DbSet<SysOuterDbConnString> SysOuterDbConnString { get; set; }
        public virtual DbSet<SysParamGroups> SysParamGroups { get; set; }
        public virtual DbSet<SysParams> SysParams { get; set; }
        public virtual DbSet<SysProperty> SysProperty { get; set; }
        public virtual DbSet<SysPropertySet> SysPropertySet { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleData> SysRoleData { get; set; }
        public virtual DbSet<SysRoleDataBusi> SysRoleDataBusi { get; set; }
        public virtual DbSet<SysRoleField> SysRoleField { get; set; }
        public virtual DbSet<SysRoleMenu> SysRoleMenu { get; set; }
        public virtual DbSet<SysRoleMenuActions> SysRoleMenuActions { get; set; }
        public virtual DbSet<SysRoleUser> SysRoleUser { get; set; }
        public virtual DbSet<SysSummary> SysSummary { get; set; }
        public virtual DbSet<SysSummaryReporttemplate> SysSummaryReporttemplate { get; set; }
        public virtual DbSet<SysSummarySet> SysSummarySet { get; set; }
        public virtual DbSet<SysTerminal> SysTerminal { get; set; }
        public virtual DbSet<SysTerminalItems> SysTerminalItems { get; set; }
        public virtual DbSet<SysUniqueset> SysUniqueset { get; set; }
        public virtual DbSet<SysUpdateLog> SysUpdateLog { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<SysWarning> SysWarning { get; set; }
        public virtual DbSet<SysauditField> SysauditField { get; set; }
        public virtual DbSet<Sysbillnoset> Sysbillnoset { get; set; }
        public virtual DbSet<Sysmsg> Sysmsg { get; set; }
        public virtual DbSet<Sysmsgconfig> Sysmsgconfig { get; set; }
        public virtual DbSet<Sysmsgsetup> Sysmsgsetup { get; set; }
        public virtual DbSet<Sysmsgsetupinfo> Sysmsgsetupinfo { get; set; }
        public virtual DbSet<SzbDeleteBak20181019> SzbDeleteBak20181019 { get; set; }
        public virtual DbSet<T1> T1 { get; set; }
        public virtual DbSet<TBaseuserDevice> TBaseuserDevice { get; set; }
        public virtual DbSet<TDevicebindlog> TDevicebindlog { get; set; }
        public virtual DbSet<TTest> TTest { get; set; }
        public virtual DbSet<TUser> TUser { get; set; }
        public virtual DbSet<Table1> Table1 { get; set; }
        public virtual DbSet<Tasks> Task { get; set; }
        public virtual DbSet<TbBl> TbBl { get; set; }
        public virtual DbSet<TbCpmxrb> TbCpmxrb { get; set; }
        public virtual DbSet<TbInitwip> TbInitwip { get; set; }
        public virtual DbSet<TbJobbooking> TbJobbooking { get; set; }
        public virtual DbSet<TbOeeCq> TbOeeCq { get; set; }
        public virtual DbSet<TbPaintentry> TbPaintentry { get; set; }
        public virtual DbSet<TbPerfTimeservicelog> TbPerfTimeservicelog { get; set; }
        public virtual DbSet<TbQuota> TbQuota { get; set; }
        public virtual DbSet<TbRate> TbRate { get; set; }
        public virtual DbSet<TbRbHz> TbRbHz { get; set; }
        public virtual DbSet<TbRbMx> TbRbMx { get; set; }
        public virtual DbSet<TbRbMxMonth> TbRbMxMonth { get; set; }
        public virtual DbSet<TbReworkdayhz> TbReworkdayhz { get; set; }
        public virtual DbSet<TbSbrecordCameraMap> TbSbrecordCameraMap { get; set; }
        public virtual DbSet<TbSzbDaystatisticlog> TbSzbDaystatisticlog { get; set; }
        public virtual DbSet<TbSzbhzCq> TbSzbhzCq { get; set; }
        public virtual DbSet<TbSzdata> TbSzdata { get; set; }
        public virtual DbSet<TbTransferinout> TbTransferinout { get; set; }
        public virtual DbSet<TbTzrbHz> TbTzrbHz { get; set; }
        public virtual DbSet<TbTzrbMx> TbTzrbMx { get; set; }
        public virtual DbSet<TbTzrbMxMonth> TbTzrbMxMonth { get; set; }
        public virtual DbSet<TbWaste> TbWaste { get; set; }
        public virtual DbSet<TbWastetime> TbWastetime { get; set; }
        public virtual DbSet<TbXray> TbXray { get; set; }
        public virtual DbSet<TbXrayZb> TbXrayZb { get; set; }
        public virtual DbSet<TbXrayhgl> TbXrayhgl { get; set; }
        public virtual DbSet<TblBarcode> TblBarcode { get; set; }
        public virtual DbSet<TblProcessinfo> TblProcessinfo { get; set; }
        public virtual DbSet<TerminalAllot> TerminalAllot { get; set; }
        public virtual DbSet<TerminalSetup> TerminalSetup { get; set; }
        public virtual DbSet<Testi> Testi { get; set; }
        public virtual DbSet<TfBan> TfBan { get; set; }
        public virtual DbSet<TfBom> TfBom { get; set; }
        public virtual DbSet<TfBom2> TfBom2 { get; set; }
        public virtual DbSet<TfByjl> TfByjl { get; set; }
        public virtual DbSet<TfCk> TfCk { get; set; }
        public virtual DbSet<TfCs> TfCs { get; set; }
        public virtual DbSet<TfDs> TfDs { get; set; }
        public virtual DbSet<TfGrM> TfGrM { get; set; }
        public virtual DbSet<TfGrS> TfGrS { get; set; }
        public virtual DbSet<TfIc> TfIc { get; set; }
        public virtual DbSet<TfIj> TfIj { get; set; }
        public virtual DbSet<TfJh> TfJh { get; set; }
        public virtual DbSet<TfJj> TfJj { get; set; }
        public virtual DbSet<TfJxzbJs> TfJxzbJs { get; set; }
        public virtual DbSet<TfJxzbSz> TfJxzbSz { get; set; }
        public virtual DbSet<TfMdInout> TfMdInout { get; set; }
        public virtual DbSet<TfMjaa> TfMjaa { get; set; }
        public virtual DbSet<TfMl> TfMl { get; set; }
        public virtual DbSet<TfMm0> TfMm0 { get; set; }
        public virtual DbSet<TfMmjh> TfMmjh { get; set; }
        public virtual DbSet<TfMo> TfMo { get; set; }
        public virtual DbSet<TfMp1> TfMp1 { get; set; }
        public virtual DbSet<TfMp2> TfMp2 { get; set; }
        public virtual DbSet<TfMp3> TfMp3 { get; set; }
        public virtual DbSet<TfMsc> TfMsc { get; set; }
        public virtual DbSet<TfPos> TfPos { get; set; }
        public virtual DbSet<TfPromv> TfPromv { get; set; }
        public virtual DbSet<TfPss> TfPss { get; set; }
        public virtual DbSet<TfQl> TfQl { get; set; }
        public virtual DbSet<TfQyM> TfQyM { get; set; }
        public virtual DbSet<TfQyS> TfQyS { get; set; }
        public virtual DbSet<TfRsc> TfRsc { get; set; }
        public virtual DbSet<TfRxM> TfRxM { get; set; }
        public virtual DbSet<TfRxS> TfRxS { get; set; }
        public virtual DbSet<TfSbaa> TfSbaa { get; set; }
        public virtual DbSet<TfSbycbg> TfSbycbg { get; set; }
        public virtual DbSet<TfSbycbg1> TfSbycbg1 { get; set; }
        public virtual DbSet<TfSojh> TfSojh { get; set; }
        public virtual DbSet<TfSq> TfSq { get; set; }
        public virtual DbSet<TfSqd> TfSqd { get; set; }
        public virtual DbSet<TfStM> TfStM { get; set; }
        public virtual DbSet<TfStS> TfStS { get; set; }
        public virtual DbSet<TfTb> TfTb { get; set; }
        public virtual DbSet<TfTi> TfTi { get; set; }
        public virtual DbSet<TfTw> TfTw { get; set; }
        public virtual DbSet<TfTy> TfTy { get; set; }
        public virtual DbSet<TfTz> TfTz { get; set; }
        public virtual DbSet<TfUnqcRecord> TfUnqcRecord { get; set; }
        public virtual DbSet<TfUnqcdspInfos> TfUnqcdspInfos { get; set; }
        public virtual DbSet<TfUnqcprdhl> TfUnqcprdhl { get; set; }
        public virtual DbSet<TfVhid> TfVhid { get; set; }
        public virtual DbSet<TfWjM> TfWjM { get; set; }
        public virtual DbSet<TfWjS> TfWjS { get; set; }
        public virtual DbSet<TfWxM> TfWxM { get; set; }
        public virtual DbSet<TfWxS> TfWxS { get; set; }
        public virtual DbSet<TfZc> TfZc { get; set; }
        public virtual DbSet<TfZcRes> TfZcRes { get; set; }
        public virtual DbSet<TfZg> TfZg { get; set; }
        public virtual DbSet<TiType> TiType { get; set; }
        public virtual DbSet<TmpDphHgl> TmpDphHgl { get; set; }
        public virtual DbSet<TmpHjHgl> TmpHjHgl { get; set; }
        public virtual DbSet<TmpHuanmo> TmpHuanmo { get; set; }
        public virtual DbSet<TmpJjgHgl> TmpJjgHgl { get; set; }
        public virtual DbSet<TmpMaterials> TmpMaterials { get; set; }
        public virtual DbSet<TmpSzb> TmpSzb { get; set; }
        public virtual DbSet<TmpSzbdata> TmpSzbdata { get; set; }
        public virtual DbSet<TmpTzzmxl> TmpTzzmxl { get; set; }
        public virtual DbSet<TomesYplacebar> TomesYplacebar { get; set; }
        public virtual DbSet<Tool> Tool { get; set; }
        public virtual DbSet<ToolPrdt> ToolPrdt { get; set; }
        public virtual DbSet<TrayBarcodebinding> TrayBarcodebinding { get; set; }
        public virtual DbSet<TrayBarcodeinfos> TrayBarcodeinfos { get; set; }
        public virtual DbSet<Tt> Tt { get; set; }
        public virtual DbSet<Tt1> Tt1 { get; set; }
        public virtual DbSet<Tt2> Tt2 { get; set; }
        public virtual DbSet<TypeUnqualified> TypeUnqualified { get; set; }
        public virtual DbSet<TzBarcodeinfos> TzBarcodeinfos { get; set; }
        public virtual DbSet<TzMod> TzMod { get; set; }
        public virtual DbSet<TzSeb> TzSeb { get; set; }
        public virtual DbSet<TzSpectrumInfo> TzSpectrumInfo { get; set; }
        public virtual DbSet<TzscMap> TzscMap { get; set; }
        public virtual DbSet<TzscMap20184> TzscMap20184 { get; set; }
        public virtual DbSet<UnacceptedProductionHandle> UnacceptedProductionHandle { get; set; }
        public virtual DbSet<UnacceptedProductionHandleSub> UnacceptedProductionHandleSub { get; set; }
        public virtual DbSet<UnacceptedProductionHandleSubResult> UnacceptedProductionHandleSubResult { get; set; }
        public virtual DbSet<WhEntryBarcode> WhEntryBarcode { get; set; }
        public virtual DbSet<WhEntryInfo> WhEntryInfo { get; set; }
        public virtual DbSet<WhEntryTemp> WhEntryTemp { get; set; }
        public virtual DbSet<WhInventoryBarcode> WhInventoryBarcode { get; set; }
        public virtual DbSet<WhInventoryPart> WhInventoryPart { get; set; }
        public virtual DbSet<WmAsn> WmAsn { get; set; }
        public virtual DbSet<WmAsnBarcodeInfo> WmAsnBarcodeInfo { get; set; }
        public virtual DbSet<WmAsnItem> WmAsnItem { get; set; }
        public virtual DbSet<WmBarCodeScanTemp> WmBarCodeScanTemp { get; set; }
        public virtual DbSet<WmBarcode> WmBarcode { get; set; }
        public virtual DbSet<WmBarcodeBatchInfo> WmBarcodeBatchInfo { get; set; }
        public virtual DbSet<WmBarcodeBatchInfoHis> WmBarcodeBatchInfoHis { get; set; }
        public virtual DbSet<WmBarcodeSource> WmBarcodeSource { get; set; }
        public virtual DbSet<WmFeeding> WmFeeding { get; set; }
        public virtual DbSet<WmFeedingDetail> WmFeedingDetail { get; set; }
        public virtual DbSet<WmFeedingHistory> WmFeedingHistory { get; set; }
        public virtual DbSet<WmForm> WmForm { get; set; }
        public virtual DbSet<WmFormBarcodeInfo> WmFormBarcodeInfo { get; set; }
        public virtual DbSet<WmFormItem> WmFormItem { get; set; }
        public virtual DbSet<WmFormScene> WmFormScene { get; set; }
        public virtual DbSet<WmFormType> WmFormType { get; set; }
        public virtual DbSet<WmFreezeStorage> WmFreezeStorage { get; set; }
        public virtual DbSet<WmFreezeStorageHistory> WmFreezeStorageHistory { get; set; }
        public virtual DbSet<WmFrozenStorage> WmFrozenStorage { get; set; }
        public virtual DbSet<WmInventoryPlan> WmInventoryPlan { get; set; }
        public virtual DbSet<WmInventoryPlanBarcode> WmInventoryPlanBarcode { get; set; }
        public virtual DbSet<WmInventoryPlanItem> WmInventoryPlanItem { get; set; }
        public virtual DbSet<WmItemPageAge> WmItemPageAge { get; set; }
        public virtual DbSet<WmMaterialPreparaPlan> WmMaterialPreparaPlan { get; set; }
        public virtual DbSet<WmMaterialPreparaPlanBarcode> WmMaterialPreparaPlanBarcode { get; set; }
        public virtual DbSet<WmMaterialPreparaPlanItem> WmMaterialPreparaPlanItem { get; set; }
        public virtual DbSet<WmOnShelfGuide> WmOnShelfGuide { get; set; }
        public virtual DbSet<WmOnShelfGuideBarcode> WmOnShelfGuideBarcode { get; set; }
        public virtual DbSet<WmOnShelfGuideItem> WmOnShelfGuideItem { get; set; }
        public virtual DbSet<WmOnShelfGuideRule> WmOnShelfGuideRule { get; set; }
        public virtual DbSet<WmOrderBarsQty> WmOrderBarsQty { get; set; }
        public virtual DbSet<WmOutFormApply> WmOutFormApply { get; set; }
        public virtual DbSet<WmOutFormApplyBarcodeInfo> WmOutFormApplyBarcodeInfo { get; set; }
        public virtual DbSet<WmOutFormApplyItem> WmOutFormApplyItem { get; set; }
        public virtual DbSet<WmPackage> WmPackage { get; set; }
        public virtual DbSet<WmPackageBarcode> WmPackageBarcode { get; set; }
        public virtual DbSet<WmPackageBarcodeHistory> WmPackageBarcodeHistory { get; set; }
        public virtual DbSet<WmPackageBom> WmPackageBom { get; set; }
        public virtual DbSet<WmPackageBomItems> WmPackageBomItems { get; set; }
        public virtual DbSet<WmPackageChange> WmPackageChange { get; set; }
        public virtual DbSet<WmPackageFeed> WmPackageFeed { get; set; }
        public virtual DbSet<WmPackageSnMng> WmPackageSnMng { get; set; }
        public virtual DbSet<WmPackageType> WmPackageType { get; set; }
        public virtual DbSet<WmPackageTypeProduct> WmPackageTypeProduct { get; set; }
        public virtual DbSet<WmPackageTypeRelation> WmPackageTypeRelation { get; set; }
        public virtual DbSet<WmShelfGuide> WmShelfGuide { get; set; }
        public virtual DbSet<WmShelfGuideBarcode> WmShelfGuideBarcode { get; set; }
        public virtual DbSet<WmShelfGuideItem> WmShelfGuideItem { get; set; }
        public virtual DbSet<WmStock> WmStock { get; set; }
        public virtual DbSet<WmStorage> WmStorage { get; set; }
        public virtual DbSet<WmStorageBarcode> WmStorageBarcode { get; set; }
        public virtual DbSet<WmStorageBarcodeHistory> WmStorageBarcodeHistory { get; set; }
        public virtual DbSet<WmStorageBarcodeLock> WmStorageBarcodeLock { get; set; }
        public virtual DbSet<WmStorageHistory> WmStorageHistory { get; set; }
        public virtual DbSet<WmWareHouse> WmWareHouse { get; set; }
        public virtual DbSet<WmWareHouseProduct> WmWareHouseProduct { get; set; }
        public virtual DbSet<WorkGroup> WorkGroup { get; set; }
        public virtual DbSet<WorkShift> WorkShift { get; set; }
        public virtual DbSet<WsReturnMaterial> WsReturnMaterial { get; set; }
        public virtual DbSet<Ychj> Ychj { get; set; }
        public virtual DbSet<Yctl> Yctl { get; set; }
        public virtual DbSet<ZcNo> ZcNo { get; set; }
        public virtual DbSet<ZzSbmodBc> ZzSbmodBc { get; set; }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            /* Configure the shared tables (with included modules) here */

            builder.Entity<AppUser>(b =>
            {
                b.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users"); //Sharing the same table "AbpUsers" with the IdentityUser

                b.ConfigureByConvention();
                b.ConfigureAbpUser();

                /* Configure mappings for your additional properties
                 * Also see the MesEfCoreEntityExtensionMappings class
                 */
            });

            /* Configure your own tables/entities inside the ConfigureMes method */

            builder.ConfigureMes();

        }

    }
}